"use server";

import { revalidatePath } from "next/cache";

import { createAdminClient } from "@/lib/supabase/admin";
import {
  addDomainToVercel,
  removeDomainFromVercel,
} from "@/lib/domains/vercel";
import { verifyCname, verifyTxtToken } from "@/lib/domains/verify";

import { recordAdminAction } from "../_audit";
import { assertAdmin } from "../_lib";
import type {
  CustomDomainScope,
  CustomDomainStatus,
  WorkspaceCustomDomainRow,
} from "../_types";

/* Server actions for /admin/domains.
 *
 * Every action:
 *   - calls assertAdmin() at the top (RLS still enforces the same on
 *     the underlying tables, but we need the auth context for audit
 *     rows anyway).
 *   - records an audit row with the action verb prefixed `domain.`.
 *   - revalidates `/admin/domains` and the per-domain page so a
 *     follow-up navigation reflects the new state immediately.
 *
 * The DB has a CHECK constraint on `status`; we move it forward only
 * (pending → txt_verified → cname_verified → active → disabled). We
 * never demote unless the underlying verification fails, in which case
 * we leave the existing status alone and surface the error.
 */

const DOMAIN_RE = /^(?=.{1,253}$)([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$/;
const CNAME_TARGET = "cname.vercel-dns.com";

export interface ActionResult {
  ok: boolean;
  error?: string;
  message?: string;
}

function normalizeDomain(domain: string | null | undefined): string {
  return (domain ?? "")
    .trim()
    .toLowerCase()
    .replace(/^https?:\/\//, "")
    .replace(/\/.*$/, "");
}

async function fetchRow(
  id: string
): Promise<WorkspaceCustomDomainRow | null> {
  const admin = createAdminClient();
  const { data } = await admin
    .from("workspace_custom_domains")
    .select("*")
    .eq("id", id)
    .maybeSingle();
  return (data as WorkspaceCustomDomainRow | null) ?? null;
}

function revalidateAll(id?: string): void {
  revalidatePath("/admin/domains");
  if (id) revalidatePath(`/admin/domains/${id}`);
}

/* ──────────────────── add ──────────────────── */

export async function addDomain(formData: FormData): Promise<ActionResult> {
  try {
    await assertAdmin();
    const workspaceId = String(formData.get("workspace_id") ?? "").trim();
    const rawDomain = String(formData.get("domain") ?? "");
    const scope = (String(formData.get("scope") ?? "workspace").trim() ||
      "workspace") as CustomDomainScope;

    if (!workspaceId) return { ok: false, error: "workspace is required" };
    const domain = normalizeDomain(rawDomain);
    if (!domain || !DOMAIN_RE.test(domain)) {
      return { ok: false, error: "invalid domain" };
    }
    if (scope !== "workspace" && scope !== "toshare") {
      return { ok: false, error: "invalid scope" };
    }

    const admin = createAdminClient();

    // Confirm workspace exists so we don't insert an orphan FK row
    // (DB would also reject, but a friendlier error helps the UI).
    const { data: ws, error: wsErr } = await admin
      .from("workspaces")
      .select("id, name")
      .eq("id", workspaceId)
      .maybeSingle();
    if (wsErr) return { ok: false, error: wsErr.message };
    if (!ws) return { ok: false, error: "workspace not found" };

    const { data: inserted, error } = await admin
      .from("workspace_custom_domains")
      .insert({
        workspace_id: workspaceId,
        domain,
        scope,
        status: "pending" as CustomDomainStatus,
        // txt_token is auto-generated by the DB default
      })
      .select("*")
      .single();
    if (error) return { ok: false, error: error.message };

    await recordAdminAction({
      action: "domain.add",
      targetType: "workspace_custom_domain",
      targetId: (inserted as WorkspaceCustomDomainRow).id,
      after: inserted,
      metadata: { workspace_id: workspaceId, domain, scope },
    });

    revalidateAll();
    return { ok: true, message: "Domain added — awaiting DNS verification" };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) };
  }
}

/* ──────────────────── verify TXT ──────────────────── */

export async function verifyTxt(formData: FormData): Promise<ActionResult> {
  try {
    await assertAdmin();
    const id = String(formData.get("id") ?? "").trim();
    if (!id) return { ok: false, error: "missing id" };

    const before = await fetchRow(id);
    if (!before) return { ok: false, error: "domain not found" };

    const ok = await verifyTxtToken(before.domain, before.txt_token);
    const admin = createAdminClient();
    const now = new Date().toISOString();

    if (ok) {
      const nextStatus: CustomDomainStatus =
        before.status === "pending" || before.status === "failed"
          ? "txt_verified"
          : before.status;
      const { data: updated, error } = await admin
        .from("workspace_custom_domains")
        .update({
          txt_verified_at: now,
          status: nextStatus,
          updated_at: now,
        })
        .eq("id", id)
        .select("*")
        .single();
      if (error) return { ok: false, error: error.message };

      await recordAdminAction({
        action: "domain.verify_txt",
        targetType: "workspace_custom_domain",
        targetId: id,
        before,
        after: updated,
        metadata: { result: "ok", at: now },
      });

      revalidateAll(id);
      return { ok: true, message: "TXT verified" };
    }

    // Failure path: do NOT demote the status, just audit the miss. The
    // detail page surfaces the last attempt by reading the audit log.
    await recordAdminAction({
      action: "domain.verify_txt",
      targetType: "workspace_custom_domain",
      targetId: id,
      before,
      metadata: {
        result: "miss",
        at: now,
        expected_token: before.txt_token,
      },
    });

    revalidateAll(id);
    return {
      ok: false,
      error: `No matching TXT record at _spacefield-verify.${before.domain}`,
    };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) };
  }
}

/* ──────────────────── verify CNAME ──────────────────── */

export async function verifyCnameAction(
  formData: FormData
): Promise<ActionResult> {
  try {
    await assertAdmin();
    const id = String(formData.get("id") ?? "").trim();
    if (!id) return { ok: false, error: "missing id" };

    const before = await fetchRow(id);
    if (!before) return { ok: false, error: "domain not found" };
    if (!before.txt_verified_at) {
      return { ok: false, error: "verify TXT before CNAME" };
    }

    const expected = before.cname_target || CNAME_TARGET;
    const ok = await verifyCname(before.domain, expected);
    const admin = createAdminClient();
    const now = new Date().toISOString();

    if (ok) {
      const nextStatus: CustomDomainStatus =
        before.status === "active" || before.status === "disabled"
          ? before.status
          : "cname_verified";
      const { data: updated, error } = await admin
        .from("workspace_custom_domains")
        .update({
          cname_verified_at: now,
          status: nextStatus,
          updated_at: now,
        })
        .eq("id", id)
        .select("*")
        .single();
      if (error) return { ok: false, error: error.message };

      await recordAdminAction({
        action: "domain.verify_cname",
        targetType: "workspace_custom_domain",
        targetId: id,
        before,
        after: updated,
        metadata: { result: "ok", at: now, expected },
      });

      revalidateAll(id);
      return { ok: true, message: "CNAME verified" };
    }

    await recordAdminAction({
      action: "domain.verify_cname",
      targetType: "workspace_custom_domain",
      targetId: id,
      before,
      metadata: { result: "miss", at: now, expected },
    });

    revalidateAll(id);
    return {
      ok: false,
      error: `No matching CNAME on ${before.domain} (expected ${expected})`,
    };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) };
  }
}

/* ──────────────────── attach to Vercel ──────────────────── */

export async function attachToVercel(
  formData: FormData
): Promise<ActionResult> {
  try {
    await assertAdmin();
    const id = String(formData.get("id") ?? "").trim();
    if (!id) return { ok: false, error: "missing id" };

    const before = await fetchRow(id);
    if (!before) return { ok: false, error: "domain not found" };
    if (!before.txt_verified_at || !before.cname_verified_at) {
      return { ok: false, error: "TXT and CNAME must both verify first" };
    }

    const result = await addDomainToVercel(before.domain);

    const admin = createAdminClient();
    const now = new Date().toISOString();

    if (!result.ok) {
      await recordAdminAction({
        action: "domain.attach_vercel",
        targetType: "workspace_custom_domain",
        targetId: id,
        before,
        metadata: {
          result: "error",
          at: now,
          error: result.error,
          status: result.status,
        },
      });

      revalidateAll(id);
      return { ok: false, error: result.error ?? "Vercel attach failed" };
    }

    const { data: updated, error } = await admin
      .from("workspace_custom_domains")
      .update({
        added_to_vercel_at: now,
        status: "active" as CustomDomainStatus,
        updated_at: now,
      })
      .eq("id", id)
      .select("*")
      .single();
    if (error) return { ok: false, error: error.message };

    await recordAdminAction({
      action: "domain.attach_vercel",
      targetType: "workspace_custom_domain",
      targetId: id,
      before,
      after: updated,
      metadata: { result: "ok", at: now, status: result.status },
    });

    revalidateAll(id);
    return { ok: true, message: "Attached to Vercel — domain is active" };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) };
  }
}

/* ──────────────────── disable ──────────────────── */

export async function disableDomain(
  formData: FormData
): Promise<ActionResult> {
  try {
    await assertAdmin();
    const id = String(formData.get("id") ?? "").trim();
    if (!id) return { ok: false, error: "missing id" };

    const before = await fetchRow(id);
    if (!before) return { ok: false, error: "domain not found" };

    let removeErr: string | undefined;
    if (before.added_to_vercel_at) {
      const result = await removeDomainFromVercel(before.domain);
      if (!result.ok) removeErr = result.error;
    }

    const admin = createAdminClient();
    const now = new Date().toISOString();

    const { data: updated, error } = await admin
      .from("workspace_custom_domains")
      .update({
        status: "disabled" as CustomDomainStatus,
        added_to_vercel_at: null,
        updated_at: now,
      })
      .eq("id", id)
      .select("*")
      .single();
    if (error) return { ok: false, error: error.message };

    await recordAdminAction({
      action: "domain.disable",
      targetType: "workspace_custom_domain",
      targetId: id,
      before,
      after: updated,
      metadata: { at: now, vercel_remove_error: removeErr ?? null },
    });

    revalidateAll(id);
    return removeErr
      ? {
          ok: true,
          message: `Disabled (Vercel removal error: ${removeErr})`,
        }
      : { ok: true, message: "Domain disabled" };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) };
  }
}

/* ──────────────────── delete ──────────────────── */

export async function deleteDomain(
  formData: FormData
): Promise<ActionResult> {
  try {
    await assertAdmin();
    const id = String(formData.get("id") ?? "").trim();
    if (!id) return { ok: false, error: "missing id" };

    const before = await fetchRow(id);
    if (!before) return { ok: false, error: "domain not found" };

    let removeErr: string | undefined;
    if (before.added_to_vercel_at) {
      const result = await removeDomainFromVercel(before.domain);
      if (!result.ok) removeErr = result.error;
    }

    const admin = createAdminClient();
    const { error } = await admin
      .from("workspace_custom_domains")
      .delete()
      .eq("id", id);
    if (error) return { ok: false, error: error.message };

    await recordAdminAction({
      action: "domain.delete",
      targetType: "workspace_custom_domain",
      targetId: id,
      before,
      metadata: { vercel_remove_error: removeErr ?? null },
    });

    revalidateAll();
    return { ok: true, message: "Domain deleted" };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) };
  }
}
