// Developer Track Record Data
// Realistic data for 31 Dubai developers

export interface Developer {
  id: string;
  name: string;
  logo?: string;
  established: number;
  headquarters: string;
  totalProjects: number;
  completedProjects: number;
  ongoingProjects: number;
  upcomingProjects: number;
  deliveryScore: number;
  qualityScore: number;
  valueAppreciation: number;
  overallScore: number;
  avgPriceAppreciation3y: { min: number; max: number };
  notableProjects: string[];
  areasPresent: string[];
  propertyTypes: string[];
  priceRange: string;
  serviceChargeAvg: { min: number; max: number };
  knownFor: string;
  controversies: string | null;
  website: string;
  description: string;
  tags: string[];
}

export const DATA_UPDATED = "2026-03-26";

export const developers: Developer[] = [
  {
    id: "emaar",
    name: "Emaar Properties",
    established: 1997,
    headquarters: "Dubai, UAE",
    totalProjects: 95,
    completedProjects: 72,
    ongoingProjects: 16,
    upcomingProjects: 7,
    deliveryScore: 9.2,
    qualityScore: 9.5,
    valueAppreciation: 9.4,
    overallScore: 9.4,
    avgPriceAppreciation3y: { min: 35, max: 65 },
    notableProjects: ["Burj Khalifa", "Dubai Mall", "Dubai Marina", "Downtown Dubai", "Emaar Beachfront", "Dubai Hills Estate", "The Valley"],
    areasPresent: ["Downtown Dubai", "Dubai Marina", "Dubai Hills", "Arabian Ranches", "Emaar Beachfront", "Dubai Creek Harbour", "The Valley", "Rashid Yachts & Marina"],
    propertyTypes: ["Apartments", "Villas", "Townhouses", "Penthouses", "Mansions"],
    priceRange: "AED 800K - 100M+",
    serviceChargeAvg: { min: 15, max: 30 },
    knownFor: "Dubai's largest and most reputable developer. Built the Burj Khalifa and is synonymous with premium master-planned communities.",
    controversies: null,
    website: "https://www.emaar.com",
    description: "Emaar Properties is the most recognized developer in Dubai and one of the largest in the world. Behind iconic landmarks like Burj Khalifa and Dubai Mall, Emaar has shaped Dubai's skyline. Their master-planned communities consistently deliver strong capital appreciation and rental yields.",
    tags: ["luxury", "master-planned", "off-plan", "premium"],
  },
  {
    id: "damac",
    name: "DAMAC Properties",
    established: 2002,
    headquarters: "Dubai, UAE",
    totalProjects: 44,
    completedProjects: 30,
    ongoingProjects: 10,
    upcomingProjects: 4,
    deliveryScore: 6.5,
    qualityScore: 7.0,
    valueAppreciation: 7.2,
    overallScore: 6.9,
    avgPriceAppreciation3y: { min: 15, max: 40 },
    notableProjects: ["DAMAC Hills", "DAMAC Hills 2", "Cavalli Tower", "Safa One", "DAMAC Lagoons"],
    areasPresent: ["DAMAC Hills", "DAMAC Hills 2", "Business Bay", "Dubai Marina", "JLT", "DAMAC Lagoons"],
    propertyTypes: ["Apartments", "Villas", "Townhouses", "Hotel Apartments"],
    priceRange: "AED 500K - 50M",
    serviceChargeAvg: { min: 12, max: 25 },
    knownFor: "Branded luxury residences with partnerships including Cavalli, Versace, and Fendi. Known for aggressive marketing and large-scale communities.",
    controversies: "History of delivery delays on several projects. Some buyers have reported finish quality not matching showroom standards. DAMAC Hills 2 faced criticism for remote location and slow infrastructure development.",
    website: "https://www.damacproperties.com",
    description: "DAMAC Properties is a major Dubai developer known for luxury branded residences and large master-planned communities. While they deliver high-profile projects, they've faced criticism around delivery timelines and quality consistency across their portfolio.",
    tags: ["luxury", "master-planned", "off-plan", "branded"],
  },
  {
    id: "nakheel",
    name: "Nakheel",
    established: 2000,
    headquarters: "Dubai, UAE",
    totalProjects: 52,
    completedProjects: 42,
    ongoingProjects: 7,
    upcomingProjects: 3,
    deliveryScore: 7.5,
    qualityScore: 7.8,
    valueAppreciation: 8.5,
    overallScore: 7.9,
    avgPriceAppreciation3y: { min: 25, max: 55 },
    notableProjects: ["Palm Jumeirah", "The World Islands", "Dragon Mart", "Ibn Battuta Mall", "Nakheel Mall", "Palm Jebel Ali"],
    areasPresent: ["Palm Jumeirah", "Jumeirah Islands", "Jumeirah Park", "Jumeirah Village Circle", "Discovery Gardens", "International City", "Dragon City", "Palm Jebel Ali"],
    propertyTypes: ["Apartments", "Villas", "Townhouses", "Retail"],
    priceRange: "AED 400K - 200M+",
    serviceChargeAvg: { min: 10, max: 22 },
    knownFor: "Creator of the iconic Palm Jumeirah. Government-backed developer with massive land bank and master-planned communities across Dubai.",
    controversies: "The World Islands project faced years of delays. Some older projects like Discovery Gardens and International City had quality concerns. Now merged with Dubai Holding.",
    website: "https://www.nakheel.com",
    description: "Nakheel is the government-backed developer behind Palm Jumeirah, one of the most iconic developments in the world. With a massive portfolio spanning affordable to ultra-luxury, Nakheel properties — especially on the Palm — have seen exceptional appreciation.",
    tags: ["luxury", "master-planned", "affordable", "government"],
  },
  {
    id: "dubai-properties",
    name: "Dubai Properties",
    established: 2002,
    headquarters: "Dubai, UAE",
    totalProjects: 28,
    completedProjects: 22,
    ongoingProjects: 4,
    upcomingProjects: 2,
    deliveryScore: 7.0,
    qualityScore: 7.2,
    valueAppreciation: 7.5,
    overallScore: 7.2,
    avgPriceAppreciation3y: { min: 18, max: 40 },
    notableProjects: ["JBR", "Business Bay", "1/JBR", "Villanova", "Mudon", "La Vie"],
    areasPresent: ["Jumeirah Beach Residence", "Business Bay", "Dubailand", "Villanova", "Mudon", "Remraam"],
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    priceRange: "AED 500K - 30M",
    serviceChargeAvg: { min: 12, max: 20 },
    knownFor: "Part of Dubai Holding. Developed JBR and significant portions of Business Bay. Strong in both urban and suburban communities.",
    controversies: "Some projects in Dubailand faced extended delays. Business Bay projects had mixed quality reviews in earlier phases.",
    website: "https://www.dubaiproperties.ae",
    description: "Dubai Properties, a member of Dubai Holding, is behind some of Dubai's most popular residential addresses including JBR and parts of Business Bay. Their portfolio spans affordable suburban communities to premium waterfront living.",
    tags: ["master-planned", "off-plan", "government"],
  },
  {
    id: "meraas",
    name: "Meraas",
    established: 2007,
    headquarters: "Dubai, UAE",
    totalProjects: 22,
    completedProjects: 16,
    ongoingProjects: 4,
    upcomingProjects: 2,
    deliveryScore: 8.5,
    qualityScore: 9.0,
    valueAppreciation: 8.8,
    overallScore: 8.8,
    avgPriceAppreciation3y: { min: 30, max: 55 },
    notableProjects: ["City Walk", "Bluewaters Island", "La Mer", "Port de La Mer", "Bvlgari Resort & Residences", "Madinat Jumeirah Living"],
    areasPresent: ["City Walk", "Bluewaters", "La Mer", "Al Jaddaf", "Jumeirah", "Pearl Jumeirah"],
    propertyTypes: ["Apartments", "Villas", "Penthouses"],
    priceRange: "AED 1.5M - 80M",
    serviceChargeAvg: { min: 18, max: 35 },
    knownFor: "Premium lifestyle destinations with exceptional design and placemaking. Known for creating experiential communities rather than just buildings.",
    controversies: null,
    website: "https://www.meraas.com",
    description: "Meraas is a Dubai Holding company known for premium lifestyle destinations. City Walk, Bluewaters Island, and La Mer are among Dubai's most sought-after addresses. Their focus on design, retail integration, and community experience sets them apart.",
    tags: ["luxury", "premium", "lifestyle"],
  },
  {
    id: "sobha",
    name: "Sobha Realty",
    established: 1976,
    headquarters: "Dubai, UAE",
    totalProjects: 18,
    completedProjects: 12,
    ongoingProjects: 4,
    upcomingProjects: 2,
    deliveryScore: 8.8,
    qualityScore: 9.3,
    valueAppreciation: 8.5,
    overallScore: 8.9,
    avgPriceAppreciation3y: { min: 30, max: 60 },
    notableProjects: ["Sobha Hartland", "Sobha Hartland II", "Sobha One", "Sobha SeaHaven", "Sobha Reserve"],
    areasPresent: ["Mohammed Bin Rashid City", "Sobha Hartland", "Dubai Maritime City", "Dubai Harbour"],
    propertyTypes: ["Apartments", "Villas", "Townhouses", "Penthouses"],
    priceRange: "AED 1M - 70M",
    serviceChargeAvg: { min: 14, max: 25 },
    knownFor: "Backward-integrated developer that controls every aspect of construction. Renowned for exceptional build quality and finishing — often considered the best in Dubai.",
    controversies: null,
    website: "https://www.sobharealty.com",
    description: "Sobha Realty is India-origin developer founded by PNC Menon, known for obsessive quality control. As a backward-integrated company, they manufacture their own materials including marble, glass, and metal works. Sobha Hartland has become one of Dubai's most desirable communities.",
    tags: ["luxury", "premium", "off-plan"],
  },
  {
    id: "azizi",
    name: "Azizi Developments",
    established: 2007,
    headquarters: "Dubai, UAE",
    totalProjects: 40,
    completedProjects: 22,
    ongoingProjects: 14,
    upcomingProjects: 4,
    deliveryScore: 5.5,
    qualityScore: 5.8,
    valueAppreciation: 6.5,
    overallScore: 5.9,
    avgPriceAppreciation3y: { min: 12, max: 30 },
    notableProjects: ["Azizi Riviera", "Azizi Venice", "Azizi Creek Views", "Azizi Aura"],
    areasPresent: ["MBR City", "Al Furjan", "Dubai Healthcare City", "Palm Jumeirah", "Dubai South", "Studio City"],
    propertyTypes: ["Apartments", "Studios", "Hotel Apartments"],
    priceRange: "AED 350K - 15M",
    serviceChargeAvg: { min: 10, max: 18 },
    knownFor: "High-volume affordable developer targeting first-time buyers and investors. Aggressive launch pace with attractive payment plans.",
    controversies: "Multiple projects have faced significant delivery delays. Quality complaints are common among handover buyers. High density in some projects has raised livability concerns.",
    website: "https://www.azizidevelopments.com",
    description: "Azizi Developments is one of Dubai's most prolific developers in the affordable-to-mid segment. With projects concentrated in MBR City, Al Furjan, and Healthcare City, they target investors seeking entry-level pricing. However, delivery timelines and quality consistency remain concerns.",
    tags: ["affordable", "off-plan", "high-volume"],
  },
  {
    id: "danube",
    name: "Danube Properties",
    established: 2014,
    headquarters: "Dubai, UAE",
    totalProjects: 30,
    completedProjects: 14,
    ongoingProjects: 12,
    upcomingProjects: 4,
    deliveryScore: 6.0,
    qualityScore: 6.0,
    valueAppreciation: 6.8,
    overallScore: 6.3,
    avgPriceAppreciation3y: { min: 15, max: 35 },
    notableProjects: ["Bayz 101", "Fashionz", "Eleganz", "Diamondz", "Oceanz"],
    areasPresent: ["JVC", "Business Bay", "Al Furjan", "Arjan", "JLT", "Dubai Science Park", "Maritime City"],
    propertyTypes: ["Apartments", "Studios", "Furnished Apartments"],
    priceRange: "AED 400K - 8M",
    serviceChargeAvg: { min: 12, max: 20 },
    knownFor: "Pioneered the 1% monthly payment plan model in Dubai. Known for naming projects with 'z' suffix and targeting the affordable luxury segment.",
    controversies: "Rapid launch pace has raised questions about delivery capacity. Some early projects had quality issues. Furnishing quality in handed-over units sometimes differs from marketing materials.",
    website: "https://www.danubeproperties.ae",
    description: "Danube Properties, an offshoot of the Danube Group (building materials), has become one of Dubai's most active developers. Their 1% monthly payment plans have made property ownership accessible to a wider audience. Projects are typically in the affordable-to-mid segment with full furnishing.",
    tags: ["affordable", "off-plan", "furnished"],
  },
  {
    id: "binghatti",
    name: "Binghatti Developers",
    established: 2014,
    headquarters: "Dubai, UAE",
    totalProjects: 25,
    completedProjects: 10,
    ongoingProjects: 11,
    upcomingProjects: 4,
    deliveryScore: 6.2,
    qualityScore: 6.5,
    valueAppreciation: 6.8,
    overallScore: 6.5,
    avgPriceAppreciation3y: { min: 15, max: 35 },
    notableProjects: ["Mercedes-Benz Places", "Binghatti Ghost", "Binghatti Crescent", "Binghatti Ivory"],
    areasPresent: ["Business Bay", "JVC", "Dubai Silicon Oasis", "Al Jaddaf", "Liwan"],
    propertyTypes: ["Apartments", "Studios", "Branded Residences"],
    priceRange: "AED 400K - 20M",
    serviceChargeAvg: { min: 11, max: 20 },
    knownFor: "Distinctive architectural style with geometric Islamic patterns. Recently partnered with Mercedes-Benz and Jacob & Co for branded residences.",
    controversies: "Some earlier projects in DSO and Liwan had quality concerns. Rapid scaling has raised questions about maintaining quality across many simultaneous projects.",
    website: "https://www.binghatti.com",
    description: "Binghatti has quickly risen from a small Dubai developer to a high-profile brand, known for striking geometric facades inspired by Islamic architecture. Their partnership with Mercedes-Benz and Jacob & Co has elevated their positioning, though they're still proving consistency across their growing portfolio.",
    tags: ["affordable", "off-plan", "branded", "mid-range"],
  },
  {
    id: "omniyat",
    name: "Omniyat",
    established: 2005,
    headquarters: "Dubai, UAE",
    totalProjects: 14,
    completedProjects: 10,
    ongoingProjects: 3,
    upcomingProjects: 1,
    deliveryScore: 8.5,
    qualityScore: 9.2,
    valueAppreciation: 8.8,
    overallScore: 8.8,
    avgPriceAppreciation3y: { min: 30, max: 55 },
    notableProjects: ["The Opus by Zaha Hadid", "One Palm", "The Alba", "The Lana (Dorchester Collection)", "AVA at Palm Jumeirah"],
    areasPresent: ["Palm Jumeirah", "Business Bay", "Marasi Marina", "Al Sufouh"],
    propertyTypes: ["Apartments", "Penthouses", "Ultra-luxury Residences"],
    priceRange: "AED 3M - 150M+",
    serviceChargeAvg: { min: 25, max: 50 },
    knownFor: "Ultra-luxury developer collaborating with world-renowned architects like Zaha Hadid. Every project is a statement piece with museum-quality finishing.",
    controversies: null,
    website: "https://www.omniyat.com",
    description: "Omniyat is Dubai's boutique ultra-luxury developer, creating architectural masterpieces in prime locations. Their collaboration with Zaha Hadid on The Opus and Dorchester Collection on The Lana demonstrates their commitment to exceptional design and hospitality-grade finishing.",
    tags: ["luxury", "premium", "ultra-luxury"],
  },
  {
    id: "select-group",
    name: "Select Group",
    established: 2002,
    headquarters: "Dubai, UAE",
    totalProjects: 18,
    completedProjects: 14,
    ongoingProjects: 3,
    upcomingProjects: 1,
    deliveryScore: 7.8,
    qualityScore: 7.5,
    valueAppreciation: 7.8,
    overallScore: 7.7,
    avgPriceAppreciation3y: { min: 20, max: 45 },
    notableProjects: ["Marina Gate", "The Residences at Business Central", "Peninsula by Select Group", "Six Senses Residences The Palm"],
    areasPresent: ["Dubai Marina", "Business Bay", "JLT", "Palm Jumeirah"],
    propertyTypes: ["Apartments", "Penthouses", "Branded Residences"],
    priceRange: "AED 800K - 50M",
    serviceChargeAvg: { min: 14, max: 28 },
    knownFor: "Focused mid-to-luxury developer with strong track record in Dubai Marina. Known for delivering on time with consistent quality.",
    controversies: null,
    website: "https://www.select-group.ae",
    description: "Select Group is a respected Dubai developer with a focused portfolio of quality projects, primarily in Dubai Marina and Business Bay. Their Marina Gate towers are among the most popular in the Marina, and their Six Senses collaboration on the Palm marks a move into ultra-luxury.",
    tags: ["luxury", "off-plan", "mid-range"],
  },
  {
    id: "ellington",
    name: "Ellington Properties",
    established: 2014,
    headquarters: "Dubai, UAE",
    totalProjects: 20,
    completedProjects: 12,
    ongoingProjects: 6,
    upcomingProjects: 2,
    deliveryScore: 8.0,
    qualityScore: 8.5,
    valueAppreciation: 8.0,
    overallScore: 8.2,
    avgPriceAppreciation3y: { min: 25, max: 45 },
    notableProjects: ["Belgravia", "DT1", "Wilton Terraces", "The Crestmark", "One River Point"],
    areasPresent: ["JVC", "MBR City", "Business Bay", "Downtown", "Palm Jumeirah"],
    propertyTypes: ["Apartments", "Townhouses", "Villas"],
    priceRange: "AED 800K - 30M",
    serviceChargeAvg: { min: 14, max: 22 },
    knownFor: "Design-led developer with a focus on aesthetics, lifestyle, and curated living experiences. Known for lush landscaping and boutique feel.",
    controversies: null,
    website: "https://www.ellingtonproperties.com",
    description: "Ellington Properties has earned a reputation as Dubai's design-led developer, focusing on aesthetics, green spaces, and lifestyle-oriented communities. Their projects in JVC and MBR City have been well-received for quality finishing and thoughtful design details.",
    tags: ["luxury", "off-plan", "design-led"],
  },
  {
    id: "mag",
    name: "MAG Property Development",
    established: 2003,
    headquarters: "Dubai, UAE",
    totalProjects: 16,
    completedProjects: 10,
    ongoingProjects: 4,
    upcomingProjects: 2,
    deliveryScore: 5.8,
    qualityScore: 5.5,
    valueAppreciation: 5.8,
    overallScore: 5.7,
    avgPriceAppreciation3y: { min: 10, max: 25 },
    notableProjects: ["MAG Eye", "MAG 5 Boulevard", "MAG City", "MAG 318"],
    areasPresent: ["MBR City", "Dubai South", "Al Furjan", "JVC"],
    propertyTypes: ["Apartments", "Studios", "Townhouses"],
    priceRange: "AED 300K - 5M",
    serviceChargeAvg: { min: 8, max: 15 },
    knownFor: "Budget-friendly developer offering entry-level properties in emerging areas. Part of MAG Group, a diversified conglomerate.",
    controversies: "Several projects experienced significant delays. Quality has been inconsistent, with some buyers reporting subpar finishing. Some cancelled projects in earlier years.",
    website: "https://www.magld.com",
    description: "MAG Property Development offers some of the most affordable entry points into Dubai real estate. While pricing is attractive, the developer has had mixed reviews on delivery timelines and finishing quality. Part of the larger MAG Group conglomerate.",
    tags: ["affordable", "off-plan", "budget"],
  },
  {
    id: "deyaar",
    name: "Deyaar Development",
    established: 2002,
    headquarters: "Dubai, UAE",
    totalProjects: 22,
    completedProjects: 18,
    ongoingProjects: 3,
    upcomingProjects: 1,
    deliveryScore: 6.5,
    qualityScore: 6.2,
    valueAppreciation: 6.0,
    overallScore: 6.2,
    avgPriceAppreciation3y: { min: 10, max: 28 },
    notableProjects: ["Midtown", "The Atria", "Mont Rose", "Regalia"],
    areasPresent: ["Dubai Production City", "Business Bay", "Dubai Marina", "Al Barsha"],
    propertyTypes: ["Apartments", "Studios", "Commercial"],
    priceRange: "AED 350K - 8M",
    serviceChargeAvg: { min: 10, max: 18 },
    knownFor: "Listed developer (DFM) focused on affordable-to-mid segment. Strong in Dubai Production City with their Midtown community.",
    controversies: "Some earlier projects faced delays and quality issues. Financial difficulties during the 2008-2010 downturn affected project delivery.",
    website: "https://www.deyaar.ae",
    description: "Deyaar is a publicly listed developer on the Dubai Financial Market, focusing on affordable and mid-range properties. Their Midtown project in Dubai Production City is their flagship community. The company has stabilized after facing challenges during the 2008 financial crisis.",
    tags: ["affordable", "off-plan", "mid-range"],
  },
  {
    id: "tiger-group",
    name: "Tiger Group",
    established: 1976,
    headquarters: "Dubai, UAE",
    totalProjects: 20,
    completedProjects: 14,
    ongoingProjects: 4,
    upcomingProjects: 2,
    deliveryScore: 6.0,
    qualityScore: 5.8,
    valueAppreciation: 5.5,
    overallScore: 5.8,
    avgPriceAppreciation3y: { min: 8, max: 22 },
    notableProjects: ["Tiger Tower", "Sky Tower", "Tiger Court", "Tiger Palm 5"],
    areasPresent: ["JLT", "Business Bay", "Al Furjan", "Dubai Sports City"],
    propertyTypes: ["Apartments", "Studios", "Hotel Apartments"],
    priceRange: "AED 300K - 5M",
    serviceChargeAvg: { min: 10, max: 16 },
    knownFor: "Long-established group with presence across real estate, retail, and F&B. Known for affordable towers in JLT and Business Bay.",
    controversies: "Quality has been a recurring concern. Some projects have had persistent maintenance issues. Several handover delays across their portfolio.",
    website: "https://www.tigergroup.ae",
    description: "Tiger Group is a long-established Dubai conglomerate with a real estate arm focused on affordable apartments and hotel apartments. While their pricing is competitive, quality and maintenance have been persistent areas of concern for residents.",
    tags: ["affordable", "budget"],
  },
  {
    id: "samana",
    name: "Samana Developers",
    established: 2017,
    headquarters: "Dubai, UAE",
    totalProjects: 28,
    completedProjects: 8,
    ongoingProjects: 15,
    upcomingProjects: 5,
    deliveryScore: 6.5,
    qualityScore: 6.8,
    valueAppreciation: 6.5,
    overallScore: 6.6,
    avgPriceAppreciation3y: { min: 15, max: 30 },
    notableProjects: ["Samana Golf Avenue", "Samana Waves", "Samana Manhattan", "Samana Skyros", "Samana Portofino"],
    areasPresent: ["JVC", "Arjan", "Al Furjan", "Dubai Studio City", "JLT"],
    propertyTypes: ["Apartments", "Studios", "Furnished Apartments"],
    priceRange: "AED 400K - 5M",
    serviceChargeAvg: { min: 12, max: 18 },
    knownFor: "Fast-growing developer with resort-style amenities including private pools for many units. Aggressive launch schedule with attractive payment plans.",
    controversies: "Very rapid launch pace has raised sustainability concerns. As a relatively new developer, long-term track record is still being established. Some concern about oversaturation in JVC.",
    website: "https://www.samana-developers.com",
    description: "Samana Developers has rapidly scaled since 2017, launching projects at an aggressive pace primarily in JVC and Arjan. Their USP is resort-style living with private pools in many units. While pricing is attractive, their ability to deliver on all simultaneous projects is still being tested.",
    tags: ["affordable", "off-plan", "resort-style"],
  },
  {
    id: "object-one",
    name: "Object One",
    established: 2019,
    headquarters: "Dubai, UAE",
    totalProjects: 6,
    completedProjects: 2,
    ongoingProjects: 3,
    upcomingProjects: 1,
    deliveryScore: 6.0,
    qualityScore: 6.5,
    valueAppreciation: 5.5,
    overallScore: 6.0,
    avgPriceAppreciation3y: { min: 10, max: 22 },
    notableProjects: ["Object One Tower", "Object One Residences"],
    areasPresent: ["JVC", "Business Bay", "Dubai South"],
    propertyTypes: ["Apartments", "Studios"],
    priceRange: "AED 400K - 3M",
    serviceChargeAvg: { min: 10, max: 16 },
    knownFor: "Relatively new boutique developer with modern design aesthetic targeting mid-range buyers.",
    controversies: "Limited track record makes long-term assessment difficult. Still proving delivery capabilities.",
    website: "https://www.object.one",
    description: "Object One is a newer entrant in Dubai's real estate market, focusing on modern, design-forward apartments in mid-range areas. As a young developer, their long-term track record is still being established.",
    tags: ["off-plan", "mid-range", "boutique"],
  },
  {
    id: "vincitore",
    name: "Vincitore Real Estate Development",
    established: 2014,
    headquarters: "Dubai, UAE",
    totalProjects: 8,
    completedProjects: 4,
    ongoingProjects: 3,
    upcomingProjects: 1,
    deliveryScore: 6.2,
    qualityScore: 6.0,
    valueAppreciation: 5.8,
    overallScore: 6.0,
    avgPriceAppreciation3y: { min: 10, max: 25 },
    notableProjects: ["Vincitore Benessere", "Vincitore Boulevard", "Vincitore Palacio"],
    areasPresent: ["Arjan", "Dubai Studio City", "Dubai Sports City"],
    propertyTypes: ["Apartments", "Studios"],
    priceRange: "AED 350K - 3M",
    serviceChargeAvg: { min: 10, max: 16 },
    knownFor: "Italian-themed affordable developer focused on Arjan area. Known for decent finishing at entry-level prices.",
    controversies: "Some delivery delays reported. Limited presence outside of Arjan.",
    website: "https://www.vincitore.com",
    description: "Vincitore offers Italian-inspired design at affordable price points, primarily in Dubai's Arjan community. While they've carved a niche in the affordable segment, their portfolio is relatively concentrated geographically.",
    tags: ["affordable", "off-plan", "budget"],
  },
  {
    id: "reportage",
    name: "Reportage Properties",
    established: 2014,
    headquarters: "Abu Dhabi, UAE",
    totalProjects: 15,
    completedProjects: 8,
    ongoingProjects: 5,
    upcomingProjects: 2,
    deliveryScore: 6.5,
    qualityScore: 6.2,
    valueAppreciation: 6.0,
    overallScore: 6.2,
    avgPriceAppreciation3y: { min: 10, max: 25 },
    notableProjects: ["Reportage Village", "Reem Hills", "Leonardo Residences", "Alexis Tower"],
    areasPresent: ["JVC", "Dubailand", "MBR City"],
    propertyTypes: ["Apartments", "Studios", "Townhouses"],
    priceRange: "AED 350K - 5M",
    serviceChargeAvg: { min: 10, max: 16 },
    knownFor: "Abu Dhabi-based developer expanding into Dubai with affordable apartments and townhouses in emerging communities.",
    controversies: "Some projects have faced delays. Quality reviews are mixed.",
    website: "https://www.reportageproperties.com",
    description: "Reportage Properties is an Abu Dhabi-origin developer that has expanded into Dubai's affordable segment. Their projects in JVC and Dubailand target budget-conscious buyers and investors seeking entry-level properties.",
    tags: ["affordable", "off-plan", "budget"],
  },
  {
    id: "seven-tides",
    name: "Seven Tides",
    established: 2004,
    headquarters: "Dubai, UAE",
    totalProjects: 8,
    completedProjects: 6,
    ongoingProjects: 1,
    upcomingProjects: 1,
    deliveryScore: 7.5,
    qualityScore: 7.5,
    valueAppreciation: 7.8,
    overallScore: 7.6,
    avgPriceAppreciation3y: { min: 20, max: 45 },
    notableProjects: ["Dukes The Palm", "Anantara The Palm", "SE7EN Residences", "SE7EN City"],
    areasPresent: ["Palm Jumeirah", "JLT", "Al Barari"],
    propertyTypes: ["Hotel Apartments", "Apartments", "Serviced Residences"],
    priceRange: "AED 800K - 20M",
    serviceChargeAvg: { min: 15, max: 30 },
    knownFor: "Hospitality-focused developer with premium hotel residences on Palm Jumeirah. Strong rental yields from hotel-operated units.",
    controversies: null,
    website: "https://www.seventides.com",
    description: "Seven Tides is a boutique developer specializing in hospitality-linked residences. Their Dukes and Anantara properties on Palm Jumeirah offer strong rental returns through hotel management programs, making them popular with investors seeking hassle-free income.",
    tags: ["luxury", "hospitality", "investment"],
  },
  {
    id: "aldar",
    name: "Aldar Properties",
    established: 2004,
    headquarters: "Abu Dhabi, UAE",
    totalProjects: 35,
    completedProjects: 25,
    ongoingProjects: 7,
    upcomingProjects: 3,
    deliveryScore: 8.5,
    qualityScore: 8.5,
    valueAppreciation: 8.0,
    overallScore: 8.3,
    avgPriceAppreciation3y: { min: 25, max: 50 },
    notableProjects: ["Yas Island", "Saadiyat Island", "Al Raha Beach", "Aldar HQ", "Haven by Aldar (Dubai)"],
    areasPresent: ["Yas Island", "Saadiyat Island", "Reem Island", "Al Raha Beach", "Dubai (expanding)"],
    propertyTypes: ["Apartments", "Villas", "Townhouses", "Commercial"],
    priceRange: "AED 600K - 40M",
    serviceChargeAvg: { min: 12, max: 22 },
    knownFor: "Abu Dhabi's largest developer, now expanding into Dubai. Known for high-quality master-planned communities and government backing.",
    controversies: null,
    website: "https://www.aldar.com",
    description: "Aldar Properties is Abu Dhabi's largest and most prominent developer, publicly listed on ADX. Behind iconic projects like Yas Island and Saadiyat Island, they've recently expanded into Dubai. Strong financials, government backing, and consistent delivery make them one of the UAE's most reliable developers.",
    tags: ["luxury", "master-planned", "government", "premium"],
  },
  {
    id: "dirc",
    name: "DIRC (Dubai Investments Real Estate Company)",
    established: 1995,
    headquarters: "Dubai, UAE",
    totalProjects: 12,
    completedProjects: 10,
    ongoingProjects: 1,
    upcomingProjects: 1,
    deliveryScore: 7.0,
    qualityScore: 6.8,
    valueAppreciation: 6.5,
    overallScore: 6.8,
    avgPriceAppreciation3y: { min: 12, max: 28 },
    notableProjects: ["Green Community", "Ritaj", "Mirdif Hills"],
    areasPresent: ["Dubai Investments Park", "Green Community", "Mirdif"],
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    priceRange: "AED 400K - 8M",
    serviceChargeAvg: { min: 10, max: 18 },
    knownFor: "Subsidiary of Dubai Investments. Known for Green Community, a well-established family-friendly gated community in DIP.",
    controversies: "Some projects in DIP have had limited appreciation due to remote location.",
    website: "https://www.dfrproperty.com",
    description: "DIRC, the real estate arm of Dubai Investments, is known for the well-regarded Green Community development in Dubai Investments Park. Their projects tend to be family-oriented with good green spaces, though locations can be distant from central Dubai.",
    tags: ["mid-range", "master-planned", "family"],
  },
  {
    id: "imtiaz",
    name: "Imtiaz Developments",
    established: 2008,
    headquarters: "Dubai, UAE",
    totalProjects: 10,
    completedProjects: 5,
    ongoingProjects: 3,
    upcomingProjects: 2,
    deliveryScore: 6.0,
    qualityScore: 6.0,
    valueAppreciation: 5.8,
    overallScore: 5.9,
    avgPriceAppreciation3y: { min: 10, max: 22 },
    notableProjects: ["Solitaire Cascades", "Solitaire Tower", "SLS Residences"],
    areasPresent: ["JVC", "Business Bay", "Dubai Marina"],
    propertyTypes: ["Apartments", "Studios"],
    priceRange: "AED 400K - 5M",
    serviceChargeAvg: { min: 10, max: 16 },
    knownFor: "Mid-range developer focused on JVC and Business Bay with reasonably priced apartments.",
    controversies: "Some projects have experienced delays. Limited brand recognition compared to larger developers.",
    website: "https://www.imtiazdevelopments.ae",
    description: "Imtiaz Developments operates in the mid-range segment, offering apartments in popular areas like JVC and Business Bay. They're a smaller developer still building their reputation in a competitive market.",
    tags: ["affordable", "off-plan", "mid-range"],
  },
  {
    id: "nshama",
    name: "Nshama",
    established: 2014,
    headquarters: "Dubai, UAE",
    totalProjects: 8,
    completedProjects: 5,
    ongoingProjects: 2,
    upcomingProjects: 1,
    deliveryScore: 7.5,
    qualityScore: 7.0,
    valueAppreciation: 7.5,
    overallScore: 7.3,
    avgPriceAppreciation3y: { min: 20, max: 40 },
    notableProjects: ["Town Square Dubai", "Rawda Apartments", "Hayat Townhouses", "Safi Apartments"],
    areasPresent: ["Town Square Dubai", "Al Quoz"],
    propertyTypes: ["Apartments", "Townhouses"],
    priceRange: "AED 400K - 4M",
    serviceChargeAvg: { min: 10, max: 16 },
    knownFor: "Created Town Square Dubai, one of the largest affordable master-planned communities in Dubai with extensive parks and amenities.",
    controversies: "Town Square is relatively remote from central Dubai. Some concerns about density in later phases.",
    website: "https://www.nshama.com",
    description: "Nshama is best known for Town Square Dubai, a massive affordable master-planned community near Al Barsha South. The development features Dubai's largest community park, extensive retail, and a family-friendly environment at accessible prices.",
    tags: ["affordable", "master-planned", "family"],
  },
  {
    id: "union-properties",
    name: "Union Properties",
    established: 1987,
    headquarters: "Dubai, UAE",
    totalProjects: 15,
    completedProjects: 12,
    ongoingProjects: 2,
    upcomingProjects: 1,
    deliveryScore: 5.5,
    qualityScore: 5.5,
    valueAppreciation: 5.0,
    overallScore: 5.3,
    avgPriceAppreciation3y: { min: 5, max: 18 },
    notableProjects: ["Motor City", "Green Community (Motorcity)", "Dubai Autodrome"],
    areasPresent: ["Motor City", "Dubai Silicon Oasis", "Dubailand"],
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    priceRange: "AED 350K - 8M",
    serviceChargeAvg: { min: 8, max: 16 },
    knownFor: "One of Dubai's oldest developers, behind Motor City. Listed on DFM but has faced financial and governance challenges.",
    controversies: "Significant financial difficulties and governance issues. Board disputes and management changes have affected operations. Several projects faced delays or cancellation. Share price has declined substantially from peak.",
    website: "https://www.up.ae",
    description: "Union Properties is one of Dubai's oldest listed developers, best known for Motor City and the Dubai Autodrome. However, the company has faced significant financial challenges, governance controversies, and a declining share price in recent years.",
    tags: ["mid-range", "affordable"],
  },
  {
    id: "meydan",
    name: "Meydan Group",
    established: 2007,
    headquarters: "Dubai, UAE",
    totalProjects: 14,
    completedProjects: 8,
    ongoingProjects: 4,
    upcomingProjects: 2,
    deliveryScore: 6.8,
    qualityScore: 7.5,
    valueAppreciation: 7.5,
    overallScore: 7.3,
    avgPriceAppreciation3y: { min: 18, max: 40 },
    notableProjects: ["Meydan Racecourse", "Meydan One", "Meydan Avenue", "The Galleries at Meydan"],
    areasPresent: ["Meydan", "MBR City", "Nad Al Sheba"],
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    priceRange: "AED 600K - 15M",
    serviceChargeAvg: { min: 12, max: 22 },
    knownFor: "Government-backed developer known for the iconic Meydan Racecourse. Now merged with Dubai Holding alongside Nakheel.",
    controversies: "Meydan One mega-project has faced significant delays and scope changes. Some buyers have waited years beyond original handover dates.",
    website: "https://www.meydan.ae",
    description: "Meydan Group, now part of Dubai Holding, is the developer behind the Meydan Racecourse district. Their master plan envisions a massive mixed-use development in the heart of MBR City, though the ambitious Meydan One project has faced notable delays.",
    tags: ["luxury", "master-planned", "government"],
  },
  {
    id: "jge",
    name: "Jumeirah Golf Estates (JGE)",
    established: 2003,
    headquarters: "Dubai, UAE",
    totalProjects: 6,
    completedProjects: 4,
    ongoingProjects: 1,
    upcomingProjects: 1,
    deliveryScore: 7.5,
    qualityScore: 8.0,
    valueAppreciation: 7.5,
    overallScore: 7.7,
    avgPriceAppreciation3y: { min: 20, max: 45 },
    notableProjects: ["Fire Course", "Earth Course", "Alandalus", "Redwood Park"],
    areasPresent: ["Jumeirah Golf Estates"],
    propertyTypes: ["Villas", "Townhouses", "Apartments"],
    priceRange: "AED 1.5M - 30M",
    serviceChargeAvg: { min: 12, max: 22 },
    knownFor: "Premium golf community with championship courses. Home to the DP World Tour Championship. Excellent for families seeking villa lifestyle.",
    controversies: "Original masterplan was much larger; several phases were delayed or redesigned after 2008 crisis.",
    website: "https://www.jumeirahgolfestates.com",
    description: "Jumeirah Golf Estates is a premium gated community built around two championship golf courses (Earth and Fire). It's home to the DP World Tour Championship and offers spacious villas and townhouses in a lush, green setting. Popular with families and golf enthusiasts.",
    tags: ["luxury", "master-planned", "golf", "family"],
  },
  {
    id: "majid-al-futtaim",
    name: "Majid Al Futtaim",
    established: 1992,
    headquarters: "Dubai, UAE",
    totalProjects: 10,
    completedProjects: 7,
    ongoingProjects: 2,
    upcomingProjects: 1,
    deliveryScore: 8.5,
    qualityScore: 8.5,
    valueAppreciation: 8.0,
    overallScore: 8.3,
    avgPriceAppreciation3y: { min: 22, max: 45 },
    notableProjects: ["Tilal Al Ghaf", "Mall of the Emirates", "City Centre Mirdif", "Al Zahia (Sharjah)"],
    areasPresent: ["Tilal Al Ghaf", "Dubai Lifestyle City"],
    propertyTypes: ["Villas", "Townhouses", "Apartments"],
    priceRange: "AED 1.5M - 25M",
    serviceChargeAvg: { min: 14, max: 22 },
    knownFor: "Retail and entertainment giant behind Mall of the Emirates. Their Tilal Al Ghaf community is one of Dubai's best master-planned villa developments.",
    controversies: null,
    website: "https://www.majidalfuttaim.com",
    description: "Majid Al Futtaim is a diversified conglomerate best known for Mall of the Emirates and Carrefour in the region. Their real estate arm has delivered Tilal Al Ghaf, one of Dubai's most successful villa communities, featuring a lagoon, extensive amenities, and high-quality construction.",
    tags: ["luxury", "master-planned", "family", "premium"],
  },
  {
    id: "wasl",
    name: "wasl Asset Management",
    established: 2008,
    headquarters: "Dubai, UAE",
    totalProjects: 30,
    completedProjects: 25,
    ongoingProjects: 3,
    upcomingProjects: 2,
    deliveryScore: 7.5,
    qualityScore: 7.0,
    valueAppreciation: 7.0,
    overallScore: 7.2,
    avgPriceAppreciation3y: { min: 15, max: 35 },
    notableProjects: ["wasl1", "wasl Port Views", "wasl Tower", "Al Khail Heights"],
    areasPresent: ["Al Karama", "Deira", "Oud Metha", "Al Garhoud", "Jumeirah"],
    propertyTypes: ["Apartments", "Commercial", "Retail"],
    priceRange: "AED 400K - 10M",
    serviceChargeAvg: { min: 8, max: 16 },
    knownFor: "Government-owned asset management company managing a massive portfolio of properties across old and new Dubai. Major landlord in Karama and Deira.",
    controversies: null,
    website: "https://www.wasl.ae",
    description: "wasl Asset Management is a government-owned entity managing one of Dubai's largest real estate portfolios. They own and operate properties across residential, commercial, and retail sectors, with a strong presence in established neighborhoods like Karama, Deira, and Oud Metha.",
    tags: ["government", "mid-range", "affordable"],
  },
  {
    id: "al-habtoor",
    name: "Al Habtoor Group",
    established: 1970,
    headquarters: "Dubai, UAE",
    totalProjects: 8,
    completedProjects: 6,
    ongoingProjects: 1,
    upcomingProjects: 1,
    deliveryScore: 8.0,
    qualityScore: 8.2,
    valueAppreciation: 7.5,
    overallScore: 7.9,
    avgPriceAppreciation3y: { min: 20, max: 42 },
    notableProjects: ["Al Habtoor City", "Habtoor Grand Resort", "The Residences at Al Habtoor City", "Al Habtoor Tower"],
    areasPresent: ["Sheikh Zayed Road", "Dubai Marina", "JBR"],
    propertyTypes: ["Apartments", "Penthouses", "Hotel Apartments"],
    priceRange: "AED 1M - 40M",
    serviceChargeAvg: { min: 18, max: 30 },
    knownFor: "Prestigious family conglomerate with Al Habtoor City being their landmark mixed-use development featuring three hotels (Westin, W, St. Regis).",
    controversies: null,
    website: "https://www.habtoor.com",
    description: "Al Habtoor Group is one of the UAE's most established family conglomerates. Their Al Habtoor City development on Sheikh Zayed Road is a landmark mixed-use complex featuring three luxury hotels and premium residences. Quality and finishing are consistently high across their limited but prestigious portfolio.",
    tags: ["luxury", "premium", "hospitality"],
  },
  {
    id: "kleindienst",
    name: "Kleindienst Group",
    established: 2003,
    headquarters: "Dubai, UAE",
    totalProjects: 4,
    completedProjects: 2,
    ongoingProjects: 1,
    upcomingProjects: 1,
    deliveryScore: 5.0,
    qualityScore: 7.0,
    valueAppreciation: 6.5,
    overallScore: 6.2,
    avgPriceAppreciation3y: { min: 10, max: 30 },
    notableProjects: ["The Heart of Europe", "Côte d'Azur", "Sweden Beach Palace", "Floating Seahorse Villas"],
    areasPresent: ["The World Islands"],
    propertyTypes: ["Villas", "Penthouses", "Floating Villas", "Hotel Apartments"],
    priceRange: "AED 2M - 100M+",
    serviceChargeAvg: { min: 30, max: 60 },
    knownFor: "Developing 'The Heart of Europe' on The World Islands with themed island resorts. Known for the unique Floating Seahorse underwater villas.",
    controversies: "The Heart of Europe project has faced very long delays, originally announced over a decade ago with completion pushed multiple times. Questions about feasibility and timeline persist.",
    website: "https://www.thoe.com",
    description: "Kleindienst Group is the developer behind The Heart of Europe on The World Islands, an ambitious project featuring European-themed island resorts and the unique Floating Seahorse underwater villas. While the concept is extraordinary, the project has faced extensive delays spanning many years.",
    tags: ["luxury", "ultra-luxury", "unique"],
  },
];
