/* Server-side email sending via Resend.
 *
 * Use this for transactional notifications generated by app logic
 * (workspace invites, comment notifications, etc.) — anything that
 * isn't a Supabase Auth-triggered email.
 *
 * Auth emails (signup confirm, magic link, password reset, email change)
 * are handled by Supabase Auth which is wired to use Resend's SMTP. Don't
 * call sendEmail() for those — Supabase does it.
 *
 * Always run on the server (Route Handlers, Server Actions, GitHub
 * Actions). The RESEND_API_KEY env var is server-only.
 */

import "server-only";
import { Resend } from "resend";
import { SENDERS, type EmailRole } from "./email-senders";

const apiKey = process.env.RESEND_API_KEY;
const resend = apiKey ? new Resend(apiKey) : null;

export interface SendEmailArgs {
  to: string | string[];
  subject: string;
  html: string;
  /** Plain-text fallback. Auto-derived from html if not given. */
  text?: string;
  /** Sender role (info / support / sales / hello / noreply / invites /
   *  security / legal) OR a literal "Name <addr>" string for ad-hoc use. */
  from?: EmailRole | string;
  replyTo?: string;
}

export async function sendEmail({
  to,
  subject,
  html,
  text,
  from = "noreply",
  replyTo,
}: SendEmailArgs): Promise<{ id: string } | null> {
  if (!resend) {
    console.warn("[email] RESEND_API_KEY not set — skipping send");
    return null;
  }

  // Resolve role → sender or use literal string
  const role = SENDERS[from as EmailRole] as
    | (typeof SENDERS)[EmailRole]
    | undefined;
  const fromHeader = role ? role.from : (from as string);
  const replyToHeader = replyTo ?? role?.replyTo;

  const { data, error } = await resend.emails.send({
    from: fromHeader,
    to: Array.isArray(to) ? to : [to],
    subject,
    html,
    text:
      text ??
      html
        .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, "")
        .replace(/<[^>]+>/g, " ")
        .replace(/\s+/g, " ")
        .trim(),
    replyTo: replyToHeader,
  });
  if (error) {
    console.error("[email] send failed:", error);
    throw new Error(error.message ?? "email send failed");
  }
  return data ? { id: data.id } : null;
}

/* Notify the team inbox about something that happened in the app
 * (new contact form submission, payment lead, security report, etc.).
 * Goes to the role's `inbox` (currently hello@example.com via
 * forwards once inbound is wired). */
export async function notifyTeam(args: {
  role: EmailRole;
  subject: string;
  html: string;
  /** Optional reply-to so the team can reply directly to the user. */
  replyTo?: string;
}): Promise<{ id: string } | null> {
  const sender = SENDERS[args.role];
  return sendEmail({
    from: args.role,
    to: sender.inbox,
    subject: args.subject,
    html: args.html,
    replyTo: args.replyTo,
  });
}

/* Pre-built templates — keep markup minimal and inline-styled so it
 * renders consistently across mail clients. */

export function workspaceInviteEmail(args: {
  inviteeName: string | null;
  inviterName: string;
  workspaceName: string;
  role: "member" | "admin";
  acceptUrl: string;
}): { subject: string; html: string } {
  const { inviteeName, inviterName, workspaceName, role, acceptUrl } = args;
  const greeting = inviteeName ? `Hi ${escapeHtml(inviteeName)},` : "Hi,";
  return {
    subject: `${inviterName} invited you to ${workspaceName} on Space Field`,
    html: `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; max-width: 560px; margin: 0 auto; padding: 32px 16px; color: #0a0a0a;">
        <h1 style="margin: 0 0 8px; font-size: 22px; font-weight: 700; letter-spacing: -0.01em;">You're invited to a workspace</h1>
        <p style="margin: 0 0 24px; color: #555; font-size: 14px; line-height: 1.6;">${greeting}</p>
        <p style="margin: 0 0 16px; font-size: 15px; line-height: 1.7;">
          <strong>${escapeHtml(inviterName)}</strong> has invited you to join the workspace
          <strong>${escapeHtml(workspaceName)}</strong> on Space Field as a
          <strong>${role}</strong>.
        </p>
        <p style="margin: 0 0 32px; font-size: 14px; color: #555; line-height: 1.6;">
          Members share dock, widgets, and installed tools — switch to the workspace
          and you'll see exactly what ${escapeHtml(inviterName)} set up.
        </p>
        <a href="${escapeHtml(acceptUrl)}"
           style="display: inline-block; padding: 12px 22px; background: #7c3aed; color: #fff; text-decoration: none; border-radius: 8px; font-weight: 500; font-size: 14px;">
          Accept invitation
        </a>
        <p style="margin: 32px 0 0; font-size: 12px; color: #999; line-height: 1.6;">
          If you don't want to join, you can ignore this email. The link expires in 14 days.
        </p>
        <hr style="border: 0; border-top: 1px solid #eee; margin: 32px 0;">
        <p style="margin: 0; font-size: 11px; color: #999;">
          <a href="https://spacefield.co" style="color: #999; text-decoration: none;">spacefield.co</a>
          — your workspace, in the browser.
        </p>
      </div>
    `,
  };
}

/* Welcome email — sent on first sign-up confirmation. */
export function welcomeEmail(args: {
  name: string | null;
}): { subject: string; html: string } {
  const greeting = args.name ? `Hi ${escapeHtml(args.name)},` : "Hi,";
  return {
    subject: "Welcome to Space Field",
    html: emailWrap(`
      <h1 style="${H1}">Welcome aboard.</h1>
      <p style="${P}">${greeting}</p>
      <p style="${P}">
        Space Field is a desktop OS in your browser. Create workspaces,
        install tools, invite collaborators — your work follows you across
        devices.
      </p>
      <p style="${P}">A few quick starts:</p>
      <ul style="${UL}">
        <li>Press <strong>⌘ K</strong> anywhere to open the launcher.</li>
        <li>Click your avatar (top-right) to manage your profile.</li>
        <li>Right-click the dock to customize what's pinned.</li>
        <li>File menu → New Workspace to set up a second one.</li>
      </ul>
      ${button("Open Space Field", "https://spacefield.co")}
      <p style="${SMALL}">
        Reply to this email any time — it goes straight to us.
      </p>
    `),
  };
}

/* Notify the inviter when their invitee accepts. */
export function inviteAcceptedEmail(args: {
  inviterName: string | null;
  acceptedBy: string;
  workspaceName: string;
  role: "member" | "admin";
}): { subject: string; html: string } {
  const greeting = args.inviterName
    ? `Hi ${escapeHtml(args.inviterName)},`
    : "Hi,";
  return {
    subject: `${args.acceptedBy} joined ${args.workspaceName}`,
    html: emailWrap(`
      <h1 style="${H1}">Your invite was accepted.</h1>
      <p style="${P}">${greeting}</p>
      <p style="${P}">
        <strong>${escapeHtml(args.acceptedBy)}</strong> just joined
        <strong>${escapeHtml(args.workspaceName)}</strong> as a
        <strong>${args.role}</strong>.
      </p>
      ${button("Open the workspace", "https://spacefield.co")}
    `),
  };
}

/* Auto-reply when someone submits the contact form. */
export function contactReceivedEmail(args: {
  name: string | null;
  topic: string;
}): { subject: string; html: string } {
  const greeting = args.name ? `Hi ${escapeHtml(args.name)},` : "Hi,";
  return {
    subject: "We got your message",
    html: emailWrap(`
      <h1 style="${H1}">Got it — thanks.</h1>
      <p style="${P}">${greeting}</p>
      <p style="${P}">
        We received your <strong>${escapeHtml(
          args.topic
        )}</strong> message and will reply within a day or two.
      </p>
      <p style="${P}">
        In the meantime, the workspace is at
        <a href="https://spacefield.co" style="${LINK}">spacefield.co</a>.
      </p>
    `),
  };
}

/* ───────────────── shared template chrome ───────────────── */

const FONT =
  "font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;";
const H1 =
  "margin: 0 0 12px; font-size: 22px; font-weight: 700; letter-spacing: -0.01em; color: #0a0a0a;";
const P = "margin: 0 0 16px; font-size: 15px; line-height: 1.65; color: #2a2a2a;";
const UL =
  "margin: 0 0 16px; padding-left: 18px; font-size: 14px; line-height: 1.6; color: #2a2a2a;";
const LINK = "color: #7c3aed; text-decoration: underline;";
const SMALL =
  "margin: 32px 0 0; font-size: 12px; color: #888; line-height: 1.6;";

function emailWrap(inner: string): string {
  return `
    <div style="${FONT} max-width: 560px; margin: 0 auto; padding: 32px 16px; color: #0a0a0a;">
      <div style="margin-bottom: 32px;">
        <span style="display: inline-block; font-size: 14px; font-weight: 700; letter-spacing: -0.01em; color: #0a0a0a;">
          Space Field
        </span>
      </div>
      ${inner}
      <hr style="border: 0; border-top: 1px solid #eee; margin: 32px 0;">
      <p style="margin: 0; font-size: 11px; color: #999; ${FONT}">
        <a href="https://spacefield.co" style="color: #999; text-decoration: none;">spacefield.co</a>
        — your workspace, in the browser.
      </p>
    </div>
  `;
}

function button(label: string, href: string): string {
  return `
    <p style="margin: 24px 0;">
      <a href="${escapeHtml(href)}"
         style="display: inline-block; padding: 12px 22px; background: #7c3aed; color: #fff; text-decoration: none; border-radius: 8px; font-weight: 500; font-size: 14px;">
        ${escapeHtml(label)}
      </a>
    </p>
  `;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
