// =============================================================================
// Global Real Estate Market Data — Curated Dataset
// Last full refresh: 2025-Q1
// Update frequency: Monthly (owner manually updates values + lastUpdated field)
// =============================================================================

export interface CityData {
  id: string;
  name: string;
  country: string;
  countryCode: string;
  region: string;

  // Property Prices
  avgPricePerSqft: number | null;
  avgPricePerSqm: number | null;
  avgApartmentPrice: number | null;
  priceChangeYoY: number | null;
  priceChange5Y: number | null;

  // Rental Market
  avgRentalYield: number | null;
  avgMonthlyRent1BR: number | null;
  avgMonthlyRent2BR: number | null;
  rentChangeYoY: number | null;

  // Affordability
  priceToIncomeRatio: number | null;
  mortgageRate: number | null;
  maxLTV: number | null;

  // Investment Environment
  foreignOwnershipAllowed: "yes" | "limited" | "no";
  freeholdAvailable: boolean;
  goldenVisaThreshold: number | null;
  propertyTaxRate: number | null;
  capitalGainsTax: number | null;
  rentalIncomeTax: number | null;
  transactionCostBuyer: number | null;
  transactionCostSeller: number | null;

  // Market Size & Liquidity
  annualTransactions: number | null;
  avgDaysOnMarket: number | null;
  newSupplyPipeline: "high" | "medium" | "low" | null;

  // Quality of Life Context
  safetyIndex: number | null;
  qualityOfLifeIndex: number | null;

  // Data freshness
  lastUpdated: string;
}

export const REGIONS = {
  "Middle East": ["dubai", "abu-dhabi", "riyadh", "doha", "muscat"],
  Europe: [
    "london",
    "paris",
    "berlin",
    "munich",
    "madrid",
    "barcelona",
    "amsterdam",
    "lisbon",
    "istanbul",
    "athens",
    "milan",
    "rome",
    "zurich",
    "vienna",
    "prague",
    "warsaw",
    "budapest",
    "dublin",
  ],
  Americas: [
    "new-york",
    "miami",
    "los-angeles",
    "san-francisco",
    "toronto",
    "vancouver",
    "sao-paulo",
    "mexico-city",
  ],
  Asia: [
    "singapore",
    "hong-kong",
    "tokyo",
    "shanghai",
    "beijing",
    "mumbai",
    "bangkok",
    "kuala-lumpur",
    "seoul",
    "jakarta",
  ],
  Oceania: ["sydney", "melbourne", "auckland"],
  Africa: ["cape-town", "nairobi", "cairo"],
} as const;

export type Region = keyof typeof REGIONS;

// ---------------------------------------------------------------------------
// CITY DATA
// ---------------------------------------------------------------------------

export const CITY_DATA: CityData[] = [
  // ===========================================================================
  // MIDDLE EAST
  // ===========================================================================
  {
    id: "dubai",
    name: "Dubai",
    country: "United Arab Emirates",
    countryCode: "AE",
    region: "Middle East",
    avgPricePerSqft: 475,
    avgPricePerSqm: 5112,
    avgApartmentPrice: 550000,
    priceChangeYoY: 18,
    priceChange5Y: 55,
    avgRentalYield: 7.0,
    avgMonthlyRent1BR: 2200,
    avgMonthlyRent2BR: 3500,
    rentChangeYoY: 15,
    priceToIncomeRatio: 7.5,
    mortgageRate: 4.75,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: 545000,
    propertyTaxRate: 0,
    capitalGainsTax: 0,
    rentalIncomeTax: 0,
    transactionCostBuyer: 8,
    transactionCostSeller: 2,
    annualTransactions: 180000,
    avgDaysOnMarket: 45,
    newSupplyPipeline: "high",
    safetyIndex: 86,
    qualityOfLifeIndex: 74,
    lastUpdated: "2025-Q1",
  },
  {
    id: "abu-dhabi",
    name: "Abu Dhabi",
    country: "United Arab Emirates",
    countryCode: "AE",
    region: "Middle East",
    avgPricePerSqft: 320,
    avgPricePerSqm: 3444,
    avgApartmentPrice: 400000,
    priceChangeYoY: 10,
    priceChange5Y: 30,
    avgRentalYield: 6.5,
    avgMonthlyRent1BR: 1500,
    avgMonthlyRent2BR: 2500,
    rentChangeYoY: 8,
    priceToIncomeRatio: 6.0,
    mortgageRate: 4.75,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: 545000,
    propertyTaxRate: 0,
    capitalGainsTax: 0,
    rentalIncomeTax: 0,
    transactionCostBuyer: 6,
    transactionCostSeller: 2,
    annualTransactions: 30000,
    avgDaysOnMarket: 60,
    newSupplyPipeline: "high",
    safetyIndex: 88,
    qualityOfLifeIndex: 73,
    lastUpdated: "2025-Q1",
  },
  {
    id: "riyadh",
    name: "Riyadh",
    country: "Saudi Arabia",
    countryCode: "SA",
    region: "Middle East",
    avgPricePerSqft: 210,
    avgPricePerSqm: 2260,
    avgApartmentPrice: 280000,
    priceChangeYoY: 12,
    priceChange5Y: 35,
    avgRentalYield: 5.5,
    avgMonthlyRent1BR: 1000,
    avgMonthlyRent2BR: 1700,
    rentChangeYoY: 10,
    priceToIncomeRatio: 8.0,
    mortgageRate: 5.5,
    maxLTV: 90,
    foreignOwnershipAllowed: "limited",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0,
    capitalGainsTax: 0,
    rentalIncomeTax: 0,
    transactionCostBuyer: 5,
    transactionCostSeller: 2.5,
    annualTransactions: 50000,
    avgDaysOnMarket: 70,
    newSupplyPipeline: "high",
    safetyIndex: 72,
    qualityOfLifeIndex: 58,
    lastUpdated: "2025-Q1",
  },
  {
    id: "doha",
    name: "Doha",
    country: "Qatar",
    countryCode: "QA",
    region: "Middle East",
    avgPricePerSqft: 250,
    avgPricePerSqm: 2690,
    avgApartmentPrice: 350000,
    priceChangeYoY: -5,
    priceChange5Y: -10,
    avgRentalYield: 5.0,
    avgMonthlyRent1BR: 1300,
    avgMonthlyRent2BR: 2200,
    rentChangeYoY: -3,
    priceToIncomeRatio: 5.5,
    mortgageRate: 5.0,
    maxLTV: 70,
    foreignOwnershipAllowed: "limited",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0,
    capitalGainsTax: 0,
    rentalIncomeTax: 0,
    transactionCostBuyer: 3.5,
    transactionCostSeller: 0,
    annualTransactions: 8000,
    avgDaysOnMarket: 90,
    newSupplyPipeline: "high",
    safetyIndex: 85,
    qualityOfLifeIndex: 68,
    lastUpdated: "2025-Q1",
  },
  {
    id: "muscat",
    name: "Muscat",
    country: "Oman",
    countryCode: "OM",
    region: "Middle East",
    avgPricePerSqft: 130,
    avgPricePerSqm: 1400,
    avgApartmentPrice: 180000,
    priceChangeYoY: 3,
    priceChange5Y: 5,
    avgRentalYield: 5.5,
    avgMonthlyRent1BR: 650,
    avgMonthlyRent2BR: 1100,
    rentChangeYoY: 2,
    priceToIncomeRatio: 7.0,
    mortgageRate: 5.5,
    maxLTV: 80,
    foreignOwnershipAllowed: "limited",
    freeholdAvailable: true,
    goldenVisaThreshold: 250000,
    propertyTaxRate: 0,
    capitalGainsTax: 0,
    rentalIncomeTax: 0,
    transactionCostBuyer: 5,
    transactionCostSeller: 3,
    annualTransactions: 5000,
    avgDaysOnMarket: 100,
    newSupplyPipeline: "medium",
    safetyIndex: 80,
    qualityOfLifeIndex: 60,
    lastUpdated: "2025-Q1",
  },

  // ===========================================================================
  // EUROPE
  // ===========================================================================
  {
    id: "london",
    name: "London",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    avgPricePerSqft: 950,
    avgPricePerSqm: 10226,
    avgApartmentPrice: 750000,
    priceChangeYoY: -2,
    priceChange5Y: 5,
    avgRentalYield: 4.0,
    avgMonthlyRent1BR: 2400,
    avgMonthlyRent2BR: 3600,
    rentChangeYoY: 8,
    priceToIncomeRatio: 14.5,
    mortgageRate: 4.5,
    maxLTV: 75,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.5,
    capitalGainsTax: 28,
    rentalIncomeTax: 45,
    transactionCostBuyer: 6,
    transactionCostSeller: 1.5,
    annualTransactions: 100000,
    avgDaysOnMarket: 55,
    newSupplyPipeline: "medium",
    safetyIndex: 55,
    qualityOfLifeIndex: 70,
    lastUpdated: "2025-Q1",
  },
  {
    id: "paris",
    name: "Paris",
    country: "France",
    countryCode: "FR",
    region: "Europe",
    avgPricePerSqft: 1050,
    avgPricePerSqm: 11302,
    avgApartmentPrice: 680000,
    priceChangeYoY: -4,
    priceChange5Y: -5,
    avgRentalYield: 3.2,
    avgMonthlyRent1BR: 1500,
    avgMonthlyRent2BR: 2500,
    rentChangeYoY: 3,
    priceToIncomeRatio: 18.0,
    mortgageRate: 3.8,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.6,
    capitalGainsTax: 36,
    rentalIncomeTax: 45,
    transactionCostBuyer: 8,
    transactionCostSeller: 0,
    annualTransactions: 45000,
    avgDaysOnMarket: 60,
    newSupplyPipeline: "low",
    safetyIndex: 48,
    qualityOfLifeIndex: 72,
    lastUpdated: "2025-Q1",
  },
  {
    id: "berlin",
    name: "Berlin",
    country: "Germany",
    countryCode: "DE",
    region: "Europe",
    avgPricePerSqft: 480,
    avgPricePerSqm: 5167,
    avgApartmentPrice: 380000,
    priceChangeYoY: -3,
    priceChange5Y: 15,
    avgRentalYield: 3.5,
    avgMonthlyRent1BR: 1100,
    avgMonthlyRent2BR: 1700,
    rentChangeYoY: 5,
    priceToIncomeRatio: 10.0,
    mortgageRate: 3.8,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.4,
    capitalGainsTax: 0,
    rentalIncomeTax: 45,
    transactionCostBuyer: 10,
    transactionCostSeller: 3.5,
    annualTransactions: 25000,
    avgDaysOnMarket: 65,
    newSupplyPipeline: "low",
    safetyIndex: 55,
    qualityOfLifeIndex: 72,
    lastUpdated: "2025-Q1",
  },
  {
    id: "munich",
    name: "Munich",
    country: "Germany",
    countryCode: "DE",
    region: "Europe",
    avgPricePerSqft: 750,
    avgPricePerSqm: 8073,
    avgApartmentPrice: 600000,
    priceChangeYoY: -5,
    priceChange5Y: 10,
    avgRentalYield: 3.0,
    avgMonthlyRent1BR: 1400,
    avgMonthlyRent2BR: 2100,
    rentChangeYoY: 6,
    priceToIncomeRatio: 13.0,
    mortgageRate: 3.8,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.4,
    capitalGainsTax: 0,
    rentalIncomeTax: 45,
    transactionCostBuyer: 10,
    transactionCostSeller: 3.5,
    annualTransactions: 15000,
    avgDaysOnMarket: 50,
    newSupplyPipeline: "low",
    safetyIndex: 78,
    qualityOfLifeIndex: 82,
    lastUpdated: "2025-Q1",
  },
  {
    id: "madrid",
    name: "Madrid",
    country: "Spain",
    countryCode: "ES",
    region: "Europe",
    avgPricePerSqft: 400,
    avgPricePerSqm: 4306,
    avgApartmentPrice: 350000,
    priceChangeYoY: 8,
    priceChange5Y: 25,
    avgRentalYield: 4.8,
    avgMonthlyRent1BR: 1100,
    avgMonthlyRent2BR: 1700,
    rentChangeYoY: 10,
    priceToIncomeRatio: 9.0,
    mortgageRate: 3.5,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.5,
    capitalGainsTax: 23,
    rentalIncomeTax: 24,
    transactionCostBuyer: 12,
    transactionCostSeller: 3,
    annualTransactions: 60000,
    avgDaysOnMarket: 55,
    newSupplyPipeline: "medium",
    safetyIndex: 65,
    qualityOfLifeIndex: 74,
    lastUpdated: "2025-Q1",
  },
  {
    id: "barcelona",
    name: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    region: "Europe",
    avgPricePerSqft: 420,
    avgPricePerSqm: 4521,
    avgApartmentPrice: 370000,
    priceChangeYoY: 9,
    priceChange5Y: 30,
    avgRentalYield: 4.5,
    avgMonthlyRent1BR: 1200,
    avgMonthlyRent2BR: 1800,
    rentChangeYoY: 12,
    priceToIncomeRatio: 11.0,
    mortgageRate: 3.5,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.5,
    capitalGainsTax: 23,
    rentalIncomeTax: 24,
    transactionCostBuyer: 12,
    transactionCostSeller: 3,
    annualTransactions: 40000,
    avgDaysOnMarket: 50,
    newSupplyPipeline: "low",
    safetyIndex: 52,
    qualityOfLifeIndex: 73,
    lastUpdated: "2025-Q1",
  },
  {
    id: "amsterdam",
    name: "Amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    region: "Europe",
    avgPricePerSqft: 650,
    avgPricePerSqm: 6996,
    avgApartmentPrice: 500000,
    priceChangeYoY: 5,
    priceChange5Y: 20,
    avgRentalYield: 3.5,
    avgMonthlyRent1BR: 1800,
    avgMonthlyRent2BR: 2600,
    rentChangeYoY: 5,
    priceToIncomeRatio: 12.0,
    mortgageRate: 4.0,
    maxLTV: 100,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.3,
    capitalGainsTax: 31,
    rentalIncomeTax: 36,
    transactionCostBuyer: 6,
    transactionCostSeller: 2,
    annualTransactions: 20000,
    avgDaysOnMarket: 30,
    newSupplyPipeline: "low",
    safetyIndex: 62,
    qualityOfLifeIndex: 78,
    lastUpdated: "2025-Q1",
  },
  {
    id: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    countryCode: "PT",
    region: "Europe",
    avgPricePerSqft: 450,
    avgPricePerSqm: 4844,
    avgApartmentPrice: 380000,
    priceChangeYoY: 6,
    priceChange5Y: 40,
    avgRentalYield: 4.5,
    avgMonthlyRent1BR: 1200,
    avgMonthlyRent2BR: 1800,
    rentChangeYoY: 8,
    priceToIncomeRatio: 15.0,
    mortgageRate: 3.8,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: 500000,
    propertyTaxRate: 0.4,
    capitalGainsTax: 28,
    rentalIncomeTax: 28,
    transactionCostBuyer: 8,
    transactionCostSeller: 5,
    annualTransactions: 25000,
    avgDaysOnMarket: 55,
    newSupplyPipeline: "medium",
    safetyIndex: 72,
    qualityOfLifeIndex: 70,
    lastUpdated: "2025-Q1",
  },
  {
    id: "istanbul",
    name: "Istanbul",
    country: "Turkey",
    countryCode: "TR",
    region: "Europe",
    avgPricePerSqft: 150,
    avgPricePerSqm: 1615,
    avgApartmentPrice: 150000,
    priceChangeYoY: 30,
    priceChange5Y: 200,
    avgRentalYield: 5.5,
    avgMonthlyRent1BR: 500,
    avgMonthlyRent2BR: 800,
    rentChangeYoY: 80,
    priceToIncomeRatio: 11.0,
    mortgageRate: 40.0,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: 400000,
    propertyTaxRate: 0.2,
    capitalGainsTax: 0,
    rentalIncomeTax: 35,
    transactionCostBuyer: 4,
    transactionCostSeller: 2,
    annualTransactions: 150000,
    avgDaysOnMarket: 45,
    newSupplyPipeline: "high",
    safetyIndex: 50,
    qualityOfLifeIndex: 48,
    lastUpdated: "2025-Q1",
  },
  {
    id: "athens",
    name: "Athens",
    country: "Greece",
    countryCode: "GR",
    region: "Europe",
    avgPricePerSqft: 230,
    avgPricePerSqm: 2476,
    avgApartmentPrice: 200000,
    priceChangeYoY: 10,
    priceChange5Y: 50,
    avgRentalYield: 5.5,
    avgMonthlyRent1BR: 700,
    avgMonthlyRent2BR: 1100,
    rentChangeYoY: 12,
    priceToIncomeRatio: 9.0,
    mortgageRate: 4.2,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: 250000,
    propertyTaxRate: 0.3,
    capitalGainsTax: 0,
    rentalIncomeTax: 15,
    transactionCostBuyer: 8,
    transactionCostSeller: 0,
    annualTransactions: 20000,
    avgDaysOnMarket: 75,
    newSupplyPipeline: "low",
    safetyIndex: 56,
    qualityOfLifeIndex: 58,
    lastUpdated: "2025-Q1",
  },
  {
    id: "milan",
    name: "Milan",
    country: "Italy",
    countryCode: "IT",
    region: "Europe",
    avgPricePerSqft: 500,
    avgPricePerSqm: 5382,
    avgApartmentPrice: 420000,
    priceChangeYoY: 5,
    priceChange5Y: 20,
    avgRentalYield: 4.2,
    avgMonthlyRent1BR: 1300,
    avgMonthlyRent2BR: 2000,
    rentChangeYoY: 7,
    priceToIncomeRatio: 12.0,
    mortgageRate: 3.8,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: 250000,
    propertyTaxRate: 0.5,
    capitalGainsTax: 26,
    rentalIncomeTax: 21,
    transactionCostBuyer: 10,
    transactionCostSeller: 0,
    annualTransactions: 30000,
    avgDaysOnMarket: 60,
    newSupplyPipeline: "medium",
    safetyIndex: 52,
    qualityOfLifeIndex: 65,
    lastUpdated: "2025-Q1",
  },
  {
    id: "rome",
    name: "Rome",
    country: "Italy",
    countryCode: "IT",
    region: "Europe",
    avgPricePerSqft: 380,
    avgPricePerSqm: 4090,
    avgApartmentPrice: 320000,
    priceChangeYoY: 2,
    priceChange5Y: 5,
    avgRentalYield: 4.5,
    avgMonthlyRent1BR: 1000,
    avgMonthlyRent2BR: 1600,
    rentChangeYoY: 5,
    priceToIncomeRatio: 11.0,
    mortgageRate: 3.8,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: 250000,
    propertyTaxRate: 0.5,
    capitalGainsTax: 26,
    rentalIncomeTax: 21,
    transactionCostBuyer: 10,
    transactionCostSeller: 0,
    annualTransactions: 25000,
    avgDaysOnMarket: 80,
    newSupplyPipeline: "low",
    safetyIndex: 48,
    qualityOfLifeIndex: 62,
    lastUpdated: "2025-Q1",
  },
  {
    id: "zurich",
    name: "Zurich",
    country: "Switzerland",
    countryCode: "CH",
    region: "Europe",
    avgPricePerSqft: 1200,
    avgPricePerSqm: 12917,
    avgApartmentPrice: 950000,
    priceChangeYoY: 3,
    priceChange5Y: 15,
    avgRentalYield: 2.5,
    avgMonthlyRent1BR: 2500,
    avgMonthlyRent2BR: 3800,
    rentChangeYoY: 3,
    priceToIncomeRatio: 10.0,
    mortgageRate: 2.5,
    maxLTV: 80,
    foreignOwnershipAllowed: "limited",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.2,
    capitalGainsTax: 0,
    rentalIncomeTax: 35,
    transactionCostBuyer: 5,
    transactionCostSeller: 2,
    annualTransactions: 10000,
    avgDaysOnMarket: 40,
    newSupplyPipeline: "low",
    safetyIndex: 82,
    qualityOfLifeIndex: 90,
    lastUpdated: "2025-Q1",
  },
  {
    id: "vienna",
    name: "Vienna",
    country: "Austria",
    countryCode: "AT",
    region: "Europe",
    avgPricePerSqft: 520,
    avgPricePerSqm: 5597,
    avgApartmentPrice: 400000,
    priceChangeYoY: -2,
    priceChange5Y: 15,
    avgRentalYield: 3.5,
    avgMonthlyRent1BR: 1000,
    avgMonthlyRent2BR: 1600,
    rentChangeYoY: 4,
    priceToIncomeRatio: 10.0,
    mortgageRate: 3.8,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.2,
    capitalGainsTax: 30,
    rentalIncomeTax: 50,
    transactionCostBuyer: 7,
    transactionCostSeller: 3.5,
    annualTransactions: 15000,
    avgDaysOnMarket: 55,
    newSupplyPipeline: "medium",
    safetyIndex: 80,
    qualityOfLifeIndex: 86,
    lastUpdated: "2025-Q1",
  },
  {
    id: "prague",
    name: "Prague",
    country: "Czech Republic",
    countryCode: "CZ",
    region: "Europe",
    avgPricePerSqft: 400,
    avgPricePerSqm: 4306,
    avgApartmentPrice: 320000,
    priceChangeYoY: 8,
    priceChange5Y: 45,
    avgRentalYield: 4.0,
    avgMonthlyRent1BR: 900,
    avgMonthlyRent2BR: 1400,
    rentChangeYoY: 6,
    priceToIncomeRatio: 13.0,
    mortgageRate: 5.0,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.1,
    capitalGainsTax: 0,
    rentalIncomeTax: 15,
    transactionCostBuyer: 4,
    transactionCostSeller: 0,
    annualTransactions: 20000,
    avgDaysOnMarket: 40,
    newSupplyPipeline: "medium",
    safetyIndex: 75,
    qualityOfLifeIndex: 72,
    lastUpdated: "2025-Q1",
  },
  {
    id: "warsaw",
    name: "Warsaw",
    country: "Poland",
    countryCode: "PL",
    region: "Europe",
    avgPricePerSqft: 310,
    avgPricePerSqm: 3337,
    avgApartmentPrice: 250000,
    priceChangeYoY: 10,
    priceChange5Y: 50,
    avgRentalYield: 4.5,
    avgMonthlyRent1BR: 750,
    avgMonthlyRent2BR: 1200,
    rentChangeYoY: 8,
    priceToIncomeRatio: 9.0,
    mortgageRate: 7.5,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.1,
    capitalGainsTax: 19,
    rentalIncomeTax: 8.5,
    transactionCostBuyer: 4,
    transactionCostSeller: 0,
    annualTransactions: 30000,
    avgDaysOnMarket: 45,
    newSupplyPipeline: "medium",
    safetyIndex: 70,
    qualityOfLifeIndex: 62,
    lastUpdated: "2025-Q1",
  },
  {
    id: "budapest",
    name: "Budapest",
    country: "Hungary",
    countryCode: "HU",
    region: "Europe",
    avgPricePerSqft: 250,
    avgPricePerSqm: 2690,
    avgApartmentPrice: 200000,
    priceChangeYoY: 12,
    priceChange5Y: 55,
    avgRentalYield: 5.5,
    avgMonthlyRent1BR: 650,
    avgMonthlyRent2BR: 1000,
    rentChangeYoY: 10,
    priceToIncomeRatio: 9.5,
    mortgageRate: 6.5,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: 250000,
    propertyTaxRate: 0.2,
    capitalGainsTax: 15,
    rentalIncomeTax: 15,
    transactionCostBuyer: 6,
    transactionCostSeller: 0,
    annualTransactions: 18000,
    avgDaysOnMarket: 50,
    newSupplyPipeline: "medium",
    safetyIndex: 68,
    qualityOfLifeIndex: 60,
    lastUpdated: "2025-Q1",
  },
  {
    id: "dublin",
    name: "Dublin",
    country: "Ireland",
    countryCode: "IE",
    region: "Europe",
    avgPricePerSqft: 520,
    avgPricePerSqm: 5597,
    avgApartmentPrice: 420000,
    priceChangeYoY: 6,
    priceChange5Y: 25,
    avgRentalYield: 4.0,
    avgMonthlyRent1BR: 2000,
    avgMonthlyRent2BR: 3000,
    rentChangeYoY: 5,
    priceToIncomeRatio: 10.5,
    mortgageRate: 4.0,
    maxLTV: 90,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.2,
    capitalGainsTax: 33,
    rentalIncomeTax: 52,
    transactionCostBuyer: 3,
    transactionCostSeller: 1,
    annualTransactions: 20000,
    avgDaysOnMarket: 30,
    newSupplyPipeline: "medium",
    safetyIndex: 60,
    qualityOfLifeIndex: 72,
    lastUpdated: "2025-Q1",
  },

  // ===========================================================================
  // AMERICAS
  // ===========================================================================
  {
    id: "new-york",
    name: "New York",
    country: "United States",
    countryCode: "US",
    region: "Americas",
    avgPricePerSqft: 1100,
    avgPricePerSqm: 11840,
    avgApartmentPrice: 900000,
    priceChangeYoY: 3,
    priceChange5Y: 10,
    avgRentalYield: 3.5,
    avgMonthlyRent1BR: 3800,
    avgMonthlyRent2BR: 5500,
    rentChangeYoY: 4,
    priceToIncomeRatio: 12.0,
    mortgageRate: 7.0,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 1.2,
    capitalGainsTax: 20,
    rentalIncomeTax: 37,
    transactionCostBuyer: 4,
    transactionCostSeller: 6,
    annualTransactions: 50000,
    avgDaysOnMarket: 55,
    newSupplyPipeline: "medium",
    safetyIndex: 45,
    qualityOfLifeIndex: 65,
    lastUpdated: "2025-Q1",
  },
  {
    id: "miami",
    name: "Miami",
    country: "United States",
    countryCode: "US",
    region: "Americas",
    avgPricePerSqft: 550,
    avgPricePerSqm: 5920,
    avgApartmentPrice: 500000,
    priceChangeYoY: 8,
    priceChange5Y: 55,
    avgRentalYield: 5.5,
    avgMonthlyRent1BR: 2800,
    avgMonthlyRent2BR: 4000,
    rentChangeYoY: 5,
    priceToIncomeRatio: 9.0,
    mortgageRate: 7.0,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 1.0,
    capitalGainsTax: 20,
    rentalIncomeTax: 37,
    transactionCostBuyer: 3,
    transactionCostSeller: 6,
    annualTransactions: 40000,
    avgDaysOnMarket: 45,
    newSupplyPipeline: "high",
    safetyIndex: 42,
    qualityOfLifeIndex: 62,
    lastUpdated: "2025-Q1",
  },
  {
    id: "los-angeles",
    name: "Los Angeles",
    country: "United States",
    countryCode: "US",
    region: "Americas",
    avgPricePerSqft: 650,
    avgPricePerSqm: 6996,
    avgApartmentPrice: 600000,
    priceChangeYoY: 5,
    priceChange5Y: 30,
    avgRentalYield: 4.0,
    avgMonthlyRent1BR: 2500,
    avgMonthlyRent2BR: 3500,
    rentChangeYoY: 3,
    priceToIncomeRatio: 11.0,
    mortgageRate: 7.0,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.75,
    capitalGainsTax: 20,
    rentalIncomeTax: 37,
    transactionCostBuyer: 3,
    transactionCostSeller: 6,
    annualTransactions: 55000,
    avgDaysOnMarket: 40,
    newSupplyPipeline: "low",
    safetyIndex: 40,
    qualityOfLifeIndex: 63,
    lastUpdated: "2025-Q1",
  },
  {
    id: "san-francisco",
    name: "San Francisco",
    country: "United States",
    countryCode: "US",
    region: "Americas",
    avgPricePerSqft: 950,
    avgPricePerSqm: 10226,
    avgApartmentPrice: 800000,
    priceChangeYoY: -2,
    priceChange5Y: 5,
    avgRentalYield: 3.5,
    avgMonthlyRent1BR: 3200,
    avgMonthlyRent2BR: 4500,
    rentChangeYoY: 2,
    priceToIncomeRatio: 10.5,
    mortgageRate: 7.0,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 1.2,
    capitalGainsTax: 20,
    rentalIncomeTax: 37,
    transactionCostBuyer: 3,
    transactionCostSeller: 6,
    annualTransactions: 15000,
    avgDaysOnMarket: 35,
    newSupplyPipeline: "low",
    safetyIndex: 38,
    qualityOfLifeIndex: 65,
    lastUpdated: "2025-Q1",
  },
  {
    id: "toronto",
    name: "Toronto",
    country: "Canada",
    countryCode: "CA",
    region: "Americas",
    avgPricePerSqft: 750,
    avgPricePerSqm: 8073,
    avgApartmentPrice: 550000,
    priceChangeYoY: -5,
    priceChange5Y: 15,
    avgRentalYield: 4.0,
    avgMonthlyRent1BR: 2200,
    avgMonthlyRent2BR: 3000,
    rentChangeYoY: 5,
    priceToIncomeRatio: 12.0,
    mortgageRate: 5.5,
    maxLTV: 80,
    foreignOwnershipAllowed: "limited",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.65,
    capitalGainsTax: 25,
    rentalIncomeTax: 50,
    transactionCostBuyer: 4,
    transactionCostSeller: 5,
    annualTransactions: 65000,
    avgDaysOnMarket: 20,
    newSupplyPipeline: "high",
    safetyIndex: 60,
    qualityOfLifeIndex: 75,
    lastUpdated: "2025-Q1",
  },
  {
    id: "vancouver",
    name: "Vancouver",
    country: "Canada",
    countryCode: "CA",
    region: "Americas",
    avgPricePerSqft: 800,
    avgPricePerSqm: 8611,
    avgApartmentPrice: 580000,
    priceChangeYoY: -3,
    priceChange5Y: 10,
    avgRentalYield: 3.5,
    avgMonthlyRent1BR: 2100,
    avgMonthlyRent2BR: 3000,
    rentChangeYoY: 4,
    priceToIncomeRatio: 13.0,
    mortgageRate: 5.5,
    maxLTV: 80,
    foreignOwnershipAllowed: "limited",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.3,
    capitalGainsTax: 25,
    rentalIncomeTax: 50,
    transactionCostBuyer: 4,
    transactionCostSeller: 5,
    annualTransactions: 25000,
    avgDaysOnMarket: 25,
    newSupplyPipeline: "medium",
    safetyIndex: 62,
    qualityOfLifeIndex: 78,
    lastUpdated: "2025-Q1",
  },
  {
    id: "sao-paulo",
    name: "Sao Paulo",
    country: "Brazil",
    countryCode: "BR",
    region: "Americas",
    avgPricePerSqft: 180,
    avgPricePerSqm: 1938,
    avgApartmentPrice: 200000,
    priceChangeYoY: 5,
    priceChange5Y: 20,
    avgRentalYield: 5.5,
    avgMonthlyRent1BR: 600,
    avgMonthlyRent2BR: 1000,
    rentChangeYoY: 8,
    priceToIncomeRatio: 10.0,
    mortgageRate: 10.0,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 1.0,
    capitalGainsTax: 15,
    rentalIncomeTax: 27.5,
    transactionCostBuyer: 4,
    transactionCostSeller: 6,
    annualTransactions: 80000,
    avgDaysOnMarket: 90,
    newSupplyPipeline: "high",
    safetyIndex: 30,
    qualityOfLifeIndex: 42,
    lastUpdated: "2025-Q1",
  },
  {
    id: "mexico-city",
    name: "Mexico City",
    country: "Mexico",
    countryCode: "MX",
    region: "Americas",
    avgPricePerSqft: 200,
    avgPricePerSqm: 2153,
    avgApartmentPrice: 200000,
    priceChangeYoY: 8,
    priceChange5Y: 35,
    avgRentalYield: 6.0,
    avgMonthlyRent1BR: 700,
    avgMonthlyRent2BR: 1200,
    rentChangeYoY: 10,
    priceToIncomeRatio: 9.0,
    mortgageRate: 11.0,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.1,
    capitalGainsTax: 35,
    rentalIncomeTax: 35,
    transactionCostBuyer: 5,
    transactionCostSeller: 5,
    annualTransactions: 60000,
    avgDaysOnMarket: 80,
    newSupplyPipeline: "medium",
    safetyIndex: 35,
    qualityOfLifeIndex: 45,
    lastUpdated: "2025-Q1",
  },

  // ===========================================================================
  // ASIA
  // ===========================================================================
  {
    id: "singapore",
    name: "Singapore",
    country: "Singapore",
    countryCode: "SG",
    region: "Asia",
    avgPricePerSqft: 1800,
    avgPricePerSqm: 19375,
    avgApartmentPrice: 1200000,
    priceChangeYoY: 6,
    priceChange5Y: 30,
    avgRentalYield: 3.5,
    avgMonthlyRent1BR: 2800,
    avgMonthlyRent2BR: 4200,
    rentChangeYoY: 5,
    priceToIncomeRatio: 15.0,
    mortgageRate: 3.5,
    maxLTV: 75,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: 2500000,
    propertyTaxRate: 0.5,
    capitalGainsTax: 0,
    rentalIncomeTax: 22,
    transactionCostBuyer: 4,
    transactionCostSeller: 3,
    annualTransactions: 25000,
    avgDaysOnMarket: 30,
    newSupplyPipeline: "medium",
    safetyIndex: 90,
    qualityOfLifeIndex: 82,
    lastUpdated: "2025-Q1",
  },
  {
    id: "hong-kong",
    name: "Hong Kong",
    country: "Hong Kong SAR",
    countryCode: "HK",
    region: "Asia",
    avgPricePerSqft: 2000,
    avgPricePerSqm: 21528,
    avgApartmentPrice: 1100000,
    priceChangeYoY: -10,
    priceChange5Y: -25,
    avgRentalYield: 3.0,
    avgMonthlyRent1BR: 2500,
    avgMonthlyRent2BR: 4000,
    rentChangeYoY: -5,
    priceToIncomeRatio: 20.0,
    mortgageRate: 4.0,
    maxLTV: 60,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: false,
    goldenVisaThreshold: 3800000,
    propertyTaxRate: 0.1,
    capitalGainsTax: 0,
    rentalIncomeTax: 15,
    transactionCostBuyer: 4.5,
    transactionCostSeller: 1,
    annualTransactions: 45000,
    avgDaysOnMarket: 60,
    newSupplyPipeline: "medium",
    safetyIndex: 80,
    qualityOfLifeIndex: 70,
    lastUpdated: "2025-Q1",
  },
  {
    id: "tokyo",
    name: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    region: "Asia",
    avgPricePerSqft: 800,
    avgPricePerSqm: 8611,
    avgApartmentPrice: 550000,
    priceChangeYoY: 10,
    priceChange5Y: 35,
    avgRentalYield: 3.5,
    avgMonthlyRent1BR: 1200,
    avgMonthlyRent2BR: 2000,
    rentChangeYoY: 5,
    priceToIncomeRatio: 13.0,
    mortgageRate: 1.5,
    maxLTV: 100,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 1.0,
    capitalGainsTax: 20,
    rentalIncomeTax: 45,
    transactionCostBuyer: 7,
    transactionCostSeller: 4,
    annualTransactions: 50000,
    avgDaysOnMarket: 45,
    newSupplyPipeline: "medium",
    safetyIndex: 88,
    qualityOfLifeIndex: 78,
    lastUpdated: "2025-Q1",
  },
  {
    id: "shanghai",
    name: "Shanghai",
    country: "China",
    countryCode: "CN",
    region: "Asia",
    avgPricePerSqft: 750,
    avgPricePerSqm: 8073,
    avgApartmentPrice: 600000,
    priceChangeYoY: -8,
    priceChange5Y: -15,
    avgRentalYield: 1.8,
    avgMonthlyRent1BR: 1000,
    avgMonthlyRent2BR: 1600,
    rentChangeYoY: -3,
    priceToIncomeRatio: 25.0,
    mortgageRate: 3.5,
    maxLTV: 65,
    foreignOwnershipAllowed: "limited",
    freeholdAvailable: false,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.6,
    capitalGainsTax: 20,
    rentalIncomeTax: 20,
    transactionCostBuyer: 4,
    transactionCostSeller: 5.5,
    annualTransactions: 200000,
    avgDaysOnMarket: 90,
    newSupplyPipeline: "high",
    safetyIndex: 72,
    qualityOfLifeIndex: 55,
    lastUpdated: "2025-Q1",
  },
  {
    id: "beijing",
    name: "Beijing",
    country: "China",
    countryCode: "CN",
    region: "Asia",
    avgPricePerSqft: 700,
    avgPricePerSqm: 7535,
    avgApartmentPrice: 550000,
    priceChangeYoY: -10,
    priceChange5Y: -20,
    avgRentalYield: 1.5,
    avgMonthlyRent1BR: 900,
    avgMonthlyRent2BR: 1400,
    rentChangeYoY: -4,
    priceToIncomeRatio: 28.0,
    mortgageRate: 3.5,
    maxLTV: 65,
    foreignOwnershipAllowed: "limited",
    freeholdAvailable: false,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.6,
    capitalGainsTax: 20,
    rentalIncomeTax: 20,
    transactionCostBuyer: 4,
    transactionCostSeller: 5.5,
    annualTransactions: 150000,
    avgDaysOnMarket: 100,
    newSupplyPipeline: "medium",
    safetyIndex: 70,
    qualityOfLifeIndex: 50,
    lastUpdated: "2025-Q1",
  },
  {
    id: "mumbai",
    name: "Mumbai",
    country: "India",
    countryCode: "IN",
    region: "Asia",
    avgPricePerSqft: 350,
    avgPricePerSqm: 3767,
    avgApartmentPrice: 300000,
    priceChangeYoY: 7,
    priceChange5Y: 20,
    avgRentalYield: 3.0,
    avgMonthlyRent1BR: 600,
    avgMonthlyRent2BR: 1000,
    rentChangeYoY: 8,
    priceToIncomeRatio: 25.0,
    mortgageRate: 8.5,
    maxLTV: 80,
    foreignOwnershipAllowed: "limited",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.5,
    capitalGainsTax: 12.5,
    rentalIncomeTax: 30,
    transactionCostBuyer: 7,
    transactionCostSeller: 1,
    annualTransactions: 60000,
    avgDaysOnMarket: 120,
    newSupplyPipeline: "high",
    safetyIndex: 42,
    qualityOfLifeIndex: 35,
    lastUpdated: "2025-Q1",
  },
  {
    id: "bangkok",
    name: "Bangkok",
    country: "Thailand",
    countryCode: "TH",
    region: "Asia",
    avgPricePerSqft: 250,
    avgPricePerSqm: 2690,
    avgApartmentPrice: 200000,
    priceChangeYoY: 3,
    priceChange5Y: 10,
    avgRentalYield: 5.0,
    avgMonthlyRent1BR: 650,
    avgMonthlyRent2BR: 1100,
    rentChangeYoY: 3,
    priceToIncomeRatio: 12.0,
    mortgageRate: 6.0,
    maxLTV: 80,
    foreignOwnershipAllowed: "limited",
    freeholdAvailable: false,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.05,
    capitalGainsTax: 0,
    rentalIncomeTax: 35,
    transactionCostBuyer: 3,
    transactionCostSeller: 3.3,
    annualTransactions: 40000,
    avgDaysOnMarket: 90,
    newSupplyPipeline: "high",
    safetyIndex: 48,
    qualityOfLifeIndex: 50,
    lastUpdated: "2025-Q1",
  },
  {
    id: "kuala-lumpur",
    name: "Kuala Lumpur",
    country: "Malaysia",
    countryCode: "MY",
    region: "Asia",
    avgPricePerSqft: 150,
    avgPricePerSqm: 1615,
    avgApartmentPrice: 150000,
    priceChangeYoY: 2,
    priceChange5Y: 5,
    avgRentalYield: 4.5,
    avgMonthlyRent1BR: 500,
    avgMonthlyRent2BR: 800,
    rentChangeYoY: 3,
    priceToIncomeRatio: 8.0,
    mortgageRate: 4.0,
    maxLTV: 70,
    foreignOwnershipAllowed: "limited",
    freeholdAvailable: true,
    goldenVisaThreshold: 240000,
    propertyTaxRate: 0.1,
    capitalGainsTax: 10,
    rentalIncomeTax: 26,
    transactionCostBuyer: 4,
    transactionCostSeller: 3,
    annualTransactions: 30000,
    avgDaysOnMarket: 100,
    newSupplyPipeline: "high",
    safetyIndex: 55,
    qualityOfLifeIndex: 52,
    lastUpdated: "2025-Q1",
  },
  {
    id: "seoul",
    name: "Seoul",
    country: "South Korea",
    countryCode: "KR",
    region: "Asia",
    avgPricePerSqft: 900,
    avgPricePerSqm: 9688,
    avgApartmentPrice: 700000,
    priceChangeYoY: -5,
    priceChange5Y: 30,
    avgRentalYield: 2.5,
    avgMonthlyRent1BR: 800,
    avgMonthlyRent2BR: 1400,
    rentChangeYoY: 3,
    priceToIncomeRatio: 18.0,
    mortgageRate: 4.5,
    maxLTV: 50,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: 500000,
    propertyTaxRate: 0.4,
    capitalGainsTax: 45,
    rentalIncomeTax: 42,
    transactionCostBuyer: 5,
    transactionCostSeller: 3,
    annualTransactions: 60000,
    avgDaysOnMarket: 45,
    newSupplyPipeline: "medium",
    safetyIndex: 78,
    qualityOfLifeIndex: 68,
    lastUpdated: "2025-Q1",
  },
  {
    id: "jakarta",
    name: "Jakarta",
    country: "Indonesia",
    countryCode: "ID",
    region: "Asia",
    avgPricePerSqft: 170,
    avgPricePerSqm: 1830,
    avgApartmentPrice: 150000,
    priceChangeYoY: 2,
    priceChange5Y: 5,
    avgRentalYield: 5.0,
    avgMonthlyRent1BR: 500,
    avgMonthlyRent2BR: 850,
    rentChangeYoY: 2,
    priceToIncomeRatio: 10.0,
    mortgageRate: 8.0,
    maxLTV: 80,
    foreignOwnershipAllowed: "limited",
    freeholdAvailable: false,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.2,
    capitalGainsTax: 2.5,
    rentalIncomeTax: 10,
    transactionCostBuyer: 5,
    transactionCostSeller: 2.5,
    annualTransactions: 25000,
    avgDaysOnMarket: 120,
    newSupplyPipeline: "high",
    safetyIndex: 42,
    qualityOfLifeIndex: 38,
    lastUpdated: "2025-Q1",
  },

  // ===========================================================================
  // OCEANIA
  // ===========================================================================
  {
    id: "sydney",
    name: "Sydney",
    country: "Australia",
    countryCode: "AU",
    region: "Oceania",
    avgPricePerSqft: 800,
    avgPricePerSqm: 8611,
    avgApartmentPrice: 650000,
    priceChangeYoY: 5,
    priceChange5Y: 30,
    avgRentalYield: 3.5,
    avgMonthlyRent1BR: 2200,
    avgMonthlyRent2BR: 3200,
    rentChangeYoY: 8,
    priceToIncomeRatio: 13.0,
    mortgageRate: 6.0,
    maxLTV: 80,
    foreignOwnershipAllowed: "limited",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.3,
    capitalGainsTax: 25,
    rentalIncomeTax: 47,
    transactionCostBuyer: 5,
    transactionCostSeller: 2,
    annualTransactions: 60000,
    avgDaysOnMarket: 30,
    newSupplyPipeline: "medium",
    safetyIndex: 62,
    qualityOfLifeIndex: 78,
    lastUpdated: "2025-Q1",
  },
  {
    id: "melbourne",
    name: "Melbourne",
    country: "Australia",
    countryCode: "AU",
    region: "Oceania",
    avgPricePerSqft: 550,
    avgPricePerSqm: 5920,
    avgApartmentPrice: 480000,
    priceChangeYoY: 2,
    priceChange5Y: 15,
    avgRentalYield: 4.0,
    avgMonthlyRent1BR: 1600,
    avgMonthlyRent2BR: 2400,
    rentChangeYoY: 10,
    priceToIncomeRatio: 10.0,
    mortgageRate: 6.0,
    maxLTV: 80,
    foreignOwnershipAllowed: "limited",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.3,
    capitalGainsTax: 25,
    rentalIncomeTax: 47,
    transactionCostBuyer: 6,
    transactionCostSeller: 2,
    annualTransactions: 50000,
    avgDaysOnMarket: 35,
    newSupplyPipeline: "high",
    safetyIndex: 58,
    qualityOfLifeIndex: 80,
    lastUpdated: "2025-Q1",
  },
  {
    id: "auckland",
    name: "Auckland",
    country: "New Zealand",
    countryCode: "NZ",
    region: "Oceania",
    avgPricePerSqft: 500,
    avgPricePerSqm: 5382,
    avgApartmentPrice: 450000,
    priceChangeYoY: -3,
    priceChange5Y: 10,
    avgRentalYield: 3.5,
    avgMonthlyRent1BR: 1300,
    avgMonthlyRent2BR: 2000,
    rentChangeYoY: 5,
    priceToIncomeRatio: 9.0,
    mortgageRate: 6.5,
    maxLTV: 80,
    foreignOwnershipAllowed: "limited",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.3,
    capitalGainsTax: 0,
    rentalIncomeTax: 39,
    transactionCostBuyer: 3,
    transactionCostSeller: 3,
    annualTransactions: 20000,
    avgDaysOnMarket: 40,
    newSupplyPipeline: "medium",
    safetyIndex: 58,
    qualityOfLifeIndex: 76,
    lastUpdated: "2025-Q1",
  },

  // ===========================================================================
  // AFRICA
  // ===========================================================================
  {
    id: "cape-town",
    name: "Cape Town",
    country: "South Africa",
    countryCode: "ZA",
    region: "Africa",
    avgPricePerSqft: 150,
    avgPricePerSqm: 1615,
    avgApartmentPrice: 180000,
    priceChangeYoY: 5,
    priceChange5Y: 20,
    avgRentalYield: 7.0,
    avgMonthlyRent1BR: 600,
    avgMonthlyRent2BR: 1000,
    rentChangeYoY: 8,
    priceToIncomeRatio: 6.0,
    mortgageRate: 11.5,
    maxLTV: 100,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.5,
    capitalGainsTax: 18,
    rentalIncomeTax: 45,
    transactionCostBuyer: 8,
    transactionCostSeller: 6,
    annualTransactions: 15000,
    avgDaysOnMarket: 75,
    newSupplyPipeline: "low",
    safetyIndex: 25,
    qualityOfLifeIndex: 45,
    lastUpdated: "2025-Q1",
  },
  {
    id: "nairobi",
    name: "Nairobi",
    country: "Kenya",
    countryCode: "KE",
    region: "Africa",
    avgPricePerSqft: 100,
    avgPricePerSqm: 1076,
    avgApartmentPrice: 120000,
    priceChangeYoY: 3,
    priceChange5Y: 15,
    avgRentalYield: 6.0,
    avgMonthlyRent1BR: 400,
    avgMonthlyRent2BR: 700,
    rentChangeYoY: 5,
    priceToIncomeRatio: 12.0,
    mortgageRate: 14.0,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.25,
    capitalGainsTax: 15,
    rentalIncomeTax: 10,
    transactionCostBuyer: 6,
    transactionCostSeller: 2,
    annualTransactions: 10000,
    avgDaysOnMarket: 120,
    newSupplyPipeline: "high",
    safetyIndex: 30,
    qualityOfLifeIndex: 32,
    lastUpdated: "2025-Q1",
  },
  {
    id: "cairo",
    name: "Cairo",
    country: "Egypt",
    countryCode: "EG",
    region: "Africa",
    avgPricePerSqft: 60,
    avgPricePerSqm: 646,
    avgApartmentPrice: 60000,
    priceChangeYoY: 40,
    priceChange5Y: 150,
    avgRentalYield: 7.5,
    avgMonthlyRent1BR: 250,
    avgMonthlyRent2BR: 400,
    rentChangeYoY: 30,
    priceToIncomeRatio: 8.0,
    mortgageRate: 20.0,
    maxLTV: 80,
    foreignOwnershipAllowed: "yes",
    freeholdAvailable: true,
    goldenVisaThreshold: null,
    propertyTaxRate: 0.1,
    capitalGainsTax: 0,
    rentalIncomeTax: 22.5,
    transactionCostBuyer: 3,
    transactionCostSeller: 2.5,
    annualTransactions: 50000,
    avgDaysOnMarket: 90,
    newSupplyPipeline: "high",
    safetyIndex: 38,
    qualityOfLifeIndex: 30,
    lastUpdated: "2025-Q1",
  },
];

// ---------------------------------------------------------------------------
// HELPER FUNCTIONS
// ---------------------------------------------------------------------------

/** Get a city by ID */
export function getCityById(id: string): CityData | undefined {
  return CITY_DATA.find((c) => c.id === id);
}

/** Get all cities in a region */
export function getCitiesByRegion(region: Region): CityData[] {
  return CITY_DATA.filter((c) => c.region === region);
}

/** Get cities sorted by a numeric metric (descending) */
export function getCitiesSortedBy(
  metric: keyof CityData,
  ascending = false
): CityData[] {
  return [...CITY_DATA]
    .filter((c) => c[metric] !== null && c[metric] !== undefined)
    .sort((a, b) => {
      const aVal = a[metric] as number;
      const bVal = b[metric] as number;
      return ascending ? aVal - bVal : bVal - aVal;
    });
}

/** Get unique countries from the dataset */
export function getCountries(): string[] {
  return Array.from(new Set(CITY_DATA.map((c) => c.country))).sort();
}

/** Summary stats for a region */
export function getRegionSummary(region: Region) {
  const cities = getCitiesByRegion(region);
  if (cities.length === 0) return null;

  const avg = (vals: (number | null)[]) => {
    const valid = vals.filter((v): v is number => v !== null);
    return valid.length > 0
      ? Math.round((valid.reduce((a, b) => a + b, 0) / valid.length) * 10) / 10
      : null;
  };

  return {
    region,
    cityCount: cities.length,
    avgPricePerSqft: avg(cities.map((c) => c.avgPricePerSqft)),
    avgRentalYield: avg(cities.map((c) => c.avgRentalYield)),
    avgPriceChangeYoY: avg(cities.map((c) => c.priceChangeYoY)),
    avgMortgageRate: avg(cities.map((c) => c.mortgageRate)),
  };
}
