// Regulation Monitor — UAE real estate regulatory updates
// Sources: DLD, RERA, UAE government announcements

export interface Regulation {
  id: string;
  date: string; // YYYY-MM-DD
  title: string;
  category: "rera" | "dld" | "visa" | "tax" | "mortgage" | "rental" | "ownership" | "developer";
  impact: "high" | "medium" | "low";
  status: "active" | "upcoming" | "proposed" | "superseded";
  summary: string;
  details: string[];
  affectedParties: string[];
  source: string;
}

export const CATEGORIES: { value: Regulation["category"]; label: string; color: string }[] = [
  { value: "rera", label: "RERA", color: "text-blue-400 bg-blue-400/10 border-blue-400/20" },
  { value: "dld", label: "DLD", color: "text-purple-400 bg-purple-400/10 border-purple-400/20" },
  { value: "visa", label: "Visa & Residency", color: "text-emerald-400 bg-emerald-400/10 border-emerald-400/20" },
  { value: "tax", label: "Tax & Fees", color: "text-amber-400 bg-amber-400/10 border-amber-400/20" },
  { value: "mortgage", label: "Mortgage & Finance", color: "text-cyan-400 bg-cyan-400/10 border-cyan-400/20" },
  { value: "rental", label: "Rental", color: "text-pink-400 bg-pink-400/10 border-pink-400/20" },
  { value: "ownership", label: "Ownership", color: "text-orange-400 bg-orange-400/10 border-orange-400/20" },
  { value: "developer", label: "Developer Regulations", color: "text-teal-400 bg-teal-400/10 border-teal-400/20" },
];

export const REGULATIONS: Regulation[] = [
  // 2026
  {
    id: "reg-2026-001",
    date: "2026-03-15",
    title: "DLD Digital Title Deeds — Blockchain Integration",
    category: "dld",
    impact: "high",
    status: "active",
    summary: "Dubai Land Department launches blockchain-based digital title deeds, eliminating paper certificates and enabling instant ownership verification.",
    details: [
      "All new transactions issue NFT-based title deeds on Dubai Blockchain",
      "Existing title deeds can be migrated digitally at no extra cost",
      "Enables fractional ownership tokenization framework",
      "Reduces title deed issuance time from 3 days to instant",
    ],
    affectedParties: ["All property owners", "Developers", "Banks", "Brokers"],
    source: "DLD Official Announcement",
  },
  {
    id: "reg-2026-002",
    date: "2026-02-01",
    title: "RERA Rent Index 2026 Update",
    category: "rental",
    impact: "high",
    status: "active",
    summary: "Updated RERA rent index for 2026 reflects 8-12% market increases. Landlords can now increase rents up to 20% if current rent is 40%+ below market.",
    details: [
      "0% increase if rent is up to 10% below market average",
      "5% increase if 11-20% below market",
      "10% increase if 21-30% below market",
      "15% increase if 31-40% below market",
      "20% increase if more than 40% below market",
      "90-day notice period remains mandatory",
    ],
    affectedParties: ["Landlords", "Tenants", "Property managers"],
    source: "RERA Decree No. 2/2026",
  },
  {
    id: "reg-2026-003",
    date: "2026-01-15",
    title: "Corporate Tax — Real Estate Exemption Clarification",
    category: "tax",
    impact: "medium",
    status: "active",
    summary: "Federal Tax Authority clarifies that individual property investment income remains exempt from 9% corporate tax. Companies holding >AED 375K annual rental income are subject to CT.",
    details: [
      "Individual investors: exempt from corporate tax on rental income",
      "Individual investors: exempt on capital gains from property sales",
      "Companies/LLCs: 9% CT on net rental income above AED 375,000",
      "Free zone qualifying companies: 0% CT on qualifying activities",
      "Non-resident investors: no CT obligation on UAE property income",
    ],
    affectedParties: ["Corporate investors", "LLCs", "Free zone companies"],
    source: "Federal Tax Authority Guidance CT-2026-01",
  },

  // 2025
  {
    id: "reg-2025-001",
    date: "2025-10-01",
    title: "Golden Visa — Property Threshold Maintained at AED 2M",
    category: "visa",
    impact: "high",
    status: "active",
    summary: "UAE confirms the AED 2 million property investment threshold for 10-year Golden Visa remains unchanged. Off-plan properties now eligible if developer is government-approved.",
    details: [
      "AED 2M minimum property value (purchase price, not market value)",
      "Multiple properties can be combined to reach threshold",
      "Off-plan properties eligible if from DLD-registered developers",
      "Mortgage permitted — only equity value counts toward threshold",
      "Family visa included (spouse + children)",
      "No minimum stay requirement to maintain visa",
    ],
    affectedParties: ["All property investors", "Non-residents", "Families"],
    source: "ICP / GDRFA Updated Guidelines",
  },
  {
    id: "reg-2025-002",
    date: "2025-08-15",
    title: "RERA Mandatory BMS for New Buildings",
    category: "developer",
    impact: "medium",
    status: "active",
    summary: "All new residential buildings must implement Building Management Systems (BMS) for energy monitoring. Service charge budgets must include BMS maintenance.",
    details: [
      "Smart metering mandatory for all new buildings",
      "Real-time energy consumption dashboards for residents",
      "RERA to audit service charge budgets for BMS allocation",
      "Existing buildings encouraged but not mandated until 2028",
    ],
    affectedParties: ["Developers", "Building managers", "Owners associations"],
    source: "RERA Technical Circular 2025/08",
  },
  {
    id: "reg-2025-003",
    date: "2025-06-01",
    title: "Escrow Account Regulations Tightened",
    category: "developer",
    impact: "high",
    status: "active",
    summary: "DLD tightens escrow regulations. Developers must maintain minimum 20% buffer in escrow accounts. Mandatory quarterly reporting to buyers.",
    details: [
      "20% buffer above construction cost must remain in escrow",
      "Developers must share quarterly construction progress + escrow reports with buyers",
      "DLD can freeze project if escrow falls below threshold",
      "New penalty framework for escrow mismanagement",
      "Independent auditor verification required annually",
    ],
    affectedParties: ["Developers", "Off-plan buyers", "Banks"],
    source: "DLD Circular 2025/12",
  },
  {
    id: "reg-2025-004",
    date: "2025-04-01",
    title: "Short-Term Rental License — New Framework",
    category: "rental",
    impact: "high",
    status: "active",
    summary: "DTCM introduces streamlined holiday home licensing. One license per unit. Annual renewal. Maximum 8 guests per unit. Mandatory safety standards.",
    details: [
      "Single license per unit (no stacking)",
      "Annual license fee: AED 1,520 (apartment), AED 2,100 (villa)",
      "DTCM tourism dirham: AED 10-15/night depending on property class",
      "Mandatory smoke detectors, fire extinguisher, first aid kit",
      "Maximum occupancy based on bedroom count",
      "Platforms (Airbnb, Booking) must verify license before listing",
    ],
    affectedParties: ["Short-term rental operators", "Property owners", "Platforms"],
    source: "DTCM Regulation 2025/04",
  },
  {
    id: "reg-2025-005",
    date: "2025-03-01",
    title: "UAE Central Bank — Mortgage Stress Testing",
    category: "mortgage",
    impact: "medium",
    status: "active",
    summary: "Central Bank mandates banks stress-test mortgage applications at +2% above offered rate. Maximum DBR remains 50% but stressed DBR must not exceed 55%.",
    details: [
      "Banks must calculate affordability at offered rate + 2%",
      "Stressed DBR (debt burden ratio) must stay under 55%",
      "Applies to new applications only — existing mortgages unaffected",
      "Variable rate mortgages: stress at EIBOR + 3% above current",
      "Tighter scrutiny for BTL (buy-to-let) mortgages",
    ],
    affectedParties: ["Mortgage applicants", "Banks", "Brokers"],
    source: "CBUAE Circular 2025/03",
  },

  // 2024
  {
    id: "reg-2024-001",
    date: "2024-12-01",
    title: "DLD Fee Structure — No Changes for 2025",
    category: "dld",
    impact: "low",
    status: "active",
    summary: "DLD confirms existing 4% transfer fee and admin fee structure remains unchanged for 2025-2026.",
    details: [
      "4% transfer fee maintained (typically paid by buyer)",
      "Admin fee: AED 580 (apartments), AED 430 (land)",
      "Knowledge + Innovation fee: AED 30 total per transaction",
      "Trustee fees unchanged",
      "No new fees introduced",
    ],
    affectedParties: ["All buyers and sellers"],
    source: "DLD Annual Review 2024",
  },
  {
    id: "reg-2024-002",
    date: "2024-09-15",
    title: "RERA — Mandatory Cooling-Off Period for Off-Plan",
    category: "rera",
    impact: "high",
    status: "active",
    summary: "Buyers of off-plan properties now have a mandatory 14-day cooling-off period. Developers must refund booking deposit minus 2% admin fee if buyer cancels within window.",
    details: [
      "14 calendar days from SPA signing",
      "Written cancellation notice required",
      "Refund within 30 days of cancellation",
      "Developer may retain maximum 2% as admin/processing fee",
      "Applies to all new SPAs from October 2024",
      "Does not apply to secondary market transactions",
    ],
    affectedParties: ["Off-plan buyers", "Developers", "Brokers"],
    source: "RERA Regulation 2024/15",
  },
  {
    id: "reg-2024-003",
    date: "2024-07-01",
    title: "UAE Corporate Tax — Implementation for Real Estate",
    category: "tax",
    impact: "high",
    status: "active",
    summary: "Corporate tax (9%) fully implemented. Individual property investors remain exempt. Companies with >AED 375K annual profit from RE must register.",
    details: [
      "9% CT on taxable income above AED 375,000",
      "0% on income up to AED 375,000",
      "Individual investors (personal capacity): fully exempt",
      "Capital gains on personal property: exempt",
      "Companies must file annual CT returns",
      "Free zone qualified entities: 0% on qualifying income",
    ],
    affectedParties: ["Corporate investors", "LLCs", "Free zone entities"],
    source: "Federal Tax Authority",
  },
  {
    id: "reg-2024-004",
    date: "2024-05-01",
    title: "Retirement Visa — Property Pathway",
    category: "visa",
    impact: "medium",
    status: "active",
    summary: "UAE introduces 5-year retirement visa for property owners 55+. Minimum AED 1M property value or AED 1M in savings/investments.",
    details: [
      "Age requirement: 55 years or older",
      "Property pathway: own property worth AED 1M+",
      "Alternative: AED 1M in savings or AED 20K/month income",
      "Renewable 5-year visa",
      "Can sponsor spouse",
      "No employment restrictions",
    ],
    affectedParties: ["Retirees", "55+ property owners", "Non-residents"],
    source: "ICP Updated Residency Framework",
  },
  {
    id: "reg-2024-005",
    date: "2024-03-15",
    title: "Remote Work Visa — Property Benefit",
    category: "visa",
    impact: "low",
    status: "active",
    summary: "Remote workers on the 1-year virtual working visa can use UAE property ownership to upgrade to longer residency options without employer sponsorship.",
    details: [
      "Virtual working visa: 1 year, minimum USD 3,500/month income",
      "Property ownership adds pathway to 2-year residency",
      "Can be combined with Golden Visa if property >= AED 2M",
      "No UAE employer needed",
    ],
    affectedParties: ["Remote workers", "Digital nomads", "Property investors"],
    source: "ICP / GDRFA",
  },
  {
    id: "reg-2024-006",
    date: "2024-02-01",
    title: "Owners Association Law — Enhanced Powers",
    category: "ownership",
    impact: "medium",
    status: "active",
    summary: "Updated jointly owned property law gives owners associations more authority over service charge disputes and developer handover compliance.",
    details: [
      "OA can challenge developer service charge budgets at RERA tribunal",
      "Mandatory reserve fund: minimum 10% of annual service charge budget",
      "Developer must hand over common areas within 1 year of last unit handover",
      "OA voting can now be done electronically",
      "Annual audited accounts mandatory and must be shared with all owners",
    ],
    affectedParties: ["Property owners", "Owners associations", "Developers", "Property managers"],
    source: "Law No. 6 of 2024 — Jointly Owned Property",
  },
  {
    id: "reg-2024-007",
    date: "2024-01-10",
    title: "Broker License Requirements Tightened",
    category: "rera",
    impact: "medium",
    status: "active",
    summary: "RERA raises the bar for broker licensing. Mandatory 40-hour training, exam, and continuing education credits. Crackdown on unlicensed activity.",
    details: [
      "40-hour certified training program mandatory",
      "Written exam with 70% minimum pass mark",
      "Annual continuing education: 20 credit hours",
      "License renewal contingent on CE credits",
      "AED 50,000 fine for unlicensed brokerage activity",
      "Brokerage firms must maintain professional indemnity insurance",
    ],
    affectedParties: ["Brokers", "Brokerage firms", "Training providers"],
    source: "RERA Circular 2024/01",
  },
];

export const IMPACT_STYLES: Record<Regulation["impact"], string> = {
  high: "text-red-400 bg-red-400/10 border-red-400/20",
  medium: "text-amber-400 bg-amber-400/10 border-amber-400/20",
  low: "text-emerald-400 bg-emerald-400/10 border-emerald-400/20",
};

export const STATUS_STYLES: Record<Regulation["status"], string> = {
  active: "text-emerald-400",
  upcoming: "text-blue-400",
  proposed: "text-amber-400",
  superseded: "text-gray-500",
};
