export interface ServiceChargeEntry {
  id: string;
  community: string;
  building?: string;
  developer: string;
  propertyType: "apartment" | "villa" | "townhouse";
  serviceChargePerSqft: { min: number; max: number };
  annualEstimate1BR: number | null;
  annualEstimate2BR: number | null;
  annualEstimate3BR: number | null;
  includesChiller: boolean;
  includesGas: boolean;
  masterCommunityCharge: number | null;
  managedBy: string;
  yearEstablished: number;
  trend: "increasing" | "stable" | "decreasing";
  trendNote: string;
  rating: number;
  notes: string;
}

export const DATA_UPDATED = "2026-03-26";

export const serviceChargeData: ServiceChargeEntry[] = [
  // ── Downtown Dubai ──────────────────────────────────────────────
  {
    id: "downtown-burj-khalifa",
    community: "Downtown Dubai",
    building: "Burj Khalifa Residences",
    developer: "Emaar",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 30, max: 38 },
    annualEstimate1BR: 28000,
    annualEstimate2BR: 42000,
    annualEstimate3BR: 62000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 4.5,
    managedBy: "Emaar Community Management",
    yearEstablished: 2010,
    trend: "increasing",
    trendNote: "Increased 6% in 2025",
    rating: 2,
    notes: "Highest service charges in Dubai. Premium amenities including Armani-managed facilities, infinity pool, and concierge. Chiller is a separate significant expense.",
  },
  {
    id: "downtown-boulevard-point",
    community: "Downtown Dubai",
    building: "Boulevard Point",
    developer: "Emaar",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 22, max: 26 },
    annualEstimate1BR: 18000,
    annualEstimate2BR: 28000,
    annualEstimate3BR: 40000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 4.5,
    managedBy: "Emaar Community Management",
    yearEstablished: 2018,
    trend: "stable",
    trendNote: "Remained stable in 2025",
    rating: 3,
    notes: "Modern tower with Fountain views. Standard Emaar amenities. Master community charge applies on top.",
  },
  {
    id: "downtown-act-one-two",
    community: "Downtown Dubai",
    building: "Act One | Act Two",
    developer: "Emaar",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 20, max: 24 },
    annualEstimate1BR: 16500,
    annualEstimate2BR: 26000,
    annualEstimate3BR: 38000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 4.5,
    managedBy: "Emaar Community Management",
    yearEstablished: 2020,
    trend: "increasing",
    trendNote: "Increased 4% in 2025",
    rating: 3,
    notes: "Opera District towers. Good value relative to other Downtown properties. Rooftop infinity pool.",
  },
  {
    id: "downtown-forte",
    community: "Downtown Dubai",
    building: "Forte",
    developer: "Emaar",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 18, max: 22 },
    annualEstimate1BR: 15000,
    annualEstimate2BR: 24000,
    annualEstimate3BR: 35000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 4.5,
    managedBy: "Emaar Community Management",
    yearEstablished: 2016,
    trend: "stable",
    trendNote: "Stable since 2024",
    rating: 3,
    notes: "Older Downtown tower. Reasonable charges for the area. Well-maintained common areas.",
  },
  {
    id: "downtown-address-blvd",
    community: "Downtown Dubai",
    building: "Address Boulevard",
    developer: "Emaar",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 28, max: 35 },
    annualEstimate1BR: 25000,
    annualEstimate2BR: 38000,
    annualEstimate3BR: 55000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 4.5,
    managedBy: "Address Hotels + Resorts",
    yearEstablished: 2019,
    trend: "increasing",
    trendNote: "Increased 5% in 2025",
    rating: 2,
    notes: "Hotel-branded residences with premium service charges reflecting hospitality-grade maintenance and concierge.",
  },

  // ── Dubai Marina ────────────────────────────────────────────────
  {
    id: "marina-marina-gate",
    community: "Dubai Marina",
    building: "Marina Gate 1 & 2",
    developer: "Select Group",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 16, max: 20 },
    annualEstimate1BR: 13500,
    annualEstimate2BR: 22000,
    annualEstimate3BR: 32000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 3.0,
    managedBy: "Select Group FM",
    yearEstablished: 2018,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Well-managed newer towers with competitive charges. Excellent marina walk access.",
  },
  {
    id: "marina-cayan-tower",
    community: "Dubai Marina",
    building: "Cayan Tower (Infinity)",
    developer: "Cayan Group",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 18, max: 23 },
    annualEstimate1BR: 15000,
    annualEstimate2BR: 25000,
    annualEstimate3BR: 36000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 3.0,
    managedBy: "Cayan Facilities Management",
    yearEstablished: 2013,
    trend: "increasing",
    trendNote: "Increased 7% in 2025",
    rating: 3,
    notes: "Iconic twisted tower. Charges have been rising due to unique structural maintenance needs.",
  },
  {
    id: "marina-princess-tower",
    community: "Dubai Marina",
    building: "Princess Tower",
    developer: "Tameer",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 14, max: 18 },
    annualEstimate1BR: 11000,
    annualEstimate2BR: 18000,
    annualEstimate3BR: 26000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 3.0,
    managedBy: "Ellington Properties FM",
    yearEstablished: 2012,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "One of the tallest residential towers. Reasonable charges for Marina. Large common areas spread costs.",
  },
  {
    id: "marina-damac-heights",
    community: "Dubai Marina",
    building: "DAMAC Heights",
    developer: "DAMAC",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 19, max: 24 },
    annualEstimate1BR: 16000,
    annualEstimate2BR: 26000,
    annualEstimate3BR: 38000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 3.0,
    managedBy: "DAMAC Facilities Management",
    yearEstablished: 2018,
    trend: "increasing",
    trendNote: "Increased 9% in 2025",
    rating: 2,
    notes: "Premium finishes but DAMAC service charges have been controversial. Owners have disputed charges.",
  },
  {
    id: "marina-marina-promenade",
    community: "Dubai Marina",
    building: "Marina Promenade",
    developer: "Emaar",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 15, max: 19 },
    annualEstimate1BR: 12500,
    annualEstimate2BR: 20000,
    annualEstimate3BR: 30000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 3.0,
    managedBy: "Emaar Community Management",
    yearEstablished: 2007,
    trend: "stable",
    trendNote: "Stable since 2024",
    rating: 4,
    notes: "Older but well-maintained Emaar development. Waterfront location. Transparent billing.",
  },

  // ── JBR ─────────────────────────────────────────────────────────
  {
    id: "jbr-murjan",
    community: "JBR",
    building: "Murjan Towers (1-6)",
    developer: "Dubai Properties",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 16, max: 21 },
    annualEstimate1BR: 13000,
    annualEstimate2BR: 22000,
    annualEstimate3BR: 33000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 2.5,
    managedBy: "Dubai Properties FM",
    yearEstablished: 2007,
    trend: "increasing",
    trendNote: "Increased 5% in 2025",
    rating: 3,
    notes: "Beachfront community with extensive shared amenities. The Walk retail adds to master community costs.",
  },
  {
    id: "jbr-shams",
    community: "JBR",
    building: "Shams Towers (1-4)",
    developer: "Dubai Properties",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 17, max: 22 },
    annualEstimate1BR: 14000,
    annualEstimate2BR: 23000,
    annualEstimate3BR: 35000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 2.5,
    managedBy: "Dubai Properties FM",
    yearEstablished: 2011,
    trend: "increasing",
    trendNote: "Increased 6% in 2025",
    rating: 3,
    notes: "Newer JBR cluster. Higher charges than Murjan due to premium finishing. Beach and pool access included.",
  },
  {
    id: "jbr-amwaj",
    community: "JBR",
    building: "Amwaj Towers (1-4)",
    developer: "Dubai Properties",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 15, max: 19 },
    annualEstimate1BR: 12000,
    annualEstimate2BR: 20000,
    annualEstimate3BR: 30000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 2.5,
    managedBy: "Dubai Properties FM",
    yearEstablished: 2008,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Best value in JBR. Slightly further from beach but lower service charges.",
  },

  // ── Palm Jumeirah ───────────────────────────────────────────────
  {
    id: "palm-atlantis-residences",
    community: "Palm Jumeirah",
    building: "Atlantis The Royal Residences",
    developer: "Kerzner International",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 55, max: 70 },
    annualEstimate1BR: 80000,
    annualEstimate2BR: 130000,
    annualEstimate3BR: 200000,
    includesChiller: true,
    includesGas: true,
    masterCommunityCharge: null,
    managedBy: "Kerzner International",
    yearEstablished: 2023,
    trend: "stable",
    trendNote: "First full year of operation",
    rating: 2,
    notes: "Ultra-luxury hotel-branded residences. Includes all hotel amenities, valet, concierge. Highest in Dubai.",
  },
  {
    id: "palm-shoreline",
    community: "Palm Jumeirah",
    building: "Shoreline Apartments",
    developer: "Nakheel",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 18, max: 24 },
    annualEstimate1BR: 15000,
    annualEstimate2BR: 25000,
    annualEstimate3BR: 38000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 3.5,
    managedBy: "Nakheel Community Management",
    yearEstablished: 2008,
    trend: "increasing",
    trendNote: "Increased 8% in 2025",
    rating: 3,
    notes: "Original Palm apartments. Aging infrastructure leading to increasing maintenance costs. Beach access included.",
  },
  {
    id: "palm-golden-mile",
    community: "Palm Jumeirah",
    building: "Golden Mile",
    developer: "IFA Hotels & Resorts",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 16, max: 20 },
    annualEstimate1BR: 13000,
    annualEstimate2BR: 21000,
    annualEstimate3BR: 32000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 3.5,
    managedBy: "Asteco",
    yearEstablished: 2010,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Trunk-side apartments with retail below. Reasonable charges for Palm. Shuttle to beach available.",
  },
  {
    id: "palm-one-palm",
    community: "Palm Jumeirah",
    building: "One Palm",
    developer: "Omniyat",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 40, max: 50 },
    annualEstimate1BR: null,
    annualEstimate2BR: 70000,
    annualEstimate3BR: 110000,
    includesChiller: true,
    includesGas: false,
    masterCommunityCharge: 3.5,
    managedBy: "Dorchester Collection",
    yearEstablished: 2021,
    trend: "stable",
    trendNote: "Stable since launch",
    rating: 2,
    notes: "Ultra-premium Dorchester-branded residences. No 1BR units available. Concierge, valet, private beach.",
  },
  {
    id: "palm-tiara",
    community: "Palm Jumeirah",
    building: "Tiara Residences",
    developer: "Nakheel",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 20, max: 26 },
    annualEstimate1BR: 17000,
    annualEstimate2BR: 28000,
    annualEstimate3BR: 42000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 3.5,
    managedBy: "Nakheel Community Management",
    yearEstablished: 2010,
    trend: "increasing",
    trendNote: "Increased 4% in 2025",
    rating: 3,
    notes: "Crescent-side residences with sea views. Premium location reflected in charges.",
  },

  // ── JVC ─────────────────────────────────────────────────────────
  {
    id: "jvc-binghatti-stars",
    community: "Jumeirah Village Circle",
    building: "Binghatti Stars",
    developer: "Binghatti",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 8, max: 12 },
    annualEstimate1BR: 5500,
    annualEstimate2BR: 8500,
    annualEstimate3BR: 13000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.5,
    managedBy: "Binghatti FM",
    yearEstablished: 2019,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Affordable community with improving infrastructure. Good value for money. Newer buildings tend to have better management.",
  },
  {
    id: "jvc-bloom-towers",
    community: "Jumeirah Village Circle",
    building: "Bloom Towers",
    developer: "Bloom Properties",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 9, max: 13 },
    annualEstimate1BR: 6000,
    annualEstimate2BR: 9500,
    annualEstimate3BR: 14000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.5,
    managedBy: "Bloom FM",
    yearEstablished: 2020,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Well-managed with transparent budgets. Community pool and gym included. Good rental yield area.",
  },
  {
    id: "jvc-ghalia",
    community: "Jumeirah Village Circle",
    building: "Ghalia",
    developer: "Ellington",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 12, max: 15 },
    annualEstimate1BR: 8000,
    annualEstimate2BR: 12000,
    annualEstimate3BR: 17000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.5,
    managedBy: "Ellington FM",
    yearEstablished: 2023,
    trend: "stable",
    trendNote: "First full year of operation",
    rating: 3,
    notes: "Premium JVC development. Higher charges than JVC average due to better amenities and finishing.",
  },
  {
    id: "jvc-seasons-community",
    community: "Jumeirah Village Circle",
    building: "Seasons Community",
    developer: "Danube",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 10, max: 14 },
    annualEstimate1BR: 7000,
    annualEstimate2BR: 10500,
    annualEstimate3BR: 15000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.5,
    managedBy: "Danube FM",
    yearEstablished: 2021,
    trend: "increasing",
    trendNote: "Increased 5% in 2025",
    rating: 3,
    notes: "Multiple Danube buildings in JVC. Charges creeping up as community matures. Pool and gym in each cluster.",
  },

  // ── JLT ─────────────────────────────────────────────────────────
  {
    id: "jlt-goldcrest-views",
    community: "JLT",
    building: "Goldcrest Views 1 & 2",
    developer: "Various",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 13, max: 17 },
    annualEstimate1BR: 10000,
    annualEstimate2BR: 16000,
    annualEstimate3BR: 24000,
    includesChiller: true,
    includesGas: false,
    masterCommunityCharge: 2.0,
    managedBy: "Goldcrest FM",
    yearEstablished: 2009,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 5,
    notes: "Chiller included in service charge — big saving. One of the best value-for-money options in JLT.",
  },
  {
    id: "jlt-lake-terrace",
    community: "JLT",
    building: "Lake Terrace",
    developer: "Various",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 12, max: 16 },
    annualEstimate1BR: 9500,
    annualEstimate2BR: 15000,
    annualEstimate3BR: 22000,
    includesChiller: true,
    includesGas: false,
    masterCommunityCharge: 2.0,
    managedBy: "DMCC Facilities Management",
    yearEstablished: 2008,
    trend: "stable",
    trendNote: "Stable since 2023",
    rating: 5,
    notes: "Chiller included. Lake-facing units. DMCC management keeps charges transparent and reasonable.",
  },
  {
    id: "jlt-saba-tower",
    community: "JLT",
    building: "Saba Tower",
    developer: "Various",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 14, max: 18 },
    annualEstimate1BR: 11000,
    annualEstimate2BR: 17000,
    annualEstimate3BR: 25000,
    includesChiller: true,
    includesGas: false,
    masterCommunityCharge: 2.0,
    managedBy: "DMCC Facilities Management",
    yearEstablished: 2010,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Chiller included across all JLT towers. Newer cluster with better amenities than older JLT buildings.",
  },

  // ── Dubai Hills ─────────────────────────────────────────────────
  {
    id: "dubai-hills-park-heights",
    community: "Dubai Hills Estate",
    building: "Park Heights",
    developer: "Emaar",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 14, max: 18 },
    annualEstimate1BR: 11000,
    annualEstimate2BR: 18000,
    annualEstimate3BR: 27000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 3.0,
    managedBy: "Emaar Community Management",
    yearEstablished: 2019,
    trend: "increasing",
    trendNote: "Increased 3% in 2025",
    rating: 4,
    notes: "Overlooking Dubai Hills Park and golf course. Good value for Emaar community. Master community charge applies.",
  },
  {
    id: "dubai-hills-collective",
    community: "Dubai Hills Estate",
    building: "Collective",
    developer: "Emaar",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 16, max: 20 },
    annualEstimate1BR: 13000,
    annualEstimate2BR: 21000,
    annualEstimate3BR: 30000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 3.0,
    managedBy: "Emaar Community Management",
    yearEstablished: 2022,
    trend: "stable",
    trendNote: "Stable since handover",
    rating: 4,
    notes: "Newer apartment complex in Dubai Hills. Resort-style amenities. Competitive for a premium Emaar community.",
  },
  {
    id: "dubai-hills-villas",
    community: "Dubai Hills Estate",
    building: undefined,
    developer: "Emaar",
    propertyType: "villa",
    serviceChargePerSqft: { min: 4, max: 7 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 18000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 3.0,
    managedBy: "Emaar Community Management",
    yearEstablished: 2019,
    trend: "increasing",
    trendNote: "Increased 5% in 2025",
    rating: 4,
    notes: "Villa service charges cover landscaping, security, community pools, and parks. Master community charge on top.",
  },

  // ── Business Bay ────────────────────────────────────────────────
  {
    id: "business-bay-executive-towers",
    community: "Business Bay",
    building: "Executive Towers",
    developer: "Dubai Properties",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 14, max: 18 },
    annualEstimate1BR: 11500,
    annualEstimate2BR: 19000,
    annualEstimate3BR: 28000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 2.5,
    managedBy: "Dubai Properties FM",
    yearEstablished: 2012,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Large complex with good economies of scale. Canal-side location. Charges reasonable for the area.",
  },
  {
    id: "business-bay-paramount",
    community: "Business Bay",
    building: "Paramount Tower Hotel & Residences",
    developer: "DAMAC",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 22, max: 28 },
    annualEstimate1BR: 18000,
    annualEstimate2BR: 30000,
    annualEstimate3BR: 44000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 2.5,
    managedBy: "DAMAC Facilities Management",
    yearEstablished: 2019,
    trend: "increasing",
    trendNote: "Increased 8% in 2025",
    rating: 2,
    notes: "Hotel-branded residences with high charges. DAMAC management fees have been contested by owners.",
  },
  {
    id: "business-bay-merano",
    community: "Business Bay",
    building: "Merano Tower",
    developer: "Various",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 12, max: 16 },
    annualEstimate1BR: 9500,
    annualEstimate2BR: 16000,
    annualEstimate3BR: 24000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 2.5,
    managedBy: "Asteco",
    yearEstablished: 2014,
    trend: "stable",
    trendNote: "Stable since 2024",
    rating: 4,
    notes: "Independently managed tower with competitive rates. Third-party management tends to be more cost-effective.",
  },
  {
    id: "business-bay-bay-square",
    community: "Business Bay",
    building: "Bay Square",
    developer: "Omniyat / Meraas",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 15, max: 19 },
    annualEstimate1BR: 12000,
    annualEstimate2BR: 20000,
    annualEstimate3BR: 29000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 2.5,
    managedBy: "Meraas FM",
    yearEstablished: 2015,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 3,
    notes: "Mixed-use development with retail podium. Walkable to Downtown. Well-maintained grounds.",
  },

  // ── DAMAC Hills ─────────────────────────────────────────────────
  {
    id: "damac-hills-golf-towers",
    community: "DAMAC Hills",
    building: "Golf Towers",
    developer: "DAMAC",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 14, max: 18 },
    annualEstimate1BR: 11000,
    annualEstimate2BR: 18000,
    annualEstimate3BR: 26000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 2.0,
    managedBy: "DAMAC Facilities Management",
    yearEstablished: 2018,
    trend: "increasing",
    trendNote: "Increased 6% in 2025",
    rating: 3,
    notes: "Golf course views. DAMAC management. Community still developing with new phases being handed over.",
  },
  {
    id: "damac-hills-villas",
    community: "DAMAC Hills",
    building: undefined,
    developer: "DAMAC",
    propertyType: "villa",
    serviceChargePerSqft: { min: 4, max: 6 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 14000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 2.0,
    managedBy: "DAMAC Facilities Management",
    yearEstablished: 2018,
    trend: "increasing",
    trendNote: "Increased 5% in 2025",
    rating: 3,
    notes: "Villa community charges cover common areas, parks, and Trump-branded golf course maintenance.",
  },
  {
    id: "damac-hills-townhouses",
    community: "DAMAC Hills",
    building: "Vardon / Rockwood",
    developer: "DAMAC",
    propertyType: "townhouse",
    serviceChargePerSqft: { min: 5, max: 8 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 12000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 2.0,
    managedBy: "DAMAC Facilities Management",
    yearEstablished: 2019,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 3,
    notes: "Townhouse clusters within DAMAC Hills. Charges between villa and apartment levels.",
  },

  // ── Arabian Ranches ─────────────────────────────────────────────
  {
    id: "arabian-ranches-1",
    community: "Arabian Ranches 1",
    building: undefined,
    developer: "Emaar",
    propertyType: "villa",
    serviceChargePerSqft: { min: 3, max: 5 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 12000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: null,
    managedBy: "Emaar Community Management",
    yearEstablished: 2004,
    trend: "stable",
    trendNote: "Minimal increase in 2025",
    rating: 5,
    notes: "Established Emaar villa community. Low charges cover landscaping, security, community pool, and parks. One of the best-value villa communities.",
  },
  {
    id: "arabian-ranches-2",
    community: "Arabian Ranches 2",
    building: undefined,
    developer: "Emaar",
    propertyType: "villa",
    serviceChargePerSqft: { min: 3.5, max: 5.5 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 13000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: null,
    managedBy: "Emaar Community Management",
    yearEstablished: 2015,
    trend: "stable",
    trendNote: "Stable since 2024",
    rating: 5,
    notes: "Newer phase with upgraded amenities. Slightly higher charges than AR1 but better facilities.",
  },
  {
    id: "arabian-ranches-3",
    community: "Arabian Ranches 3",
    building: undefined,
    developer: "Emaar",
    propertyType: "townhouse",
    serviceChargePerSqft: { min: 4, max: 6 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 14000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: null,
    managedBy: "Emaar Community Management",
    yearEstablished: 2022,
    trend: "stable",
    trendNote: "First years of operation",
    rating: 4,
    notes: "Newest Arabian Ranches phase. Townhouse-focused. Community still settling into maintenance patterns.",
  },

  // ── Springs & Meadows ───────────────────────────────────────────
  {
    id: "springs",
    community: "The Springs",
    building: undefined,
    developer: "Emaar",
    propertyType: "villa",
    serviceChargePerSqft: { min: 2.5, max: 4 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 8000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: null,
    managedBy: "Emaar Community Management",
    yearEstablished: 2004,
    trend: "stable",
    trendNote: "Minimal changes over years",
    rating: 5,
    notes: "Among the lowest service charges in Dubai. Mature community with lakes, parks, and community center. Excellent value.",
  },
  {
    id: "meadows",
    community: "The Meadows",
    building: undefined,
    developer: "Emaar",
    propertyType: "villa",
    serviceChargePerSqft: { min: 3, max: 4.5 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 10000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: null,
    managedBy: "Emaar Community Management",
    yearEstablished: 2004,
    trend: "stable",
    trendNote: "Stable for years",
    rating: 5,
    notes: "Premium villa community with very low charges. Lakes, mature landscaping. One of Dubai's most established communities.",
  },

  // ── Emaar Beachfront ────────────────────────────────────────────
  {
    id: "emaar-beachfront-beach-vista",
    community: "Emaar Beachfront",
    building: "Beach Vista",
    developer: "Emaar",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 18, max: 23 },
    annualEstimate1BR: 15000,
    annualEstimate2BR: 24000,
    annualEstimate3BR: 36000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 3.0,
    managedBy: "Emaar Community Management",
    yearEstablished: 2020,
    trend: "increasing",
    trendNote: "Increased 4% in 2025",
    rating: 3,
    notes: "Private beach access. Premium beachfront living. Charges reflect island infrastructure maintenance.",
  },
  {
    id: "emaar-beachfront-sunrise-bay",
    community: "Emaar Beachfront",
    building: "Sunrise Bay",
    developer: "Emaar",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 17, max: 22 },
    annualEstimate1BR: 14000,
    annualEstimate2BR: 23000,
    annualEstimate3BR: 34000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 3.0,
    managedBy: "Emaar Community Management",
    yearEstablished: 2021,
    trend: "stable",
    trendNote: "Stable since 2024",
    rating: 4,
    notes: "Slightly more affordable than Beach Vista. Same community amenities and beach access.",
  },

  // ── City Walk ───────────────────────────────────────────────────
  {
    id: "city-walk",
    community: "City Walk",
    building: "City Walk Residences",
    developer: "Meraas",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 22, max: 28 },
    annualEstimate1BR: 18000,
    annualEstimate2BR: 30000,
    annualEstimate3BR: 45000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 4.0,
    managedBy: "Meraas FM",
    yearEstablished: 2017,
    trend: "increasing",
    trendNote: "Increased 5% in 2025",
    rating: 3,
    notes: "Urban lifestyle community with extensive retail. High charges reflect premium positioning and open-air mall maintenance.",
  },

  // ── Bluewaters ──────────────────────────────────────────────────
  {
    id: "bluewaters",
    community: "Bluewaters Island",
    building: "Bluewaters Residences",
    developer: "Meraas",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 25, max: 32 },
    annualEstimate1BR: 22000,
    annualEstimate2BR: 35000,
    annualEstimate3BR: 52000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 5.0,
    managedBy: "Meraas FM",
    yearEstablished: 2019,
    trend: "increasing",
    trendNote: "Increased 7% in 2025",
    rating: 2,
    notes: "Island living with Ain Dubai. Very high master community charge for island infrastructure. Premium but expensive.",
  },

  // ── DSO ─────────────────────────────────────────────────────────
  {
    id: "dso-binghatti-avenue",
    community: "Dubai Silicon Oasis",
    building: "Binghatti Avenue",
    developer: "Binghatti",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 8, max: 11 },
    annualEstimate1BR: 5000,
    annualEstimate2BR: 8000,
    annualEstimate3BR: 12000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.0,
    managedBy: "DSOA Management",
    yearEstablished: 2018,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Tech park community with low charges. Good for investors. DSOA authority manages the master community.",
  },
  {
    id: "dso-silicon-heights",
    community: "Dubai Silicon Oasis",
    building: "Silicon Heights",
    developer: "Tiger Properties",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 9, max: 13 },
    annualEstimate1BR: 6000,
    annualEstimate2BR: 9000,
    annualEstimate3BR: 13000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.0,
    managedBy: "DSOA Management",
    yearEstablished: 2015,
    trend: "stable",
    trendNote: "Minimal changes",
    rating: 4,
    notes: "Established DSO tower with consistent charges. Community park and retail nearby.",
  },

  // ── International City ──────────────────────────────────────────
  {
    id: "international-city-china",
    community: "International City",
    building: "China Cluster",
    developer: "Nakheel",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 6, max: 9 },
    annualEstimate1BR: 3500,
    annualEstimate2BR: 5500,
    annualEstimate3BR: null,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.0,
    managedBy: "Nakheel Community Management",
    yearEstablished: 2007,
    trend: "stable",
    trendNote: "Stable for years",
    rating: 4,
    notes: "Among the cheapest service charges in Dubai. Basic amenities. Popular with budget-conscious investors.",
  },
  {
    id: "international-city-persia",
    community: "International City",
    building: "Persia Cluster",
    developer: "Nakheel",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 6, max: 9 },
    annualEstimate1BR: 3500,
    annualEstimate2BR: 5500,
    annualEstimate3BR: null,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.0,
    managedBy: "Nakheel Community Management",
    yearEstablished: 2007,
    trend: "stable",
    trendNote: "Stable for years",
    rating: 4,
    notes: "Same pricing as other International City clusters. Low-rise buildings keep maintenance costs down.",
  },

  // ── Discovery Gardens ──────────────────────────────────────────
  {
    id: "discovery-gardens",
    community: "Discovery Gardens",
    building: "Various Clusters",
    developer: "Nakheel",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 7, max: 10 },
    annualEstimate1BR: 4500,
    annualEstimate2BR: 7000,
    annualEstimate3BR: null,
    includesChiller: true,
    includesGas: false,
    masterCommunityCharge: null,
    managedBy: "Nakheel Community Management",
    yearEstablished: 2007,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 5,
    notes: "Chiller included in service charge — rare for this price range. One of Dubai's best value propositions. Near Ibn Battuta and Metro.",
  },

  // ── Motor City ──────────────────────────────────────────────────
  {
    id: "motor-city-uptown",
    community: "Motor City",
    building: "Uptown Motor City",
    developer: "Union Properties",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 10, max: 14 },
    annualEstimate1BR: 7000,
    annualEstimate2BR: 11000,
    annualEstimate3BR: 16000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.5,
    managedBy: "Union Properties FM",
    yearEstablished: 2010,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Autodrome-adjacent community. Family-friendly with pools and parks. Reasonable charges.",
  },

  // ── Sports City ─────────────────────────────────────────────────
  {
    id: "sports-city-elite",
    community: "Dubai Sports City",
    building: "Elite Residence",
    developer: "Various",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 9, max: 13 },
    annualEstimate1BR: 6500,
    annualEstimate2BR: 10000,
    annualEstimate3BR: 15000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.5,
    managedBy: "DSC Authority",
    yearEstablished: 2012,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Sports-focused community with cricket stadium, golf course. Low charges with good amenities.",
  },

  // ── Al Furjan ───────────────────────────────────────────────────
  {
    id: "al-furjan-villas",
    community: "Al Furjan",
    building: undefined,
    developer: "Nakheel",
    propertyType: "villa",
    serviceChargePerSqft: { min: 3, max: 5 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 11000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: null,
    managedBy: "Nakheel Community Management",
    yearEstablished: 2014,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Affordable villa community near metro. Pavilion mall nearby. Low service charges for villas.",
  },
  {
    id: "al-furjan-apartments",
    community: "Al Furjan",
    building: "Azizi Riviera / MAG 5",
    developer: "Various",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 10, max: 14 },
    annualEstimate1BR: 7000,
    annualEstimate2BR: 11000,
    annualEstimate3BR: 16000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.5,
    managedBy: "Various",
    yearEstablished: 2019,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Growing apartment supply in Al Furjan. Near metro. Charges vary by developer.",
  },

  // ── Town Square ─────────────────────────────────────────────────
  {
    id: "town-square",
    community: "Town Square",
    building: "Various (Hayat, Safi, etc.)",
    developer: "Nshama",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 10, max: 14 },
    annualEstimate1BR: 7000,
    annualEstimate2BR: 11000,
    annualEstimate3BR: 16000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.5,
    managedBy: "Nshama FM",
    yearEstablished: 2018,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Large master-planned community. Central park. Good value with extensive shared amenities.",
  },
  {
    id: "town-square-townhouses",
    community: "Town Square",
    building: "Naseem Townhouses",
    developer: "Nshama",
    propertyType: "townhouse",
    serviceChargePerSqft: { min: 5, max: 8 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 13000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.5,
    managedBy: "Nshama FM",
    yearEstablished: 2019,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Townhouse community within Town Square. Access to all community amenities including massive park.",
  },

  // ── Dubai Creek Harbour ─────────────────────────────────────────
  {
    id: "creek-harbour-creek-rise",
    community: "Dubai Creek Harbour",
    building: "Creek Rise",
    developer: "Emaar",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 16, max: 20 },
    annualEstimate1BR: 13000,
    annualEstimate2BR: 21000,
    annualEstimate3BR: 31000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 3.5,
    managedBy: "Emaar Community Management",
    yearEstablished: 2021,
    trend: "increasing",
    trendNote: "Increased 3% in 2025",
    rating: 3,
    notes: "Creek-side living with views of future Dubai Creek Tower. New community still adding amenities. High master charge.",
  },

  // ── Mirdif / Mirdif Hills ──────────────────────────────────────
  {
    id: "mirdif-hills",
    community: "Mirdif Hills",
    building: "Janayen Avenue",
    developer: "Dubai Holding",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 11, max: 15 },
    annualEstimate1BR: 8500,
    annualEstimate2BR: 13000,
    annualEstimate3BR: 19000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 2.0,
    managedBy: "Dubai Holding FM",
    yearEstablished: 2020,
    trend: "stable",
    trendNote: "Stable since handover",
    rating: 4,
    notes: "Family-friendly area near Mirdif City Centre. Mixed-use community with retail and schools.",
  },

  // ── Mudon ───────────────────────────────────────────────────────
  {
    id: "mudon-villas",
    community: "Mudon",
    building: undefined,
    developer: "Dubai Properties",
    propertyType: "villa",
    serviceChargePerSqft: { min: 3.5, max: 5.5 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 12000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: null,
    managedBy: "Dubai Properties FM",
    yearEstablished: 2016,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Affordable villa community. Community center with pool, gym, and parks. Popular with families.",
  },
  {
    id: "mudon-townhouses",
    community: "Mudon",
    building: "Arabella Townhouses",
    developer: "Dubai Properties",
    propertyType: "townhouse",
    serviceChargePerSqft: { min: 4, max: 6 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 11000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: null,
    managedBy: "Dubai Properties FM",
    yearEstablished: 2018,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Townhouse community within Mudon. Access to all Mudon amenities. Good value.",
  },

  // ── Sobha Hartland ──────────────────────────────────────────────
  {
    id: "sobha-hartland",
    community: "Sobha Hartland",
    building: "Hartland Greens / Creek Vistas",
    developer: "Sobha Realty",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 14, max: 18 },
    annualEstimate1BR: 11000,
    annualEstimate2BR: 18000,
    annualEstimate3BR: 27000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 2.5,
    managedBy: "Sobha FM",
    yearEstablished: 2020,
    trend: "stable",
    trendNote: "Stable since handover",
    rating: 4,
    notes: "Quality construction. Creek-side community with schools and retail. Transparent management.",
  },

  // ── Villanova ───────────────────────────────────────────────────
  {
    id: "villanova-townhouses",
    community: "Villanova",
    building: "Amaranta / La Rosa",
    developer: "Dubai Properties",
    propertyType: "townhouse",
    serviceChargePerSqft: { min: 4, max: 7 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 13000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.5,
    managedBy: "Dubai Properties FM",
    yearEstablished: 2020,
    trend: "stable",
    trendNote: "Stable since handover",
    rating: 4,
    notes: "Growing townhouse community near Dubailand. Family-oriented with parks and community pools.",
  },

  // ── Tilal Al Ghaf ───────────────────────────────────────────────
  {
    id: "tilal-al-ghaf",
    community: "Tilal Al Ghaf",
    building: undefined,
    developer: "Majid Al Futtaim",
    propertyType: "villa",
    serviceChargePerSqft: { min: 5, max: 8 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 18000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 2.5,
    managedBy: "Majid Al Futtaim Communities",
    yearEstablished: 2023,
    trend: "stable",
    trendNote: "First years of operation",
    rating: 3,
    notes: "Premium new villa community with lagoon. Higher charges expected as community matures. Crystal lagoon maintenance adds cost.",
  },

  // ── MBR City / District One ─────────────────────────────────────
  {
    id: "district-one-villas",
    community: "District One (MBR City)",
    building: undefined,
    developer: "Meydan / Sobha",
    propertyType: "villa",
    serviceChargePerSqft: { min: 6, max: 10 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 25000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 3.0,
    managedBy: "Meydan Community Management",
    yearEstablished: 2019,
    trend: "increasing",
    trendNote: "Increased 8% in 2025",
    rating: 3,
    notes: "Luxury villa community with crystal lagoon. High charges for villa category. Premium positioning next to Meydan Racecourse.",
  },

  // ── Production City (IMPZ) ─────────────────────────────────────
  {
    id: "impz",
    community: "Production City (IMPZ)",
    building: "Centrium Towers / Lakeside",
    developer: "Various",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 7, max: 11 },
    annualEstimate1BR: 4500,
    annualEstimate2BR: 7500,
    annualEstimate3BR: 11000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.0,
    managedBy: "Various",
    yearEstablished: 2010,
    trend: "stable",
    trendNote: "Stable for years",
    rating: 4,
    notes: "Affordable community. Basic amenities. Good for budget investors. Near Motor City and Sports City.",
  },

  // ── Remraam ─────────────────────────────────────────────────────
  {
    id: "remraam",
    community: "Remraam",
    building: "Al Ramth / Al Thamam",
    developer: "Dubai Properties",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 8, max: 12 },
    annualEstimate1BR: 5500,
    annualEstimate2BR: 8500,
    annualEstimate3BR: 13000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.0,
    managedBy: "Dubai Properties FM",
    yearEstablished: 2015,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Low-rise garden community. Family-friendly. One of the more affordable options near Dubailand.",
  },

  // ── Greens ──────────────────────────────────────────────────────
  {
    id: "greens",
    community: "The Greens",
    building: "Various (Al Ghaf, Al Sidr, etc.)",
    developer: "Emaar",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 12, max: 16 },
    annualEstimate1BR: 9000,
    annualEstimate2BR: 14000,
    annualEstimate3BR: 20000,
    includesChiller: true,
    includesGas: false,
    masterCommunityCharge: null,
    managedBy: "Emaar Community Management",
    yearEstablished: 2004,
    trend: "stable",
    trendNote: "Stable for years",
    rating: 5,
    notes: "Chiller included. Mature Emaar community with lakes and landscaping. Excellent value considering chiller savings.",
  },

  // ── Views ───────────────────────────────────────────────────────
  {
    id: "views",
    community: "The Views",
    building: "Various (Tanaro, Mosela, etc.)",
    developer: "Emaar",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 13, max: 17 },
    annualEstimate1BR: 10000,
    annualEstimate2BR: 16000,
    annualEstimate3BR: 23000,
    includesChiller: true,
    includesGas: false,
    masterCommunityCharge: null,
    managedBy: "Emaar Community Management",
    yearEstablished: 2007,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 5,
    notes: "Chiller included. Golf course and canal views. Similar to Greens but slightly larger apartments. Excellent value.",
  },

  // ── Dubailand / Arjan ───────────────────────────────────────────
  {
    id: "arjan",
    community: "Arjan (Dubailand)",
    building: "Various (Vincitore, Resortz, etc.)",
    developer: "Various",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 9, max: 13 },
    annualEstimate1BR: 6000,
    annualEstimate2BR: 9500,
    annualEstimate3BR: 14000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.0,
    managedBy: "Various",
    yearEstablished: 2019,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Emerging community near Miracle Garden. Many new developments. Charges vary significantly by developer.",
  },

  // ── Dubai South ─────────────────────────────────────────────────
  {
    id: "dubai-south",
    community: "Dubai South",
    building: "The Pulse / MAG 5 Boulevard",
    developer: "Dubai South / MAG",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 8, max: 12 },
    annualEstimate1BR: 5500,
    annualEstimate2BR: 8500,
    annualEstimate3BR: 13000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.0,
    managedBy: "Dubai South FM",
    yearEstablished: 2019,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Near Expo City and Al Maktoum Airport. Affordable with growth potential. Community still developing.",
  },

  // ── Jumeirah Islands ────────────────────────────────────────────
  {
    id: "jumeirah-islands",
    community: "Jumeirah Islands",
    building: undefined,
    developer: "Nakheel",
    propertyType: "villa",
    serviceChargePerSqft: { min: 3, max: 5 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 15000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: null,
    managedBy: "Nakheel Community Management",
    yearEstablished: 2007,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Island-style villa community. Each cluster on its own island surrounded by lakes. Low charges for premium location.",
  },

  // ── Jumeirah Park ───────────────────────────────────────────────
  {
    id: "jumeirah-park",
    community: "Jumeirah Park",
    building: undefined,
    developer: "Nakheel",
    propertyType: "villa",
    serviceChargePerSqft: { min: 2.5, max: 4.5 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 10000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: null,
    managedBy: "Nakheel Community Management",
    yearEstablished: 2012,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 5,
    notes: "One of Dubai's lowest service charges for villas. Parks and community center. Near Al Khail Road.",
  },

  // ── Reem (Dubai) ────────────────────────────────────────────────
  {
    id: "reem-townhouses",
    community: "Reem (Dubai)",
    building: "Mira / Mira Oasis",
    developer: "Emaar",
    propertyType: "townhouse",
    serviceChargePerSqft: { min: 4, max: 6 },
    annualEstimate1BR: null,
    annualEstimate2BR: null,
    annualEstimate3BR: 11000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: null,
    managedBy: "Emaar Community Management",
    yearEstablished: 2015,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Affordable Emaar townhouse community. Community pool and parks. Near Arabian Ranches.",
  },

  // ── MJL / Madinat Jumeirah Living ───────────────────────────────
  {
    id: "madinat-jumeirah-living",
    community: "Madinat Jumeirah Living",
    building: "Rahaal / Asayel",
    developer: "Meraas / Dubai Holding",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 18, max: 23 },
    annualEstimate1BR: 15000,
    annualEstimate2BR: 24000,
    annualEstimate3BR: 36000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 3.5,
    managedBy: "Meraas FM",
    yearEstablished: 2022,
    trend: "stable",
    trendNote: "Stable since handover",
    rating: 3,
    notes: "Premium community near Burj Al Arab. High master community charge reflects location prestige.",
  },

  // ── Wasl Gate ───────────────────────────────────────────────────
  {
    id: "wasl-gate",
    community: "Wasl Gate",
    building: "Various",
    developer: "Wasl",
    propertyType: "apartment",
    serviceChargePerSqft: { min: 10, max: 14 },
    annualEstimate1BR: 7500,
    annualEstimate2BR: 12000,
    annualEstimate3BR: 17000,
    includesChiller: false,
    includesGas: false,
    masterCommunityCharge: 1.5,
    managedBy: "Wasl Properties FM",
    yearEstablished: 2019,
    trend: "stable",
    trendNote: "Stable in 2025",
    rating: 4,
    notes: "Government-developer community near Jebel Ali. Reasonable charges with good build quality.",
  },
];
