// Tenant Screening Score — Area demand, vacancy risk, and rental market intelligence
// Sources: RERA, Property Monitor, Bayut/Dubizzle market reports

export interface AreaRentalProfile {
  area: string;
  demandScore: number; // 0-100
  vacancyRate: number; // %
  avgDaysToLease: number;
  avgRentStudio: number;
  avgRent1BR: number;
  avgRent2BR: number;
  avgRent3BR: number;
  yoyRentChange: number; // %
  tenantDemographic: string;
  topNationalities: string[];
  renewalRate: number; // %
  segment: "premium" | "mid" | "affordable";
  riskLevel: "low" | "medium" | "high";
  insights: string[];
}

export const AREA_RENTAL_DATA: AreaRentalProfile[] = [
  {
    area: "Downtown Dubai",
    demandScore: 92,
    vacancyRate: 3.2,
    avgDaysToLease: 14,
    avgRentStudio: 65000,
    avgRent1BR: 120000,
    avgRent2BR: 185000,
    avgRent3BR: 280000,
    yoyRentChange: 12.5,
    tenantDemographic: "Young professionals, executives, tourists (short-term)",
    topNationalities: ["British", "Indian", "European"],
    renewalRate: 78,
    segment: "premium",
    riskLevel: "low",
    insights: [
      "Consistently high demand due to Burj Khalifa and Dubai Mall proximity",
      "Short-term rental competition from holiday homes",
      "Service charges among highest in Dubai (AED 25-35/sqft)",
    ],
  },
  {
    area: "Dubai Marina",
    demandScore: 90,
    vacancyRate: 3.8,
    avgDaysToLease: 16,
    avgRentStudio: 55000,
    avgRent1BR: 95000,
    avgRent2BR: 150000,
    avgRent3BR: 220000,
    yoyRentChange: 10.8,
    tenantDemographic: "Young professionals, couples, short-stay visitors",
    topNationalities: ["British", "Russian", "Filipino"],
    renewalRate: 75,
    segment: "premium",
    riskLevel: "low",
    insights: [
      "Walk-to-beach lifestyle drives consistent demand",
      "Tram and Metro connectivity adds value",
      "Parking is a premium — units with parking rent 10-15% higher",
    ],
  },
  {
    area: "Palm Jumeirah",
    demandScore: 85,
    vacancyRate: 5.2,
    avgDaysToLease: 22,
    avgRentStudio: 75000,
    avgRent1BR: 140000,
    avgRent2BR: 220000,
    avgRent3BR: 380000,
    yoyRentChange: 8.5,
    tenantDemographic: "High-net-worth families, executives, celebrities",
    topNationalities: ["Russian", "British", "Chinese"],
    renewalRate: 72,
    segment: "premium",
    riskLevel: "low",
    insights: [
      "Longer lease times due to higher price point",
      "Villa/townhouse demand outstrips supply",
      "Holiday home licenses highly lucrative here",
    ],
  },
  {
    area: "Business Bay",
    demandScore: 88,
    vacancyRate: 4.5,
    avgDaysToLease: 18,
    avgRentStudio: 50000,
    avgRent1BR: 85000,
    avgRent2BR: 130000,
    avgRent3BR: 195000,
    yoyRentChange: 14.2,
    tenantDemographic: "Professionals, young couples, work-from-home tenants",
    topNationalities: ["Indian", "Pakistani", "Filipino"],
    renewalRate: 74,
    segment: "premium",
    riskLevel: "low",
    insights: [
      "Rapidly appreciating rents — some of the highest YoY growth",
      "Canal views command 15-20% premium",
      "Oversupply risk as many new towers complete 2026-2027",
    ],
  },
  {
    area: "JVC (Jumeirah Village Circle)",
    demandScore: 94,
    vacancyRate: 2.8,
    avgDaysToLease: 10,
    avgRentStudio: 38000,
    avgRent1BR: 55000,
    avgRent2BR: 80000,
    avgRent3BR: 110000,
    yoyRentChange: 18.5,
    tenantDemographic: "Families, young professionals, budget-conscious expats",
    topNationalities: ["Indian", "Pakistani", "Filipino"],
    renewalRate: 82,
    segment: "mid",
    riskLevel: "low",
    insights: [
      "Highest transaction volume area in Dubai",
      "Extreme demand but significant new supply incoming",
      "Best value proposition for families in central Dubai",
    ],
  },
  {
    area: "JLT (Jumeirah Lake Towers)",
    demandScore: 86,
    vacancyRate: 4.0,
    avgDaysToLease: 15,
    avgRentStudio: 42000,
    avgRent1BR: 72000,
    avgRent2BR: 105000,
    avgRent3BR: 145000,
    yoyRentChange: 11.2,
    tenantDemographic: "Professionals, small families, freelancers",
    topNationalities: ["Indian", "British", "Pakistani"],
    renewalRate: 76,
    segment: "mid",
    riskLevel: "low",
    insights: [
      "DMCC free zone proximity drives commercial tenant demand",
      "Lake-facing units premium vs cluster-facing",
      "Aging stock — some buildings need renovation",
    ],
  },
  {
    area: "Dubai Hills Estate",
    demandScore: 91,
    vacancyRate: 3.0,
    avgDaysToLease: 12,
    avgRentStudio: 48000,
    avgRent1BR: 90000,
    avgRent2BR: 140000,
    avgRent3BR: 200000,
    yoyRentChange: 16.8,
    tenantDemographic: "Families with children, professionals, golf enthusiasts",
    topNationalities: ["Indian", "British", "European"],
    renewalRate: 85,
    segment: "premium",
    riskLevel: "low",
    insights: [
      "Dubai Hills Mall opened — massive demand driver",
      "Schools and parks make it the top family area",
      "Villa rental demand far exceeds supply",
    ],
  },
  {
    area: "Al Furjan",
    demandScore: 82,
    vacancyRate: 4.8,
    avgDaysToLease: 17,
    avgRentStudio: 35000,
    avgRent1BR: 58000,
    avgRent2BR: 82000,
    avgRent3BR: 120000,
    yoyRentChange: 14.0,
    tenantDemographic: "Families, young professionals",
    topNationalities: ["Indian", "Pakistani", "Egyptian"],
    renewalRate: 78,
    segment: "mid",
    riskLevel: "medium",
    insights: [
      "Metro Route 2020 connectivity boosted demand",
      "Pavilion-style villas popular with families",
      "New apartment supply may soften rents in 2027",
    ],
  },
  {
    area: "Arjan",
    demandScore: 80,
    vacancyRate: 5.5,
    avgDaysToLease: 19,
    avgRentStudio: 32000,
    avgRent1BR: 48000,
    avgRent2BR: 70000,
    avgRent3BR: 95000,
    yoyRentChange: 20.1,
    tenantDemographic: "Budget-conscious families, young professionals",
    topNationalities: ["Indian", "Pakistani", "Bangladeshi"],
    renewalRate: 74,
    segment: "mid",
    riskLevel: "medium",
    insights: [
      "Miracle Garden proximity adds appeal",
      "Massive new supply pipeline — over 8,000 units by 2027",
      "Highest rent growth but watch for correction",
    ],
  },
  {
    area: "International City",
    demandScore: 78,
    vacancyRate: 6.2,
    avgDaysToLease: 12,
    avgRentStudio: 22000,
    avgRent1BR: 32000,
    avgRent2BR: 48000,
    avgRent3BR: 62000,
    yoyRentChange: 15.5,
    tenantDemographic: "Budget tenants, bachelors, labor class families",
    topNationalities: ["Indian", "Pakistani", "Bangladeshi"],
    renewalRate: 70,
    segment: "affordable",
    riskLevel: "medium",
    insights: [
      "Cheapest apartments in Dubai — high demand but older stock",
      "Phase 2 (near Dragon Mart 2) offers newer options",
      "Maintenance issues common in older clusters",
    ],
  },
  {
    area: "Dubai South",
    demandScore: 72,
    vacancyRate: 8.5,
    avgDaysToLease: 28,
    avgRentStudio: 25000,
    avgRent1BR: 38000,
    avgRent2BR: 55000,
    avgRent3BR: 75000,
    yoyRentChange: 12.8,
    tenantDemographic: "Airport workers, Expo area employees, budget seekers",
    topNationalities: ["Indian", "Pakistani", "Egyptian"],
    renewalRate: 65,
    segment: "affordable",
    riskLevel: "high",
    insights: [
      "Al Maktoum Airport expansion is the long-term catalyst",
      "Current infrastructure still developing",
      "Higher vacancy — requires competitive pricing",
    ],
  },
  {
    area: "Town Square",
    demandScore: 84,
    vacancyRate: 4.2,
    avgDaysToLease: 14,
    avgRentStudio: 30000,
    avgRent1BR: 45000,
    avgRent2BR: 68000,
    avgRent3BR: 90000,
    yoyRentChange: 16.5,
    tenantDemographic: "Young families, first-time renters, couples",
    topNationalities: ["Indian", "Pakistani", "Egyptian"],
    renewalRate: 80,
    segment: "affordable",
    riskLevel: "low",
    insights: [
      "Self-contained community with parks, retail, dining",
      "Strong family appeal — schools and nurseries nearby",
      "Nshama developer maintains well",
    ],
  },
  {
    area: "Creek Harbour",
    demandScore: 87,
    vacancyRate: 4.0,
    avgDaysToLease: 16,
    avgRentStudio: 55000,
    avgRent1BR: 95000,
    avgRent2BR: 145000,
    avgRent3BR: 210000,
    yoyRentChange: 15.2,
    tenantDemographic: "Professionals, families, investors",
    topNationalities: ["Indian", "Chinese", "European"],
    renewalRate: 77,
    segment: "premium",
    riskLevel: "low",
    insights: [
      "Dubai Creek Tower (when complete) will be major demand driver",
      "Emaar quality and community management",
      "Creek views command significant premium",
    ],
  },
  {
    area: "Motor City",
    demandScore: 76,
    vacancyRate: 5.0,
    avgDaysToLease: 20,
    avgRentStudio: 32000,
    avgRent1BR: 48000,
    avgRent2BR: 72000,
    avgRent3BR: 100000,
    yoyRentChange: 10.5,
    tenantDemographic: "Families, motorsport enthusiasts, budget mid-market",
    topNationalities: ["Indian", "British", "South African"],
    renewalRate: 75,
    segment: "mid",
    riskLevel: "medium",
    insights: [
      "Autodrome attracts niche demographic",
      "Good community feel but limited retail",
      "Stable rents — less volatile than newer areas",
    ],
  },
  {
    area: "DIFC",
    demandScore: 83,
    vacancyRate: 6.0,
    avgDaysToLease: 25,
    avgRentStudio: 70000,
    avgRent1BR: 140000,
    avgRent2BR: 220000,
    avgRent3BR: 350000,
    yoyRentChange: 9.8,
    tenantDemographic: "Finance professionals, corporate executives",
    topNationalities: ["British", "American", "European"],
    renewalRate: 70,
    segment: "premium",
    riskLevel: "medium",
    insights: [
      "Premium corporate tenant base but small residential pool",
      "Walking distance to Gate Avenue retail/dining",
      "High service charges offset yield",
    ],
  },
];

export const SCORING_WEIGHTS = {
  demandScore: 0.25,
  vacancyRate: 0.20, // inverse
  daysToLease: 0.15, // inverse
  yoyRentChange: 0.15,
  renewalRate: 0.15,
  riskLevel: 0.10,
};
