// ---------------------------------------------------------------------------
// Dubai Rental Yield Heatmap — Area Data (2025-2026)
// ---------------------------------------------------------------------------

export interface AreaYield {
  id: string;
  name: string;
  avgYield: number;
  yieldRange: { min: number; max: number };
  avgRentStudio: number | null;
  avgRent1BR: number | null;
  avgRent2BR: number | null;
  avgRent3BR: number | null;
  avgPricePerSqft: number;
  priceRange: [number, number];
  totalListings: string;
  yoyChange: number;
  propertyTypes: string[];
  zone: ZoneKey;
  coordinates: { lat: number; lng: number };
  description: string;
}

export type ZoneKey =
  | "marina-jbr"
  | "downtown-business-bay"
  | "new-dubai"
  | "old-dubai"
  | "suburban"
  | "emerging";

export interface ZoneDefinition {
  key: ZoneKey;
  label: string;
  color: string;
  description: string;
}

export const ZONES: ZoneDefinition[] = [
  { key: "marina-jbr", label: "Marina / JBR", color: "#93c5fd", description: "Waterfront high-rise living along the marina and beach" },
  { key: "downtown-business-bay", label: "Downtown / Business Bay", color: "#c4b5fd", description: "Iconic skyline district with premium towers" },
  { key: "new-dubai", label: "New Dubai", color: "#6ee7b7", description: "Established communities with modern infrastructure" },
  { key: "old-dubai", label: "Old Dubai", color: "#fcd34d", description: "Heritage areas and affordable city-centre living" },
  { key: "suburban", label: "Suburban", color: "#fdba74", description: "Family-oriented villa communities" },
  { key: "emerging", label: "Emerging", color: "#f9a8d4", description: "Up-and-coming areas with strong growth potential" },
];

export const DATA_UPDATED = "March 2026";

// ---------------------------------------------------------------------------
// 42 Dubai Areas — realistic 2025-2026 rental yield estimates
// ---------------------------------------------------------------------------

export const areas: AreaYield[] = [
  // ── Marina / JBR Zone ──────────────────────────────────────────────────
  {
    id: "dubai-marina",
    name: "Dubai Marina",
    avgYield: 6.1,
    yieldRange: { min: 5.2, max: 7.0 },
    avgRentStudio: 55000,
    avgRent1BR: 85000,
    avgRent2BR: 130000,
    avgRent3BR: 195000,
    avgPricePerSqft: 1650,
    priceRange: [750000, 8000000],
    totalListings: "3,200+",
    yoyChange: -0.3,
    propertyTypes: ["Apartment", "Penthouse"],
    zone: "marina-jbr",
    coordinates: { lat: 25.0780, lng: 55.1390 },
    description: "Dubai Marina remains one of the city's most sought-after waterfront addresses. High-rise towers line the man-made canal with direct access to beaches, dining, and the tram network. Yields have stabilised as prices caught up with rents.",
  },
  {
    id: "jbr",
    name: "Jumeirah Beach Residence",
    avgYield: 5.8,
    yieldRange: { min: 5.0, max: 6.5 },
    avgRentStudio: 58000,
    avgRent1BR: 90000,
    avgRent2BR: 140000,
    avgRent3BR: 210000,
    avgPricePerSqft: 1800,
    priceRange: [900000, 10000000],
    totalListings: "1,100+",
    yoyChange: -0.2,
    propertyTypes: ["Apartment", "Penthouse"],
    zone: "marina-jbr",
    coordinates: { lat: 25.0790, lng: 55.1330 },
    description: "JBR offers beachfront living with The Walk promenade and Ain Dubai nearby. Premium rents are offset by equally premium prices, keeping yields moderate but stable.",
  },
  {
    id: "emaar-beachfront",
    name: "Emaar Beachfront",
    avgYield: 5.5,
    yieldRange: { min: 4.8, max: 6.2 },
    avgRentStudio: 65000,
    avgRent1BR: 100000,
    avgRent2BR: 160000,
    avgRent3BR: 240000,
    avgPricePerSqft: 2100,
    priceRange: [1200000, 15000000],
    totalListings: "450+",
    yoyChange: 0.1,
    propertyTypes: ["Apartment", "Penthouse"],
    zone: "marina-jbr",
    coordinates: { lat: 25.0830, lng: 55.1280 },
    description: "A newer island community by Emaar between Palm Jumeirah and JBR. Private beach access and branded residences attract high-end tenants willing to pay premium rents.",
  },
  {
    id: "bluewaters",
    name: "Bluewaters Island",
    avgYield: 5.3,
    yieldRange: { min: 4.5, max: 6.0 },
    avgRentStudio: null,
    avgRent1BR: 110000,
    avgRent2BR: 175000,
    avgRent3BR: 280000,
    avgPricePerSqft: 2300,
    priceRange: [1500000, 20000000],
    totalListings: "200+",
    yoyChange: -0.1,
    propertyTypes: ["Apartment", "Penthouse", "Townhouse"],
    zone: "marina-jbr",
    coordinates: { lat: 25.0820, lng: 55.1200 },
    description: "Home to Ain Dubai, Bluewaters is a boutique island community. Limited inventory and resort-style amenities command top-tier rents but equally high sale prices.",
  },

  // ── Downtown / Business Bay Zone ───────────────────────────────────────
  {
    id: "downtown-dubai",
    name: "Downtown Dubai",
    avgYield: 5.0,
    yieldRange: { min: 4.2, max: 5.8 },
    avgRentStudio: 60000,
    avgRent1BR: 95000,
    avgRent2BR: 155000,
    avgRent3BR: 240000,
    avgPricePerSqft: 2200,
    priceRange: [900000, 25000000],
    totalListings: "2,800+",
    yoyChange: -0.4,
    propertyTypes: ["Apartment", "Penthouse"],
    zone: "downtown-business-bay",
    coordinates: { lat: 25.1972, lng: 55.2744 },
    description: "The Burj Khalifa district is Dubai's most iconic address. Strong rental demand from corporates and tourists, though capital values have risen faster than rents, compressing yields.",
  },
  {
    id: "business-bay",
    name: "Business Bay",
    avgYield: 6.4,
    yieldRange: { min: 5.5, max: 7.3 },
    avgRentStudio: 48000,
    avgRent1BR: 75000,
    avgRent2BR: 120000,
    avgRent3BR: 180000,
    avgPricePerSqft: 1400,
    priceRange: [600000, 8000000],
    totalListings: "4,500+",
    yoyChange: 0.2,
    propertyTypes: ["Apartment", "Penthouse", "Office"],
    zone: "downtown-business-bay",
    coordinates: { lat: 25.1860, lng: 55.2620 },
    description: "Business Bay blends commercial and residential towers along the Dubai Canal. More affordable than Downtown with comparable connectivity, making it a yield-friendly alternative.",
  },
  {
    id: "city-walk",
    name: "City Walk",
    avgYield: 4.8,
    yieldRange: { min: 4.0, max: 5.5 },
    avgRentStudio: null,
    avgRent1BR: 110000,
    avgRent2BR: 170000,
    avgRent3BR: 260000,
    avgPricePerSqft: 2500,
    priceRange: [1500000, 12000000],
    totalListings: "350+",
    yoyChange: -0.2,
    propertyTypes: ["Apartment", "Duplex"],
    zone: "downtown-business-bay",
    coordinates: { lat: 25.2070, lng: 55.2600 },
    description: "A boutique urban district by Meraas with designer retail and dining. Low-density living near Downtown appeals to high-income professionals seeking a walkable lifestyle.",
  },
  {
    id: "creek-harbour",
    name: "Dubai Creek Harbour",
    avgYield: 5.6,
    yieldRange: { min: 4.8, max: 6.5 },
    avgRentStudio: 42000,
    avgRent1BR: 72000,
    avgRent2BR: 115000,
    avgRent3BR: 175000,
    avgPricePerSqft: 1500,
    priceRange: [700000, 10000000],
    totalListings: "1,800+",
    yoyChange: 0.3,
    propertyTypes: ["Apartment", "Penthouse", "Townhouse"],
    zone: "downtown-business-bay",
    coordinates: { lat: 25.1950, lng: 55.3350 },
    description: "Emaar's waterfront mega-development along Dubai Creek. The future Dubai Creek Tower and growing handovers are driving both rental demand and capital appreciation.",
  },

  // ── New Dubai Zone ─────────────────────────────────────────────────────
  {
    id: "jvc",
    name: "Jumeirah Village Circle",
    avgYield: 8.1,
    yieldRange: { min: 7.0, max: 9.2 },
    avgRentStudio: 35000,
    avgRent1BR: 55000,
    avgRent2BR: 80000,
    avgRent3BR: 110000,
    avgPricePerSqft: 850,
    priceRange: [350000, 3500000],
    totalListings: "5,500+",
    yoyChange: 0.4,
    propertyTypes: ["Apartment", "Townhouse", "Villa"],
    zone: "new-dubai",
    coordinates: { lat: 25.0650, lng: 55.2130 },
    description: "JVC consistently ranks among Dubai's highest-yielding communities. Affordable entry prices and strong rental demand from young professionals make it a favourite for investors.",
  },
  {
    id: "jlt",
    name: "Jumeirah Lakes Towers",
    avgYield: 7.2,
    yieldRange: { min: 6.3, max: 8.0 },
    avgRentStudio: 38000,
    avgRent1BR: 62000,
    avgRent2BR: 95000,
    avgRent3BR: 140000,
    avgPricePerSqft: 1000,
    priceRange: [450000, 4000000],
    totalListings: "2,800+",
    yoyChange: 0.1,
    propertyTypes: ["Apartment", "Office"],
    zone: "new-dubai",
    coordinates: { lat: 25.0730, lng: 55.1500 },
    description: "A cluster of towers around man-made lakes with metro access. JLT offers Marina-adjacent living at lower prices, driving strong yields across unit types.",
  },
  {
    id: "dubai-hills",
    name: "Dubai Hills Estate",
    avgYield: 5.4,
    yieldRange: { min: 4.5, max: 6.3 },
    avgRentStudio: null,
    avgRent1BR: 65000,
    avgRent2BR: 100000,
    avgRent3BR: 160000,
    avgPricePerSqft: 1450,
    priceRange: [700000, 20000000],
    totalListings: "3,100+",
    yoyChange: 0.0,
    propertyTypes: ["Apartment", "Townhouse", "Villa"],
    zone: "new-dubai",
    coordinates: { lat: 25.1028, lng: 55.2395 },
    description: "Emaar's green master-planned community with an 18-hole golf course, Dubai Hills Mall, and excellent schools. Strong for families; yields are moderate due to higher capital values.",
  },
  {
    id: "al-furjan",
    name: "Al Furjan",
    avgYield: 7.0,
    yieldRange: { min: 6.0, max: 7.8 },
    avgRentStudio: null,
    avgRent1BR: 50000,
    avgRent2BR: 75000,
    avgRent3BR: 110000,
    avgPricePerSqft: 900,
    priceRange: [450000, 5000000],
    totalListings: "1,500+",
    yoyChange: 0.3,
    propertyTypes: ["Apartment", "Townhouse", "Villa"],
    zone: "new-dubai",
    coordinates: { lat: 25.0380, lng: 55.1470 },
    description: "A well-connected mixed community near Ibn Battuta Mall and the metro. Al Furjan has matured into a reliable mid-market investment with solid returns.",
  },
  {
    id: "palm-jumeirah",
    name: "Palm Jumeirah",
    avgYield: 4.3,
    yieldRange: { min: 3.5, max: 5.2 },
    avgRentStudio: null,
    avgRent1BR: 120000,
    avgRent2BR: 200000,
    avgRent3BR: 350000,
    avgPricePerSqft: 2800,
    priceRange: [1500000, 100000000],
    totalListings: "1,600+",
    yoyChange: -0.5,
    propertyTypes: ["Apartment", "Penthouse", "Villa", "Townhouse"],
    zone: "new-dubai",
    coordinates: { lat: 25.1124, lng: 55.1390 },
    description: "The world's most famous man-made island. Ultra-luxury villas and branded residences command the highest per-sqft prices in Dubai, but yields are compressed at the top end.",
  },
  {
    id: "sports-city",
    name: "Dubai Sports City",
    avgYield: 7.8,
    yieldRange: { min: 6.8, max: 8.5 },
    avgRentStudio: 28000,
    avgRent1BR: 42000,
    avgRent2BR: 62000,
    avgRent3BR: 85000,
    avgPricePerSqft: 650,
    priceRange: [280000, 2500000],
    totalListings: "1,800+",
    yoyChange: 0.5,
    propertyTypes: ["Apartment", "Villa"],
    zone: "new-dubai",
    coordinates: { lat: 25.0380, lng: 55.2230 },
    description: "Built around the International Cricket Stadium, Sports City offers affordable apartments and good-sized villas. Low entry prices translate into attractive gross yields.",
  },
  {
    id: "motor-city",
    name: "Motor City",
    avgYield: 7.4,
    yieldRange: { min: 6.5, max: 8.2 },
    avgRentStudio: null,
    avgRent1BR: 48000,
    avgRent2BR: 72000,
    avgRent3BR: 100000,
    avgPricePerSqft: 750,
    priceRange: [400000, 3500000],
    totalListings: "900+",
    yoyChange: 0.3,
    propertyTypes: ["Apartment", "Townhouse", "Villa"],
    zone: "new-dubai",
    coordinates: { lat: 25.0500, lng: 55.2360 },
    description: "Adjacent to Sports City, Motor City is a mature community with the Autodrome circuit. Family-friendly with parks and retail, delivering consistently high yields.",
  },
  {
    id: "studio-city",
    name: "Dubai Studio City",
    avgYield: 7.5,
    yieldRange: { min: 6.5, max: 8.3 },
    avgRentStudio: 30000,
    avgRent1BR: 45000,
    avgRent2BR: 68000,
    avgRent3BR: 95000,
    avgPricePerSqft: 720,
    priceRange: [320000, 2800000],
    totalListings: "800+",
    yoyChange: 0.4,
    propertyTypes: ["Apartment"],
    zone: "new-dubai",
    coordinates: { lat: 25.0440, lng: 55.2500 },
    description: "Part of the TECOM group, Studio City has seen rapid development with new tower handovers. Affordable prices and proximity to major highways keep yields high.",
  },
  {
    id: "production-city",
    name: "Dubai Production City (IMPZ)",
    avgYield: 8.3,
    yieldRange: { min: 7.2, max: 9.5 },
    avgRentStudio: 25000,
    avgRent1BR: 38000,
    avgRent2BR: 55000,
    avgRent3BR: 75000,
    avgPricePerSqft: 550,
    priceRange: [200000, 1800000],
    totalListings: "700+",
    yoyChange: 0.6,
    propertyTypes: ["Apartment"],
    zone: "new-dubai",
    coordinates: { lat: 25.0430, lng: 55.1980 },
    description: "One of Dubai's most affordable freehold areas. Low purchase prices paired with decent rents from budget-conscious tenants make IMPZ a yield champion.",
  },
  {
    id: "sobha-hartland",
    name: "Sobha Hartland",
    avgYield: 5.2,
    yieldRange: { min: 4.5, max: 6.0 },
    avgRentStudio: null,
    avgRent1BR: 70000,
    avgRent2BR: 110000,
    avgRent3BR: 170000,
    avgPricePerSqft: 1550,
    priceRange: [800000, 15000000],
    totalListings: "1,200+",
    yoyChange: 0.1,
    propertyTypes: ["Apartment", "Villa", "Townhouse"],
    zone: "new-dubai",
    coordinates: { lat: 25.1800, lng: 55.3090 },
    description: "A premium green community in MBR City with lagoons and parks. Sobha's build quality attracts quality tenants; yields are moderate due to higher asking prices.",
  },
  {
    id: "mbr-city",
    name: "Mohammed Bin Rashid City",
    avgYield: 5.6,
    yieldRange: { min: 4.8, max: 6.5 },
    avgRentStudio: null,
    avgRent1BR: 68000,
    avgRent2BR: 105000,
    avgRent3BR: 165000,
    avgPricePerSqft: 1400,
    priceRange: [650000, 18000000],
    totalListings: "2,000+",
    yoyChange: 0.2,
    propertyTypes: ["Apartment", "Villa", "Townhouse"],
    zone: "new-dubai",
    coordinates: { lat: 25.1750, lng: 55.3000 },
    description: "A vast district encompassing District One, Sobha Hartland, and more. Central location between Downtown and Meydan with growing infrastructure and community facilities.",
  },
  {
    id: "damac-hills",
    name: "DAMAC Hills",
    avgYield: 6.2,
    yieldRange: { min: 5.3, max: 7.0 },
    avgRentStudio: null,
    avgRent1BR: 50000,
    avgRent2BR: 80000,
    avgRent3BR: 130000,
    avgPricePerSqft: 950,
    priceRange: [500000, 8000000],
    totalListings: "2,200+",
    yoyChange: 0.2,
    propertyTypes: ["Apartment", "Townhouse", "Villa"],
    zone: "new-dubai",
    coordinates: { lat: 25.0370, lng: 55.2540 },
    description: "Built around the Trump International Golf Club, DAMAC Hills is a self-contained community with schools, retail, and sports facilities. Good mix of affordable and mid-range options.",
  },
  {
    id: "town-square",
    name: "Town Square",
    avgYield: 7.6,
    yieldRange: { min: 6.8, max: 8.5 },
    avgRentStudio: 27000,
    avgRent1BR: 40000,
    avgRent2BR: 58000,
    avgRent3BR: 80000,
    avgPricePerSqft: 650,
    priceRange: [280000, 2200000],
    totalListings: "1,600+",
    yoyChange: 0.5,
    propertyTypes: ["Apartment", "Townhouse"],
    zone: "new-dubai",
    coordinates: { lat: 25.0280, lng: 55.2650 },
    description: "Nshama's affordable master-planned community along Al Qudra Road. Large central park, community retail, and low entry prices create one of Dubai's best yield propositions.",
  },
  {
    id: "jumeirah-park",
    name: "Jumeirah Park",
    avgYield: 5.0,
    yieldRange: { min: 4.2, max: 5.8 },
    avgRentStudio: null,
    avgRent1BR: null,
    avgRent2BR: null,
    avgRent3BR: 150000,
    avgPricePerSqft: 1250,
    priceRange: [2500000, 8000000],
    totalListings: "600+",
    yoyChange: -0.1,
    propertyTypes: ["Villa"],
    zone: "new-dubai",
    coordinates: { lat: 25.0450, lng: 55.1550 },
    description: "A villa-only community near JLT with landscaped parks and community centres. Popular with families; yields are lower due to higher villa prices but tenancies are stable.",
  },

  // ── Old Dubai Zone ─────────────────────────────────────────────────────
  {
    id: "international-city",
    name: "International City",
    avgYield: 8.8,
    yieldRange: { min: 7.5, max: 10.0 },
    avgRentStudio: 22000,
    avgRent1BR: 32000,
    avgRent2BR: 45000,
    avgRent3BR: null,
    avgPricePerSqft: 420,
    priceRange: [180000, 1200000],
    totalListings: "3,000+",
    yoyChange: 0.7,
    propertyTypes: ["Apartment"],
    zone: "old-dubai",
    coordinates: { lat: 25.1700, lng: 55.4100 },
    description: "Dubai's most affordable freehold community. Extremely low purchase prices and steady rental demand from budget tenants make this the city's highest-yielding area.",
  },
  {
    id: "dso",
    name: "Dubai Silicon Oasis",
    avgYield: 7.9,
    yieldRange: { min: 6.8, max: 9.0 },
    avgRentStudio: 26000,
    avgRent1BR: 40000,
    avgRent2BR: 58000,
    avgRent3BR: 82000,
    avgPricePerSqft: 600,
    priceRange: [250000, 3000000],
    totalListings: "2,200+",
    yoyChange: 0.5,
    propertyTypes: ["Apartment", "Townhouse", "Villa"],
    zone: "old-dubai",
    coordinates: { lat: 25.1280, lng: 55.3820 },
    description: "A technology-focused free zone with residential communities. The tech-park ecosystem attracts IT professionals, and low property prices keep yields well above the city average.",
  },
  {
    id: "discovery-gardens",
    name: "Discovery Gardens",
    avgYield: 8.5,
    yieldRange: { min: 7.5, max: 9.5 },
    avgRentStudio: 28000,
    avgRent1BR: 40000,
    avgRent2BR: 55000,
    avgRent3BR: null,
    avgPricePerSqft: 550,
    priceRange: [220000, 1500000],
    totalListings: "1,400+",
    yoyChange: 0.4,
    propertyTypes: ["Apartment"],
    zone: "old-dubai",
    coordinates: { lat: 25.0350, lng: 55.1350 },
    description: "A low-rise garden community near Ibn Battuta Mall with metro access. Budget-friendly apartments with reliable occupancy rates deliver consistently strong yields.",
  },
  {
    id: "al-barsha",
    name: "Al Barsha",
    avgYield: 6.5,
    yieldRange: { min: 5.5, max: 7.5 },
    avgRentStudio: 35000,
    avgRent1BR: 55000,
    avgRent2BR: 82000,
    avgRent3BR: 120000,
    avgPricePerSqft: 1000,
    priceRange: [400000, 5000000],
    totalListings: "1,200+",
    yoyChange: 0.1,
    propertyTypes: ["Apartment", "Villa"],
    zone: "old-dubai",
    coordinates: { lat: 25.1120, lng: 55.1970 },
    description: "A central residential district next to Mall of the Emirates. Mixed housing stock from apartments to villas, with good metro connectivity and established retail.",
  },
  {
    id: "mirdif",
    name: "Mirdif",
    avgYield: 5.8,
    yieldRange: { min: 5.0, max: 6.5 },
    avgRentStudio: null,
    avgRent1BR: 45000,
    avgRent2BR: 65000,
    avgRent3BR: 100000,
    avgPricePerSqft: 900,
    priceRange: [600000, 5000000],
    totalListings: "900+",
    yoyChange: 0.0,
    propertyTypes: ["Apartment", "Villa", "Townhouse"],
    zone: "old-dubai",
    coordinates: { lat: 25.2190, lng: 55.4180 },
    description: "A family favourite in eastern Dubai with Mirdif City Centre, parks, and a suburban feel. Mixed leasehold/freehold options with steady long-term tenancies.",
  },

  // ── Suburban Zone ──────────────────────────────────────────────────────
  {
    id: "arabian-ranches",
    name: "Arabian Ranches",
    avgYield: 4.5,
    yieldRange: { min: 3.8, max: 5.2 },
    avgRentStudio: null,
    avgRent1BR: null,
    avgRent2BR: null,
    avgRent3BR: 180000,
    avgPricePerSqft: 1350,
    priceRange: [2000000, 15000000],
    totalListings: "800+",
    yoyChange: -0.2,
    propertyTypes: ["Villa", "Townhouse"],
    zone: "suburban",
    coordinates: { lat: 25.0600, lng: 55.2700 },
    description: "Dubai's original premium villa community with golf course, equestrian centre, and top schools. Established families create stable long-term tenancies despite lower yields.",
  },
  {
    id: "arabian-ranches-2",
    name: "Arabian Ranches 2",
    avgYield: 5.0,
    yieldRange: { min: 4.2, max: 5.8 },
    avgRentStudio: null,
    avgRent1BR: null,
    avgRent2BR: null,
    avgRent3BR: 160000,
    avgPricePerSqft: 1200,
    priceRange: [1800000, 10000000],
    totalListings: "700+",
    yoyChange: 0.1,
    propertyTypes: ["Villa", "Townhouse"],
    zone: "suburban",
    coordinates: { lat: 25.0700, lng: 55.2850 },
    description: "The newer extension of Arabian Ranches with contemporary designs and community pools. Slightly better yields than AR1 due to lower entry prices.",
  },
  {
    id: "the-springs",
    name: "The Springs",
    avgYield: 4.8,
    yieldRange: { min: 4.0, max: 5.5 },
    avgRentStudio: null,
    avgRent1BR: null,
    avgRent2BR: 90000,
    avgRent3BR: 130000,
    avgPricePerSqft: 1150,
    priceRange: [1800000, 5000000],
    totalListings: "500+",
    yoyChange: -0.1,
    propertyTypes: ["Villa", "Townhouse"],
    zone: "suburban",
    coordinates: { lat: 25.0650, lng: 55.1720 },
    description: "Lakeside villa community by Emaar near Emirates Living. Compact villas around man-made lakes with a mature landscape. Yields are modest but vacancy rates are very low.",
  },
  {
    id: "meadows",
    name: "The Meadows",
    avgYield: 4.4,
    yieldRange: { min: 3.7, max: 5.0 },
    avgRentStudio: null,
    avgRent1BR: null,
    avgRent2BR: null,
    avgRent3BR: 180000,
    avgPricePerSqft: 1400,
    priceRange: [3000000, 10000000],
    totalListings: "350+",
    yoyChange: -0.2,
    propertyTypes: ["Villa"],
    zone: "suburban",
    coordinates: { lat: 25.0740, lng: 55.1680 },
    description: "Larger villas in the Emirates Living cluster. Meadows offers spacious family homes with park views. High capital values keep yields below average, but demand is unwavering.",
  },
  {
    id: "damac-hills-2",
    name: "DAMAC Hills 2 (Akoya)",
    avgYield: 7.8,
    yieldRange: { min: 6.8, max: 8.8 },
    avgRentStudio: null,
    avgRent1BR: 32000,
    avgRent2BR: 48000,
    avgRent3BR: 65000,
    avgPricePerSqft: 520,
    priceRange: [250000, 3000000],
    totalListings: "2,500+",
    yoyChange: 0.6,
    propertyTypes: ["Apartment", "Townhouse", "Villa"],
    zone: "suburban",
    coordinates: { lat: 25.0100, lng: 55.2700 },
    description: "An affordable suburban community further along Al Qudra Road. Very low prices for townhouses and villas generate impressive yields, though the location is more remote.",
  },

  // ── Emerging Zone ──────────────────────────────────────────────────────
  {
    id: "dubai-south",
    name: "Dubai South",
    avgYield: 7.5,
    yieldRange: { min: 6.5, max: 8.5 },
    avgRentStudio: 25000,
    avgRent1BR: 38000,
    avgRent2BR: 55000,
    avgRent3BR: 75000,
    avgPricePerSqft: 620,
    priceRange: [280000, 3500000],
    totalListings: "1,800+",
    yoyChange: 0.8,
    propertyTypes: ["Apartment", "Townhouse", "Villa"],
    zone: "emerging",
    coordinates: { lat: 24.9530, lng: 55.1680 },
    description: "The aerotropolis around Al Maktoum International Airport and Expo City. Massive infrastructure investment and the new airport expansion are driving strong growth expectations.",
  },
  {
    id: "arjan",
    name: "Arjan (Dubailand)",
    avgYield: 8.0,
    yieldRange: { min: 7.0, max: 9.0 },
    avgRentStudio: 30000,
    avgRent1BR: 48000,
    avgRent2BR: 68000,
    avgRent3BR: 90000,
    avgPricePerSqft: 700,
    priceRange: [300000, 2500000],
    totalListings: "2,000+",
    yoyChange: 0.5,
    propertyTypes: ["Apartment"],
    zone: "emerging",
    coordinates: { lat: 25.0560, lng: 55.2320 },
    description: "An emerging cluster in Dubailand with a wave of new handovers. Butterfly Museum and Miracle Garden are nearby. Low prices and rising rents are creating an investor hotspot.",
  },
  {
    id: "dubai-land",
    name: "Dubailand",
    avgYield: 7.3,
    yieldRange: { min: 6.2, max: 8.2 },
    avgRentStudio: 28000,
    avgRent1BR: 42000,
    avgRent2BR: 60000,
    avgRent3BR: 85000,
    avgPricePerSqft: 680,
    priceRange: [280000, 4000000],
    totalListings: "2,800+",
    yoyChange: 0.4,
    propertyTypes: ["Apartment", "Townhouse", "Villa"],
    zone: "emerging",
    coordinates: { lat: 25.0700, lng: 55.3000 },
    description: "A sprawling development zone encompassing multiple sub-communities. Increasing handovers and improving infrastructure are gradually shifting Dubailand from speculative to established.",
  },
  {
    id: "jvt",
    name: "Jumeirah Village Triangle",
    avgYield: 7.6,
    yieldRange: { min: 6.5, max: 8.5 },
    avgRentStudio: 32000,
    avgRent1BR: 50000,
    avgRent2BR: 72000,
    avgRent3BR: 100000,
    avgPricePerSqft: 780,
    priceRange: [350000, 3000000],
    totalListings: "1,400+",
    yoyChange: 0.3,
    propertyTypes: ["Apartment", "Townhouse", "Villa"],
    zone: "emerging",
    coordinates: { lat: 25.0600, lng: 55.2050 },
    description: "The triangular sibling of JVC with a similar mix of apartments and villas. Slightly less dense, with green spaces and community facilities attracting families and investors alike.",
  },
  {
    id: "tilal-al-ghaf",
    name: "Tilal Al Ghaf",
    avgYield: 4.8,
    yieldRange: { min: 4.0, max: 5.5 },
    avgRentStudio: null,
    avgRent1BR: null,
    avgRent2BR: null,
    avgRent3BR: 200000,
    avgPricePerSqft: 1600,
    priceRange: [2500000, 25000000],
    totalListings: "400+",
    yoyChange: 0.2,
    propertyTypes: ["Villa", "Townhouse"],
    zone: "emerging",
    coordinates: { lat: 25.0340, lng: 55.2200 },
    description: "Majid Al Futtaim's lagoon community with crystal-clear swimming lagoons. A premium emerging address that's expected to appreciate significantly as phases complete.",
  },
  {
    id: "the-valley",
    name: "The Valley",
    avgYield: 6.0,
    yieldRange: { min: 5.2, max: 6.8 },
    avgRentStudio: null,
    avgRent1BR: null,
    avgRent2BR: 65000,
    avgRent3BR: 95000,
    avgPricePerSqft: 850,
    priceRange: [1200000, 5000000],
    totalListings: "600+",
    yoyChange: 0.4,
    propertyTypes: ["Townhouse", "Villa"],
    zone: "emerging",
    coordinates: { lat: 25.0480, lng: 55.3050 },
    description: "Emaar's desert community along the Dubai–Al Ain Road. Town centres, sports facilities, and a growing family demographic are building momentum for both rents and values.",
  },
  {
    id: "dubai-islands",
    name: "Dubai Islands (Deira Islands)",
    avgYield: 5.8,
    yieldRange: { min: 5.0, max: 6.5 },
    avgRentStudio: 45000,
    avgRent1BR: 70000,
    avgRent2BR: 110000,
    avgRent3BR: null,
    avgPricePerSqft: 1400,
    priceRange: [600000, 8000000],
    totalListings: "1,000+",
    yoyChange: 0.6,
    propertyTypes: ["Apartment", "Penthouse"],
    zone: "emerging",
    coordinates: { lat: 25.2750, lng: 55.3200 },
    description: "A massive waterfront development off the coast of Deira. Early handovers are commanding strong rents, and the sheer scale of planned amenities positions this as a future landmark.",
  },
  {
    id: "al-jaddaf",
    name: "Al Jaddaf",
    avgYield: 6.8,
    yieldRange: { min: 5.8, max: 7.5 },
    avgRentStudio: 35000,
    avgRent1BR: 55000,
    avgRent2BR: 82000,
    avgRent3BR: 115000,
    avgPricePerSqft: 950,
    priceRange: [400000, 3500000],
    totalListings: "800+",
    yoyChange: 0.4,
    propertyTypes: ["Apartment"],
    zone: "emerging",
    coordinates: { lat: 25.2150, lng: 55.3280 },
    description: "A cultural district along the Creek with the Jameel Arts Centre and upcoming museums. Proximity to Downtown and Healthcare City is attracting developers and tenants.",
  },
  {
    id: "ras-al-khor",
    name: "Ras Al Khor Industrial / Meydan",
    avgYield: 6.5,
    yieldRange: { min: 5.5, max: 7.5 },
    avgRentStudio: null,
    avgRent1BR: 55000,
    avgRent2BR: 85000,
    avgRent3BR: 130000,
    avgPricePerSqft: 1050,
    priceRange: [500000, 6000000],
    totalListings: "1,100+",
    yoyChange: 0.3,
    propertyTypes: ["Apartment", "Townhouse", "Villa"],
    zone: "emerging",
    coordinates: { lat: 25.1830, lng: 55.3460 },
    description: "The Meydan One district adjacent to the racecourse is rapidly transforming. Planned mega-mall, canal, and tower projects are set to redefine this area over the next few years.",
  },
];
