-- ─────────────────────────────────────────────────────────────────────────
-- toShare file-sharing bucket + helpers.
--
-- Files uploaded for sharing land in the private `toshare-files` bucket.
-- Public viewers download via signed URL generated by the API route at
-- request time (with optional password gate).
-- ─────────────────────────────────────────────────────────────────────────

-- Bucket (private — never directly accessible)
insert into storage.buckets (id, name, public, file_size_limit)
values ('toshare-files', 'toshare-files', false, 104857600) -- 100MB cap
on conflict (id) do nothing;

-- Authenticated users upload to their own folder: `<user_id>/<filename>`
create policy "toshare-files_owner_write"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'toshare-files'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "toshare-files_owner_read"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'toshare-files'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "toshare-files_owner_delete"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'toshare-files'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- RPC for the public download endpoint to record the download event.
create or replace function public.toshare_record_download(
  p_link_id  uuid,
  p_ip_hash  text,
  p_ua_hash  text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_link record;
  v_count int;
begin
  select * into v_link
    from public.toshare_links
   where id = p_link_id
     and status = 'active'
     and (expires_at is null or expires_at > now())
     and type = 'file';

  if not found then
    return false;
  end if;

  -- Optional max-downloads guard
  if (v_link.payload->>'maxDownloads')::int is not null then
    v_count := coalesce((v_link.payload->>'downloadCount')::int, 0);
    if v_count >= (v_link.payload->>'maxDownloads')::int then
      return false;
    end if;
  end if;

  update public.toshare_links
     set view_count = view_count + 1,
         payload = jsonb_set(
           payload,
           '{downloadCount}',
           to_jsonb(coalesce((payload->>'downloadCount')::int, 0) + 1)
         ),
         updated_at = now()
   where id = p_link_id;

  insert into public.toshare_events (link_id, event, ip_hash, ua_hash)
  values (p_link_id, 'redirect', p_ip_hash, p_ua_hash);

  return true;
end;
$$;

grant execute on function public.toshare_record_download to anon, authenticated;

comment on function public.toshare_record_download is
  'Atomically increments download count + emits a redirect event. Returns false if maxDownloads reached or link expired.';
